return {
    keys={
        Bufftip="工具提示", Targetattach5="效果 - 目标附加点6", TargetArt="效果 - 目标", 
        Targetattach4="效果 - 目标附加点5", race="种族", isEffect="是区域效果", 
        LightningEffect="效果 - 闪电效果", Targetattach="效果 - 目标附加点1", 
        MissileHoming="效果 - 射弹自导允许", EffectArt="效果 - 点目标", Effectsound="声音效果", 
        Missileart="效果 - 投射物图像", Buffubertip="工具提示 - 扩展", 
        Effectsoundlooped="声音效果(循环)", Targetattach2="效果 - 目标附加点3", 
        Targetattach1="效果 - 目标附加点2", EditorSuffix="编辑器后缀", 
        Targetattach3="效果 - 目标附加点4", Effectattach="效果 - 点目标附加点", 
        EditorName="名字(编辑器)", Specialattach="效果 -特殊附加点", 
        Targetattachcount="效果 - 目标 - 附加数量", Missilearc="效果 - 射弹弧度", 
        Buffart="图标", Missilespeed="效果 - 射弹速度", SpecialArt="效果 -特殊", 
        Spelldetail="效果显示需求", 
    },
    items={
        Bdbb={
            Buffubertip="这个单位具有额外的生命值和魔法值。但是这个额外的值会消失得很快。", 
            Bufftip="吸取生命值和魔法值", race="human", Spelldetail=0, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNLifeDrain.blp", Missilespeed=0, Targetattachcount=0, 
            MissileHoming=0, 
        },
        BUfa={
            Buffubertip="该单位有着霜冻护甲; 因此其护甲加强了，攻击它的近战单位也会被在短时间内减速。", 
            Bufftip="霜冻护甲", race="undead", Specialattach="chest", Targetattachcount=0, 
            TargetArt="Abilities\\Spells\\Undead\\FrostArmor\\FrostArmorTarget.mdl", Targetattach="chest", 
            Spelldetail=1, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNFrostArmor.blp", Missilespeed=0, 
            SpecialArt="Abilities\\Spells\\Undead\\FrostArmor\\FrostArmorDamage.mdl", MissileHoming=0, 
        },
        Bspo={
            Buffubertip="该单位受到了慢性毒药的攻击，因此其移动速度和攻击速度都减慢了，而且会在一定时间内持续地受到伤害。", 
            Bufftip="慢性毒药", race="nightelf", EditorSuffix=" (没有堆积)", Targetattachcount=0, Spelldetail=2, 
            isEffect=0, Missilearc=0.0, Buffart="ReplaceableTextures\\CommandButtons\\BTNSlowPoison.blp", 
            MissileHoming=0, TargetArt="Abilities\\Weapons\\PoisonSting\\PoisonStingTarget.mdl", Missilespeed=0, 
        },
        Bpos={
            Buffubertip="该单位被占据了。", Bufftip="占据", race="undead", 
            TargetArt="Abilities\\Spells\\Undead\\Possession\\PossessionTarget.mdl", Targetattachcount=0, 
            Spelldetail=0, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNPossession.blp", Missilespeed=0, 
            Targetattach="overhead", MissileHoming=0, 
        },
        BUan={
            Buffubertip="召唤出来的单位会受到驱逐魔法的伤害。", Bufftip="操纵死尸", 
            race="undead", Targetattachcount=0, Spelldetail=0, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNAnimateDead.blp", Missilespeed=0, 
            SpecialArt="Objects\\Spawnmodels\\Undead\\UndeadLargeDeathExplode\\UndeadLargeDeathExplode.mdl", 
            MissileHoming=0, 
        },
        BNpi={
            Specialattach="head", race="other", EditorSuffix=" (中立的单位但是是敌对的1)", 
            EditorName="永久的献祭", Spelldetail=0, isEffect=0, Missilearc=0.0, Targetattachcount=0, Missilespeed=0, 
            SpecialArt="Abilities\\Spells\\NightElf\\Immolation\\ImmolationDamage.mdl", MissileHoming=0, 
        },
        BNbf={
            Buffubertip="该单位受到了火焰呼吸的攻击，因此它会持续地受到火焰的伤害。", 
            Bufftip="火焰呼吸", TargetArt="Abilities\\Spells\\Other\\BreathOfFire\\BreathOfFireDamage.mdl", 
            race="other", Spelldetail=0, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNBreathOfFire.blp", Missilespeed=0, Targetattachcount=0, 
            MissileHoming=0, 
        },
        Brai={
            Buffubertip="召唤出来的单位会受到驱逐魔法的伤害。", Bufftip="骷髅战士", 
            race="undead", Spelldetail=0, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNSkeletonWarrior.blp", Missilespeed=0, 
            Targetattachcount=0, MissileHoming=0, 
        },
        BNvc={
            Buffubertip="火山爆发", Bufftip="火山爆发", race="other", 
            TargetArt="Abilities\\Spells\\Human\\Thunderclap\\ThunderclapTarget.mdl", Targetattachcount=0, 
            Spelldetail=0, isEffect=0, Missilearc=0.0, Buffart="ReplaceableTextures\\CommandButtons\\BTNVolcano.blp", 
            Missilespeed=0, Targetattach="overhead", MissileHoming=0, 
        },
        Btrv={
            EditorName="传送 显示", Spelldetail=0, isEffect=0, Missilearc=0.0, race="other", Missilespeed=0, 
            Targetattachcount=0, MissileHoming=0, 
        },
        Xfus={
            Targetattach1="sprite,fourth", Targetattachcount=2, race="undead", 
            TargetArt="Environment\\UndeadBuildingFire\\UndeadSmallBuildingFire2.mdl,Environment\\UndeadBuildingFire\\UndeadSmallBuildingFire1.mdl", 
            EditorName="建筑物伤害 – 不死族 小", Spelldetail=0, isEffect=1, Missilearc=0.0, 
            Effectsoundlooped="UndeadFireSmall", Missilespeed=0, Targetattach="sprite,first", MissileHoming=0, 
        },
        Xfum={
            Targetattach1="sprite,second", Targetattachcount=4, race="undead", Targetattach2="sprite,fourth", 
            Targetattach3="sprite,fifth", 
            TargetArt="Environment\\UndeadBuildingFire\\UndeadLargeBuildingFire2.mdl,Environment\\UndeadBuildingFire\\UndeadSmallBuildingFire1.mdl,Environment\\UndeadBuildingFire\\UndeadLargeBuildingFire0.mdl,Environment\\UndeadBuildingFire\\UndeadSmallBuildingFire2.mdl", 
            EditorName="建筑物伤害 – 不死族  中", Spelldetail=0, isEffect=1, Missilearc=0.0, 
            Effectsoundlooped="UndeadFireMedium", Missilespeed=0, Targetattach="sprite,first", MissileHoming=0, 
        },
        BNpa={
            Buffubertip="这个单位已被寄生虫侵扰，它将随着时间逝去而受伤害，如果在它死时仍然在被折磨，一个单位将会从它的尸体上诞生。", 
            Bufftip="寄生虫", race="other", TargetArt="Abilities\\Spells\\Other\\Parasite\\ParasiteTarget.mdl", 
            Targetattachcount=0, Spelldetail=0, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNParasite.blp", Missilespeed=0, Targetattach="overhead", 
            MissileHoming=0, 
        },
        BNhs={
            Buffubertip="这个单位正在接受医疗气雾的治疗。", Bufftip="医疗气雾", race="other", 
            Spelldetail=0, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNHealingSpray.blp", Missilespeed=0, Targetattachcount=0, 
            MissileHoming=0, 
        },
        BIil={
            Buffubertip="该单位是一个幻象，因此将从敌人那里得到额外的伤害。", 
            Bufftip="幻象物品", race="other", Targetattachcount=0, Spelldetail=0, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNWand.blp", Missilespeed=0, 
            SpecialArt="Abilities\\Spells\\Orc\\MirrorImage\\MirrorImageDeathCaster.mdl", MissileHoming=0, 
        },
        BHbn={
            Buffubertip="该单位被驱散了并处于虚无状态之中。被化为虚无的单位不能攻击，但是能施放魔法。敌人的魔法也会对其造成额外的伤害。", 
            Bufftip="驱散", race="human", TargetArt="Abilities\\Spells\\Human\\Banish\\BanishTarget.mdl", 
            Targetattachcount=0, Spelldetail=0, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNBanish.blp", MissileHoming=0, Missilespeed=0, 
            Effectsoundlooped="BanishLoop", 
        },
        BEfn={
            Buffubertip="召唤出来的单位会受到驱逐魔法的伤害。", Bufftip="自然之力", 
            race="nightelf", Spelldetail=0, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNEnt.blp", Missilespeed=0, Targetattachcount=0, 
            MissileHoming=0, 
        },
        BIrb={
            Buffubertip="这个单位重生了。", 
            EffectArt="Abilities\\Spells\\Orc\\FeralSpirit\\feralspiritdone.mdl", race="other", Targetattachcount=0, 
            Spelldetail=0, isEffect=0, Missilearc=0.0, Buffart="ReplaceableTextures\\CommandButtons\\BTNRune.blp", 
            MissileHoming=0, Missilespeed=0, Bufftip="再生", 
        },
        BUad={
            EditorName="操纵死尸(额外的)", Spelldetail=0, isEffect=0, Missilearc=0.0, race="undead", 
            Missilespeed=0, Targetattachcount=0, MissileHoming=0, 
        },
        Xful={
            race="undead", Targetattach1="sprite,second", Targetattach2="sprite,fifth", Targetattachcount=6, 
            Targetattach5="sprite,sixth", Targetattach4="sprite,fourth", Targetattach3="sprite,third", 
            TargetArt="Environment\\UndeadBuildingFire\\UndeadLargeBuildingFire1.mdl,Environment\\UndeadBuildingFire\\UndeadLargeBuildingFire0.mdl,Environment\\UndeadBuildingFire\\UndeadLargeBuildingFire0.mdl,Environment\\UndeadBuildingFire\\UndeadSmallBuildingFire1.mdl,Environment\\UndeadBuildingFire\\UndeadLargeBuildingFire2.mdl,Environment\\UndeadBuildingFire\\UndeadSmallBuildingFire0.mdl", 
            EditorName="建筑物伤害 – 不死族  大", Spelldetail=0, isEffect=1, Missilearc=0.0, 
            Effectsoundlooped="UndeadFireLarge", Missilespeed=0, Targetattach="sprite,first", MissileHoming=0, 
        },
        Xfos={
            Targetattach1="sprite,fourth", Targetattachcount=2, race="orc", 
            TargetArt="Environment\\SmallBuildingFire\\SmallBuildingFire2.mdl,Environment\\SmallBuildingFire\\SmallBuildingFire1.mdl", 
            EditorName="建筑物伤害 – 兽族  小", Spelldetail=0, isEffect=1, Missilearc=0.0, 
            Effectsoundlooped="HumanFireSmall", Missilespeed=0, Targetattach="sprite,first", MissileHoming=0, 
        },
        BIrg={
            Buffubertip="该单位将会逐渐恢复生命值和魔力值。", Bufftip="生命恢复", race="other", 
            Targetattach="origin", Targetattachcount=2, EditorSuffix=" (物品)", Targetattach1="origin", Spelldetail=0, 
            isEffect=0, Missilearc=0.0, Buffart="ReplaceableTextures\\CommandButtons\\BTNGreaterRejuvScroll.blp", 
            MissileHoming=0, 
            TargetArt="Abilities\\Spells\\Other\\ANrl\\ANrlTarget.mdl,Abilities\\Spells\\Other\\ANrm\\ANrmTarget.mdl", 
            Missilespeed=0, 
        },
        BHbz={
            EditorName="暴风雪 (施法者)", Spelldetail=0, isEffect=0, Missilearc=0.0, race="human", Missilespeed=0, 
            Targetattachcount=0, MissileHoming=0, 
        },
        Beye={
            Buffubertip="召唤出来的单位会受到驱逐魔法的伤害。", Bufftip="岗哨守卫", 
            race="orc", Spelldetail=0, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNSentryWard.blp", Missilespeed=0, Targetattachcount=0, 
            MissileHoming=0, 
        },
        Xfom={
            Targetattach1="sprite,second", Targetattachcount=4, race="orc", Targetattach2="sprite,fourth", 
            Targetattach3="sprite,fifth", 
            TargetArt="Environment\\LargeBuildingFire\\LargeBuildingFire2.mdl,Environment\\SmallBuildingFire\\SmallBuildingFire1.mdl,Environment\\LargeBuildingFire\\LargeBuildingFire0.mdl,Environment\\SmallBuildingFire\\SmallBuildingFire2.mdl", 
            EditorName="建筑物伤害 – 兽族  中", Spelldetail=0, isEffect=1, Missilearc=0.0, 
            Effectsoundlooped="HumanFireMedium", Missilespeed=0, Targetattach="sprite,first", MissileHoming=0, 
        },
        Xfol={
            race="orc", Targetattach1="sprite,second", Targetattach2="sprite,fifth", Targetattachcount=6, 
            Targetattach5="sprite,sixth", Targetattach4="sprite,fourth", Targetattach3="sprite,third", 
            TargetArt="Environment\\LargeBuildingFire\\LargeBuildingFire1.mdl,Environment\\LargeBuildingFire\\LargeBuildingFire0.mdl,Environment\\LargeBuildingFire\\LargeBuildingFire0.mdl,Environment\\SmallBuildingFire\\SmallBuildingFire1.mdl,Environment\\LargeBuildingFire\\LargeBuildingFire1.mdl,Environment\\SmallBuildingFire\\SmallBuildingFire0.mdl", 
            EditorName="建筑物伤害 – 兽族  大", Spelldetail=0, isEffect=1, Missilearc=0.0, 
            Effectsoundlooped="HumanFireLarge", Missilespeed=0, Targetattach="sprite,first", MissileHoming=0, 
        },
        BOae={
            Buffubertip="该单位处在耐久光环的作用之下，因此其移动速度和攻击速度都加快了。", 
            Bufftip="耐久光环", race="orc", 
            TargetArt="Abilities\\Spells\\Other\\GeneralAuraTarget\\GeneralAuraTarget.mdl", Targetattachcount=0, 
            Spelldetail=2, isEffect=0, Missilearc=0.0, Buffart="ReplaceableTextures\\CommandButtons\\BTNCommand.blp", 
            Missilespeed=0, Targetattach="origin", MissileHoming=0, 
        },
        Xfns={
            Targetattach1="sprite,fourth", Targetattachcount=2, race="nightelf", 
            TargetArt="Environment\\NightElfBuildingFire\\ElfSmallBuildingFire2.mdl,Environment\\NightElfBuildingFire\\ElfSmallBuildingFire1.mdl", 
            EditorName="建筑物伤害 - 暗夜精灵族 小", Spelldetail=0, isEffect=1, Missilearc=0.0, 
            Effectsoundlooped="NightElfFireSmall", Missilespeed=0, Targetattach="sprite,first", MissileHoming=0, 
        },
        BImo={
            Buffubertip="周围的中立单位都将受到诱惑而为你服务。", Bufftip="怪兽诱捕守卫", 
            Spelldetail=0, isEffect=0, Missilearc=0.0, race="other", Missilespeed=0, Targetattachcount=0, MissileHoming=0, 
        },
        Xfnm={
            Targetattach1="sprite,second", Targetattachcount=4, race="nightelf", Targetattach2="sprite,fourth", 
            Targetattach3="sprite,fifth", 
            TargetArt="Environment\\NightElfBuildingFire\\ElfLargeBuildingFire2.mdl,Environment\\NightElfBuildingFire\\ElfSmallBuildingFire1.mdl,Environment\\NightElfBuildingFire\\ElfLargeBuildingFire0.mdl,Environment\\NightElfBuildingFire\\ElfSmallBuildingFire2.mdl", 
            EditorName="建筑物伤害 - 暗夜精灵族 中", Spelldetail=0, isEffect=1, Missilearc=0.0, 
            Effectsoundlooped="NightElfFireMedium", Missilespeed=0, Targetattach="sprite,first", MissileHoming=0, 
        },
        BHds={
            Buffubertip="该单位处于神圣护甲的保护之下，因此是无敌的。", 
            Bufftip="神圣护甲", race="human", 
            TargetArt="Abilities\\Spells\\Human\\DivineShield\\DivineShieldTarget.mdl", Targetattachcount=0, 
            Spelldetail=0, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNDivineIntervention.blp", Missilespeed=0, 
            Targetattach="origin", MissileHoming=0, 
        },
        Bstt={
            Buffubertip="这个守卫被激活的话会击晕周围敌方的地面单位。", 
            Bufftip="静止陷阱", race="orc", Spelldetail=0, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNStasisTrap.blp", Missilespeed=0, Targetattachcount=0, 
            MissileHoming=0, 
        },
        BNpm={
            Buffubertip="这个单位已被寄生虫侵扰，它将随着时间逝去而受伤害，如果在它死时仍然在被折磨，一个单位将会从它的尸体上诞生。", 
            Bufftip="寄生虫", EditorSuffix=" (奴)", race="other", Spelldetail=0, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNParasite.blp", MissileHoming=0, Targetattachcount=0, 
            Missilespeed=0, 
        },
        BHtb={
            Buffubertip="该单位遭到了风暴之锤的攻击，因此不能移动，攻击或者施放魔法。", 
            Bufftip="风暴之锤", race="other", 
            TargetArt="Abilities\\Spells\\Human\\StormBolt\\StormBoltTarget.mdl", Targetattachcount=0, 
            Spelldetail=0, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNStormBolt.blp", Missilespeed=0, 
            Targetattach="overhead", MissileHoming=0, 
        },
        Bpoc={
            Targetattachcount=0, TargetArt="Abilities\\Spells\\Undead\\Possession\\PossessionCaster.mdl", 
            EditorName="占据 (施法者)", Spelldetail=0, isEffect=0, Missilearc=0.0, Targetattach="overhead", 
            MissileHoming=0, race="undead", Missilespeed=0, 
        },
        Bbof={
            Buffubertip="此单位已被燃烧之油烧着，它将不断的受到伤害。", 
            Bufftip="燃烧之油", 
            TargetArt="Abilities\\Spells\\Human\\FlameStrike\\FlameStrikeDamageTarget.mdl", race="orc", 
            Spelldetail=0, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNWallOfFire.blp", Missilespeed=0, Targetattachcount=0, 
            MissileHoming=0, 
        },
        Xfnl={
            race="nightelf", Targetattach1="sprite,second", Targetattach2="sprite,fifth", Targetattachcount=6, 
            Targetattach5="sprite,sixth", Targetattach4="sprite,fourth", Targetattach3="sprite,third", 
            TargetArt="Environment\\NightElfBuildingFire\\ElfLargeBuildingFire1.mdl,Environment\\NightElfBuildingFire\\ElfLargeBuildingFire0.mdl,Environment\\NightElfBuildingFire\\ElfLargeBuildingFire0.mdl,Environment\\NightElfBuildingFire\\ElfSmallBuildingFire1.mdl,Environment\\NightElfBuildingFire\\ElfLargeBuildingFire2.mdl,Environment\\NightElfBuildingFire\\ElfSmallBuildingFire0.mdl", 
            EditorName="建筑物伤害 - 暗夜精灵族 大", Spelldetail=0, isEffect=1, Missilearc=0.0, 
            Effectsoundlooped="NightElfFireLarge", Missilespeed=0, Targetattach="sprite,first", MissileHoming=0, 
        },
        Xfla={
            Targetattachcount=0, EditorName="照明弹(效果)", Spelldetail=0, isEffect=1, Missilearc=0.0, race="human", 
            Missilespeed=0, EffectArt="Abilities\\Spells\\Human\\Flare\\FlareTarget.mdl", MissileHoming=0, 
        },
        Bclf={
            Buffubertip="该建筑物中了乌云技能，所以丧失了远程攻击的能力。", 
            Bufftip="乌云技能", race="human", Spelldetail=0, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNCloudOfFog.blp", Missilespeed=0, Targetattachcount=0, 
            MissileHoming=0, 
        },
        BOvd={
            Buffubertip="该单位处在巫毒的作用之下, 因此暂时是无敌的。", Bufftip="巫毒", 
            race="orc", TargetArt="Abilities\\Spells\\Orc\\Voodoo\\VoodooAuraTarget.mdl", Targetattachcount=0, 
            Spelldetail=0, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNBigBadVoodooSpell.blp", Missilespeed=0, 
            Targetattach="overhead", MissileHoming=0, 
        },
        BNsi={
            Buffubertip="该单位受到了沉默魔法的攻击，因此其不能施放任何魔法。", 
            Bufftip="沉默魔法", race="other", TargetArt="Abilities\\Spells\\Other\\Silence\\SilenceTarget.mdl", 
            Targetattachcount=0, Spelldetail=0, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNSilence.blp", Missilespeed=0, Targetattach="overhead", 
            MissileHoming=0, 
        },
        Bhwd={
            Buffubertip="这个守卫能恢复周围单位的生命值。", Bufftip="治疗守卫", race="orc", 
            Spelldetail=0, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNHealingWard.blp", Missilespeed=0, Targetattachcount=0, 
            MissileHoming=0, 
        },
        BOwk={
            Buffubertip="此单位处于疾步风的作用之下， 因此其变为隐形了，移动地也更加快了。隐形状态中的第一次攻击会造成额外的伤害。", 
            Bufftip="疾步风", race="orc", Spelldetail=0, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNWindWalkOn.blp", Missilespeed=0, Targetattachcount=0, 
            MissileHoming=0, 
        },
        XEsf={
            Targetattachcount=0, EditorName="群星坠落(效果)", Spelldetail=0, isEffect=1, Missilearc=0.0, 
            race="nightelf", Missilespeed=0, EffectArt="Abilities\\Spells\\NightElf\\Starfall\\StarfallCaster.mdl", 
            MissileHoming=0, 
        },
        BNbr={
            Buffubertip="该单位具有战争咆哮技能，因此它的攻击力增加了。", 
            Bufftip="战争咆哮", race="other", 
            TargetArt="Abilities\\Spells\\NightElf\\BattleRoar\\RoarTarget.mdl", Targetattachcount=0, Spelldetail=1, 
            isEffect=0, Missilearc=0.0, Buffart="ReplaceableTextures\\CommandButtons\\BTNBattleRoar.blp", 
            Missilespeed=0, Targetattach="overhead", MissileHoming=0, 
        },
        BEer={
            Buffubertip="该单位受到了纠缠根须的攻击，因此其不能移动并在一定时间内会持续受到伤害。", 
            Bufftip="纠缠根须", race="nightelf", 
            TargetArt="Abilities\\Spells\\NightElf\\EntanglingRoots\\EntanglingRootsTarget.mdl", 
            Targetattachcount=0, Spelldetail=0, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNEntanglingRoots.blp", Missilespeed=0, 
            Targetattach="origin", MissileHoming=0, 
        },
        Brpb={
            Buffubertip="这个单位被恢复魔法击中；它的一部分生命值和魔法值被恢复。", 
            Bufftip="恢复", race="undead", Spelldetail=0, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNReplenishMana.blp", Missilespeed=0, 
            Targetattachcount=0, MissileHoming=0, 
        },
        Bfre={
            EditorName="冰冻", Spelldetail=0, isEffect=0, Missilearc=0.0, race="other", Missilespeed=0, 
            Targetattachcount=0, MissileHoming=0, 
        },
        BOwd={
            Buffubertip="召唤出来的单位会受到驱逐魔法的伤害。", Bufftip="守卫", Spelldetail=0, 
            isEffect=0, Missilearc=0.0, race="orc", Missilespeed=0, Targetattachcount=0, MissileHoming=0, 
        },
        BNab={
            Buffubertip="这个单位遭到了酸性炸弹的攻击。 它的护甲被减弱，并会持续地受到伤害。", 
            Bufftip="酸性炸弹", race="other", TargetArt="Abilities\\Spells\\Other\\AcidBomb\\BottleImpact.mdl", 
            Targetattachcount=0, Spelldetail=0, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNAcidBomb.blp", Missilespeed=0, Targetattach="chest", 
            MissileHoming=0, 
        },
        Xesn={
            Targetattachcount=0, TargetArt="Units\\NightElf\\Owl\\Owl.mdl", EditorName="哨兵(效果)", 
            Spelldetail=0, isEffect=1, Missilearc=0.0, Targetattach="overhead", MissileHoming=0, race="nightelf", 
            Missilespeed=0, 
        },
        Bdcm={
            Targetattachcount=0, TargetArt="Abilities\\Spells\\Other\\Drain\\ManaDrainCaster.mdl", 
            EditorName="汲取魔法值 (施法者)", Spelldetail=0, isEffect=0, Missilearc=0.0, Targetattach="chest", 
            MissileHoming=0, race="human", Missilespeed=0, 
        },
        Bena={
            Buffubertip="该单位被诱捕了，因此其不能移动和飞行。", Bufftip="诱捕", race="orc", 
            Targetattach="chest,mount", EditorSuffix=" (空中的)", Targetattachcount=0, Spelldetail=0, isEffect=0, 
            Missilearc=0.0, Buffart="ReplaceableTextures\\CommandButtons\\BTNEnsnare.blp", MissileHoming=0, 
            TargetArt="Abilities\\Spells\\Orc\\Ensnare\\ensnare_AirTarget.mdl", Missilespeed=0, 
        },
        Btsp={
            Buffubertip="该单位受到了龙卷风的袭击;因此被投掷到了空中。", 
            EffectArt="Abilities\\Spells\\Other\\Tornado\\TornadoElementalSmall.mdl", race="other", 
            Effectattach="sprite,first", Targetattachcount=0, Spelldetail=0, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNTornado.blp", MissileHoming=0, Missilespeed=0, 
            Bufftip="龙卷旋风", 
        },
        Xclf={
            EffectArt="Abilities\\Spells\\Human\\CloudOfFog\\CloudOfFog.mdl", race="human", 
            EditorName="乌云 (效果)", Spelldetail=0, isEffect=1, Missilearc=0.0, Effectsoundlooped="CloudOfFogLoop", 
            Missilespeed=0, Targetattachcount=0, MissileHoming=0, 
        },
        Xbof={
            EffectArt="Abilities\\Spells\\Human\\FlameStrike\\FlameStrikeEmbers.mdl", race="orc", 
            EditorName="燃烧之油(效果)", Spelldetail=0, isEffect=1, Missilearc=0.0, 
            Effectsoundlooped="HumanFireLarge", Missilespeed=0, Targetattachcount=0, MissileHoming=0, 
        },
        BEst={
            Buffubertip="召唤出来的单位会受到驱逐魔法的伤害。", Bufftip="侦察", Spelldetail=0, 
            isEffect=0, Missilearc=0.0, race="nightelf", Missilespeed=0, Targetattachcount=0, MissileHoming=0, 
        },
        BOac={
            Buffubertip="该单位处于命令光环的作用之下，因此其攻击力得到了增强。", 
            Bufftip="命令光环", race="orc", 
            TargetArt="Abilities\\Spells\\Other\\GeneralAuraTarget\\GeneralAuraTarget.mdl", Targetattachcount=0, 
            Spelldetail=1, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNGnollCommandAura.blp", Missilespeed=0, 
            Targetattach="origin", MissileHoming=0, 
        },
        XUdd={
            EffectArt="Abilities\\Spells\\Undead\\DeathandDecay\\DeathandDecayTarget.mdl", race="undead", 
            EditorName="死亡凋零(效果)", Spelldetail=0, isEffect=1, Missilearc=0.0, 
            Effectsoundlooped="DeathAndDecayLoop", Missilespeed=0, Targetattachcount=0, MissileHoming=0, 
        },
        BHav={
            Buffubertip="该单位处于天神下凡的状态之中，因此其生命值、攻击力、护甲都得到了加强。而且还会魔法免疫。", 
            Bufftip="天神下凡", race="human", Spelldetail=0, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNAvatar.blp", Missilespeed=0, Targetattachcount=0, 
            MissileHoming=0, 
        },
        XOre={
            EditorName="重生(效果)", Spelldetail=0, isEffect=1, Missilearc=0.0, race="orc", Missilespeed=0, 
            Targetattachcount=0, MissileHoming=0, 
        },
        BEia={
            EditorName="献祭(施法者)", Spelldetail=0, isEffect=0, Missilearc=0.0, race="nightelf", Missilespeed=0, 
            Targetattachcount=0, MissileHoming=0, 
        },
        Bam2={
            Buffubertip="这个单位具有反魔法外壳，攻击魔法对于该单位的伤害效果将减少。", 
            Bufftip="反魔法外壳", race="undead", Targetattach="overhead", EditorSuffix=" (额外的)", 
            Targetattachcount=0, Spelldetail=0, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNAntiMagicShell.blp", MissileHoming=0, 
            TargetArt="Abilities\\Spells\\Undead\\AntiMagicShell\\AntiMagicShell.mdl", Missilespeed=0, 
        },
        BNsw={
            Buffubertip="A proud hawk.", EffectArt="Abilities\\Spells\\Orc\\FeralSpirit\\feralspiritdone.mdl", 
            race="other", Targetattachcount=0, Spelldetail=0, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNWarEagle.blp", MissileHoming=0, Missilespeed=0, 
            Bufftip="战鹰", 
        },
        BEme={
            Buffubertip="让恶魔猎手变身为一个威力巨大的恶魔，该恶魔具有远程攻击能力。", 
            Bufftip="变身", race="nightelf", Spelldetail=0, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNMetamorphosis.blp", Missilespeed=0, 
            Targetattachcount=0, MissileHoming=0, 
        },
        Bspe={
            Buffubertip="该单位速度被加快了，所以移动起来要比其他一般的单位要快。", 
            Bufftip="速度加快", TargetArt="Abilities\\Spells\\Items\\AIsp\\SpeedTarget.mdl", race="other", 
            Spelldetail=0, isEffect=0, Missilearc=0.0, Buffart="ReplaceableTextures\\CommandButtons\\BTNBoots.blp", 
            Missilespeed=0, Targetattachcount=0, MissileHoming=0, 
        },
        BNcs={
            Buffubertip="火箭群", Bufftip="火箭群", race="other", 
            TargetArt="Abilities\\Spells\\Human\\Thunderclap\\ThunderclapTarget.mdl", Targetattachcount=0, 
            Spelldetail=0, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNClusterRockets.blp", Missilespeed=0, 
            Targetattach="overhead", MissileHoming=0, 
        },
        Xbli={
            EditorName="荒芜之地(效果)", Spelldetail=0, isEffect=1, Missilearc=0.0, race="other", Missilespeed=0, 
            Targetattachcount=0, MissileHoming=0, 
        },
        XNmo={
            EffectArt="Abilities\\Spells\\Other\\Monsoon\\MonsoonRain.mdl", race="other", 
            EditorName="季风(效果)", Spelldetail=0, isEffect=1, Missilearc=0.0, Effectsoundlooped="MonsoonLoop", 
            Missilespeed=0, Targetattachcount=0, MissileHoming=0, 
        },
        XNhs={
            Targetattachcount=0, EditorName="Healing Spray (Effect)", Spelldetail=0, isEffect=1, Missilearc=0.0, 
            race="other", MissileHoming=0, Missilespeed=0, 
            SpecialArt="Abilities\\Spells\\Human\\Heal\\HealTarget.mdl", 
        },
        Bbsk={
            Buffubertip="该单位处于狂热愤怒的作用之下，因此攻击力得到了加强，但是同时也会受到更多的伤害。", 
            Bufftip="狂战士", race="orc", Targetattach1="weapon,right", 
            TargetArt="Abilities\\Spells\\Orc\\TrollBerserk\\HeadhunterWEAPONSLeft.mdl,Abilities\\Spells\\Orc\\TrollBerserk\\HeadhunterWEAPONSRight.mdl", 
            Targetattachcount=2, Spelldetail=0, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNBerserkForTrolls.blp", Missilespeed=0, 
            Targetattach="weapon,left", MissileHoming=0, 
        },
        BNto={
            Bufftip="龙卷风", EditorSuffix=" (有时间限制)", race="other", Spelldetail=0, isEffect=0, 
            Missilearc=0.0, Effectsoundlooped="TornadoLoop", MissileHoming=0, Targetattachcount=0, Missilespeed=0, 
        },
        BEsh={
            Buffubertip="This unit was hit by Shadow Strike; it will take damage over time and move more slowly.", 
            Bufftip="暗影突袭", race="nightelf", 
            TargetArt="Abilities\\Spells\\NightElf\\shadowstrike\\shadowstrike.mdl", Targetattachcount=0, 
            Spelldetail=0, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNShadowStrike.blp", Missilespeed=0, 
            Targetattach="overhead", MissileHoming=0, 
        },
        Bdvv={
            Buffubertip="该单位被吞噬了，因此会持续地受到伤害。", Bufftip="吞噬", race="orc", 
            Spelldetail=0, isEffect=0, Missilearc=0.0, Buffart="ReplaceableTextures\\CommandButtons\\BTNDevour.blp", 
            Missilespeed=0, Targetattachcount=0, MissileHoming=0, 
        },
        BNsq={
            Buffubertip="一只愤怒的豪猪。", 
            EffectArt="Abilities\\Spells\\Orc\\FeralSpirit\\feralspiritdone.mdl", race="other", Targetattachcount=0, 
            Spelldetail=0, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNQuillBeast.blp", MissileHoming=0, Missilespeed=0, 
            Bufftip="豪猪", 
        },
        Blsa={
            EditorName="闪电护盾(施法者)", Spelldetail=0, isEffect=0, Missilearc=0.0, race="orc", Missilespeed=0, 
            Targetattachcount=0, MissileHoming=0, 
        },
        Bplg={
            EditorName="疾病云雾", Spelldetail=0, isEffect=0, Missilearc=0.0, race="undead", Missilespeed=0, 
            Targetattachcount=0, MissileHoming=0, 
        },
        Bweb={
            Buffubertip="该单位遭到了蛛网的攻击，因此被固定在了地面上而不能移动。", 
            Bufftip="蛛网", race="undead", Targetattach="origin", EditorSuffix=" (地面的)", Targetattachcount=0, 
            Spelldetail=0, isEffect=0, Missilearc=0.0, Buffart="ReplaceableTextures\\CommandButtons\\BTNWeb.blp", 
            MissileHoming=0, TargetArt="Abilities\\Spells\\Undead\\Web\\WebTarget.mdl", Missilespeed=0, 
        },
        BIrm={
            Buffubertip="该单位使用了净化药水，因此其魔法值会持续地恢复。", 
            Bufftip="净化药水", race="other", TargetArt="Abilities\\Spells\\Other\\ANrl\\ANrlTarget.mdl", 
            Targetattachcount=0, Spelldetail=0, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNPotionOfClarity.blp", Missilespeed=0, 
            Targetattach="origin", MissileHoming=0, 
        },
        Bfzy={
            Buffubertip="该单位处于狂热中，其攻击速率和移动速度都增加了。", 
            Bufftip="狂热", race="other", Targetattach1="hand,right", 
            TargetArt="Abilities\\Spells\\Orc\\Bloodlust\\BloodlustTarget.mdl,Abilities\\Spells\\Orc\\Bloodlust\\BloodlustSpecial.mdl", 
            Targetattachcount=2, Spelldetail=1, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNBloodLust.blp", Missilespeed=0, 
            Targetattach="hand,left", MissileHoming=0, 
        },
        BHfs={
            Buffubertip="该单位处于烈焰风暴的攻击之中，因此会在一定时间内持续受到伤害。", 
            Bufftip="烈焰风暴", 
            TargetArt="Abilities\\Spells\\Human\\FlameStrike\\FlameStrikeDamageTarget.mdl", race="human", 
            Spelldetail=0, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNWallOfFire.blp", Missilespeed=0, Targetattachcount=0, 
            MissileHoming=0, 
        },
        Bfro={
            Buffubertip="该单位速度被减慢了，所以移动起来要比其他一般的单位要慢。", 
            Bufftip="被减速的", TargetArt="Abilities\\Spells\\Other\\FrostDamage\\FrostDamage.mdl", 
            race="other", Spelldetail=0, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNFrost.blp", Missilespeed=0, Targetattachcount=0, 
            MissileHoming=0, 
        },
        Basl={
            Buffubertip="该单位受到了龙卷风的袭击，它的移动速度被暂时降低了。", 
            Bufftip="龙卷风", race="other", EditorSuffix=" (减速光环)", Targetattachcount=0, Spelldetail=0, 
            isEffect=0, Missilearc=0.0, Buffart="ReplaceableTextures\\CommandButtons\\BTNTornado.blp", 
            MissileHoming=0, TargetArt="Abilities\\Spells\\Other\\Tornado\\Tornado_Target.mdl", Missilespeed=0, 
        },
        XIct={
            EditorName="能更改时间的物品", Spelldetail=0, isEffect=1, Missilearc=0.0, race="other", 
            Missilespeed=0, Targetattachcount=0, MissileHoming=0, 
        },
        Binv={
            Buffubertip="该单位处于隐形的状态之中; 敌人不能看到其存在。如果它攻击或者施放魔法，那么就会暴露出自己的踪迹。", 
            Bufftip="隐形术", race="human", Spelldetail=0, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNInvisibility.blp", Missilespeed=0, Targetattachcount=0, 
            MissileHoming=0, 
        },
        Xfhm={
            Targetattach1="sprite,second", Targetattachcount=4, race="human", Targetattach2="sprite,fourth", 
            Targetattach3="sprite,fifth", 
            TargetArt="Environment\\LargeBuildingFire\\LargeBuildingFire2.mdl,Environment\\SmallBuildingFire\\SmallBuildingFire1.mdl,Environment\\LargeBuildingFire\\LargeBuildingFire0.mdl,Environment\\SmallBuildingFire\\SmallBuildingFire2.mdl", 
            EditorName="建筑物伤害 – 人族  中", Spelldetail=0, isEffect=1, Missilearc=0.0, 
            Effectsoundlooped="HumanFireMedium", Missilespeed=0, Targetattach="sprite,first", MissileHoming=0, 
        },
        XErf={
            EffectArt="Abilities\\Spells\\Demon\\RainOfFire\\RainOfFireTarget.mdl", race="other", 
            Targetattachcount=0, EditorName="火焰雨(效果)", Spelldetail=0, isEffect=1, Missilearc=0.0, 
            Effectsoundlooped="RainOfFireLoop", MissileHoming=0, Missilespeed=0, Effectsound="RainOfFireWave", 
        },
        BUcb={
            Buffubertip="召唤出来的单位会受到驱逐魔法的伤害。", Bufftip="腐尸甲虫", 
            race="undead", Spelldetail=0, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNCarrionScarabs.blp", Missilespeed=0, 
            Targetattachcount=0, MissileHoming=0, 
        },
        XErc={
            EditorName="混乱之雨(效果)", Spelldetail=0, isEffect=1, Missilearc=0.0, race="other", Missilespeed=0, 
            Targetattachcount=0, MissileHoming=0, 
        },
        BNms={
            Buffubertip="这个单位身上有着魔法护盾，所以他暂时对物理攻击和负面魔法有着一定的抵抗能力。", 
            Bufftip="魔法护盾", TargetArt="Abilities\\Spells\\Human\\ManaShield\\ManaShieldCaster.mdl", 
            race="other", Spelldetail=0, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNNeutralManaShield.blp", Missilespeed=0, 
            Targetattachcount=0, MissileHoming=0, 
        },
        XHfs={
            EffectArt="Abilities\\Spells\\Human\\FlameStrike\\FlameStrikeEmbers.mdl", race="human", 
            EditorName="烈焰风暴(效果)", Spelldetail=0, isEffect=1, Missilearc=0.0, 
            Effectsoundlooped="HumanFireLarge", Missilespeed=0, Targetattachcount=0, MissileHoming=0, 
        },
        Bwea={
            Buffubertip="该单位遭到了蛛网的攻击，因此被固定在了地面上而不能移动。", 
            Bufftip="蛛网", race="undead", Targetattach="chest,mount", EditorSuffix=" (空中的)", 
            Targetattachcount=0, Spelldetail=0, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNWeb.blp", MissileHoming=0, 
            TargetArt="Abilities\\Spells\\Undead\\Web\\Web_AirTarget.mdl", Missilespeed=0, 
        },
        BNdi={
            Buffubertip="这个单位受到魔鬼缠身的折磨；它将会持续受到伤害直到死亡，一个魔鬼将会从他的尸体上诞生。魔鬼缠身不能被驱散或取消。", 
            EffectArt="Abilities\\Spells\\Other\\Doom\\DoomDeath.mdl", race="other", EditorSuffix=" (奴)", 
            Targetattachcount=0, Spelldetail=0, isEffect=0, Missilearc=0.0, 
            TargetArt="Abilities\\Spells\\Other\\Doom\\DoomDeath.mdl", MissileHoming=0, Missilespeed=0, 
            Bufftip="魔鬼缠身", 
        },
        BEsv={
            Buffubertip="复仇之魂暴怒中。", 
            EffectArt="Abilities\\Spells\\Orc\\FeralSpirit\\feralspiritdone.mdl", race="nightelf", 
            Targetattachcount=0, Spelldetail=0, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNSpiritOfVengeance.blp", MissileHoming=0, 
            Missilespeed=0, Bufftip="复仇之魂", 
        },
        Bvul={
            Buffubertip="该单位是无敌的，所以任何的攻击和魔法都对其无效。", 
            Bufftip="无敌的", race="other", 
            TargetArt="Abilities\\Spells\\Human\\DivineShield\\DivineShieldTarget.mdl", Targetattachcount=0, 
            Spelldetail=0, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNInvulnerable.blp", Missilespeed=0, 
            Targetattach="origin", MissileHoming=0, 
        },
        Bvng={
            Buffubertip="复仇之魂在此。", 
            EffectArt="Abilities\\Spells\\Orc\\FeralSpirit\\feralspiritdone.mdl", race="nightelf", 
            Targetattachcount=0, Spelldetail=0, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNAvengingWatcher.blp", MissileHoming=0, Missilespeed=0, 
            Bufftip="复仇之魂", 
        },
        Bdtl={
            Targetattachcount=0, TargetArt="Abilities\\Spells\\Other\\Drain\\DrainTarget.mdl", 
            EditorName="汲取生命值(目标)", Spelldetail=0, isEffect=0, Missilearc=0.0, Targetattach="chest", 
            MissileHoming=0, race="human", Missilespeed=0, 
        },
        Xfhs={
            Targetattach1="sprite,fourth", Targetattachcount=2, race="human", 
            TargetArt="Environment\\SmallBuildingFire\\SmallBuildingFire2.mdl,Environment\\SmallBuildingFire\\SmallBuildingFire1.mdl", 
            EditorName="建筑物伤害 – 人族  小", Spelldetail=0, isEffect=1, Missilearc=0.0, 
            Effectsoundlooped="HumanFireSmall", Missilespeed=0, Targetattach="sprite,first", MissileHoming=0, 
        },
        Buhf={
            Buffubertip="该单位受到了邪恶狂热的作用，因此攻击速度加快了，但是也会持续地受到伤害。", 
            Bufftip="邪恶狂热", race="undead", 
            TargetArt="Abilities\\Spells\\Undead\\UnholyFrenzy\\UnholyFrenzyTarget.mdl", Targetattachcount=0, 
            Spelldetail=0, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNUnholyFrenzy.blp", Missilespeed=0, 
            Targetattach="overhead", MissileHoming=0, 
        },
        ANmd={
            Targetattachcount=0, TargetArt="Abilities\\Spells\\Other\\Monsoon\\MonsoonBoltTarget.mdl", 
            EditorName="季风", Spelldetail=0, isEffect=0, Missilearc=0.0, Targetattach="origin", MissileHoming=0, 
            race="other", Missilespeed=0, 
        },
        BNef={
            Buffubertip="我是一个熊猫人元素 ，崇拜我吧。", 
            EffectArt="Abilities\\Spells\\Orc\\MirrorImage\\MirrorImageDeathCaster.mdl", race="other", 
            SpecialArt="Abilities\\Spells\\Orc\\MirrorImage\\MirrorImageDeathCaster.mdl", Targetattachcount=0, 
            Spelldetail=0, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNStormEarth&Fire.blp", MissileHoming=0, Missilespeed=0, 
            Bufftip="熊猫人元素", 
        },
        BIrl={
            Buffubertip="该单位身上带有再生物品，因此其生命值将会持续地恢复。", 
            Bufftip="再生物品", race="other", TargetArt="Abilities\\Spells\\Other\\ANrm\\ANrmTarget.mdl", 
            Targetattachcount=0, Spelldetail=0, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNHealingSalve.blp", Missilespeed=0, 
            Targetattach="origin", MissileHoming=0, 
        },
        BOvc={
            Targetattachcount=0, TargetArt="Abilities\\Spells\\Orc\\Voodoo\\VoodooAura.mdl", 
            EditorName="巫毒(施法者)", Spelldetail=0, isEffect=0, Missilearc=0.0, MissileHoming=0, race="orc", 
            Missilespeed=0, 
        },
        BNss={
            Buffubertip="一种可以阻挡法师的防护之盾。", Bufftip="魔法护盾", race="other", 
            TargetArt="Abilities\\Spells\\Items\\SpellShieldAmulet\\SpellShieldCaster.mdl", Targetattachcount=0, 
            Spelldetail=0, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNSpellShieldAmulet.blp", Missilespeed=0, 
            Targetattach="origin", MissileHoming=0, 
        },
        Btdg={
            EditorName="龙卷风伤害", Spelldetail=0, isEffect=0, Missilearc=0.0, race="other", Missilespeed=0, 
            Targetattachcount=0, MissileHoming=0, 
        },
        Btlf={
            Buffubertip="召唤出来的单位会受到驱逐魔法的伤害。", Bufftip="定时的生命", 
            race="other", Spelldetail=0, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNAcorn.blp", Missilespeed=0, Targetattachcount=0, 
            MissileHoming=0, 
        },
        Btsa={
            EditorName="龙卷风旋转 (区域魔法)", Spelldetail=0, isEffect=0, Missilearc=0.0, race="other", 
            Missilespeed=0, Targetattachcount=0, MissileHoming=0, 
        },
        Bpsi={
            EditorName="毒药(信息)", Spelldetail=0, isEffect=0, Missilearc=0.0, race="other", Missilespeed=0, 
            Targetattachcount=0, MissileHoming=0, 
        },
        Bsta={
            Buffubertip="该单位被静止陷阱击中了，因此不能移动，进攻和施放魔法。", 
            Bufftip="静止陷阱", race="orc", 
            TargetArt="Abilities\\Spells\\Human\\Thunderclap\\ThunderclapTarget.mdl", Targetattachcount=0, 
            Spelldetail=0, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNStasisTrap.blp", Missilespeed=0, 
            Targetattach="overhead", MissileHoming=0, 
        },
        Xbdt={
            Targetattachcount=0, EditorName="显示 (效果)", Spelldetail=0, isEffect=1, Missilearc=0.0, race="other", 
            Missilespeed=0, EffectArt="Abilities\\Spells\\Other\\Andt\\Andt.mdl", MissileHoming=0, 
        },
        BNdo={
            Buffubertip="这个单位受到魔鬼缠身的折磨；它不能施放任何魔法也将会持续受到伤害直到死亡，一个魔鬼将会从他的尸体上诞生。魔鬼缠身不能被驱散或取消。", 
            Bufftip="魔鬼缠身", TargetArt="Abilities\\Spells\\Other\\Doom\\DoomTarget.mdl", race="other", 
            Spelldetail=0, isEffect=0, Missilearc=0.0, Buffart="ReplaceableTextures\\CommandButtons\\BTNDoom.blp", 
            Missilespeed=0, Targetattachcount=0, MissileHoming=0, 
        },
        Bssd={
            Buffubertip="该单位受到了慢性毒药的攻击;因此其移动速度和攻击速度都减慢了，而且会在一定时间内持续地受到伤害。", 
            Bufftip="慢性毒药", race="nightelf", EditorSuffix=" (堆积)", Targetattachcount=0, Spelldetail=2, 
            isEffect=0, Missilearc=0.0, Buffart="ReplaceableTextures\\PassiveButtons\\PASBTNSlowPoison.blp", 
            MissileHoming=0, TargetArt="Abilities\\Weapons\\PoisonSting\\PoisonStingTarget.mdl", Missilespeed=0, 
        },
        BEar={
            Buffubertip="该单位处在强击光环的作用之下，因此其远程攻击力得到了加强。", 
            Bufftip="强击光环", race="nightelf", 
            TargetArt="Abilities\\Spells\\Other\\GeneralAuraTarget\\GeneralAuraTarget.mdl", Targetattachcount=0, 
            Spelldetail=2, isEffect=0, Missilearc=0.0, Buffart="ReplaceableTextures\\CommandButtons\\BTNTrueShot.blp", 
            Missilespeed=0, Targetattach="origin", MissileHoming=0, 
        },
        Bliq={
            Targetattachcount=0, race="orc", TargetArt="Abilities\\Spells\\Orc\\LiquidFire\\Liquidfire.mdl", 
            EditorName="液体炸弹", Spelldetail=0, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\PassiveButtons\\PASBTNLiquidFire.blp", Missilespeed=0, 
            Effectsoundlooped="LiquidFireLoop", MissileHoming=0, 
        },
        BNsg={
            Buffubertip="一只残忍的熊。", 
            EffectArt="Abilities\\Spells\\Orc\\FeralSpirit\\feralspiritdone.mdl", race="other", Targetattachcount=0, 
            Spelldetail=0, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNGrizzlyBear.blp", MissileHoming=0, Missilespeed=0, 
            Bufftip="熊", 
        },
        BHbd={
            Buffubertip="该单位正受到暴风雪的攻击伤害。", Bufftip="暴风雪", 
            TargetArt="Abilities\\Spells\\Other\\FrostDamage\\FrostDamage.mdl", race="human", Spelldetail=0, 
            isEffect=0, Missilearc=0.0, Buffart="ReplaceableTextures\\CommandButtons\\BTNBlizzard.blp", 
            Missilespeed=0, Targetattachcount=0, MissileHoming=0, 
        },
        Barm={
            Buffubertip="该单位处于魔法恢复光环的作用之下，因此其魔法恢复速度得到了加快。", 
            Bufftip="魔法恢复光环", TargetArt="Abilities\\Spells\\Other\\ANrl\\ANrlTarget.mdl", race="orc", 
            Spelldetail=1, isEffect=0, Missilearc=0.0, Effectsoundlooped="FountainOfLifeLoop", Missilespeed=0, 
            Targetattachcount=0, MissileHoming=0, 
        },
        XOeq={
            EffectArt="Abilities\\Spells\\Orc\\EarthQuake\\EarthQuakeTarget.mdl", race="orc", 
            EditorName="地震 (效果)", Spelldetail=0, isEffect=1, Missilearc=0.0, Effectsoundlooped="EarthquakeLoop", 
            Missilespeed=0, Targetattachcount=0, MissileHoming=0, 
        },
        Bspa={
            Bufftip="小蜘蛛", race="undead", 
            TargetArt="Abilities\\Weapons\\CryptFiendMissile\\CryptFiendMissileTarget.mdl", Targetattachcount=0, 
            Spelldetail=0, isEffect=0, Missilearc=0.0, Buffart="ReplaceableTextures\\CommandButtons\\BTNSpider.blp", 
            Missilespeed=0, Targetattach="origin", MissileHoming=0, 
        },
        Bfrz={
            Buffubertip="该单位被冻住了，因此失去了原有的功效并不能被修理。", 
            Bufftip="冰冻喷吐", race="undead", 
            TargetArt="Abilities\\Spells\\Undead\\FreezingBreath\\FreezingBreathTargetArt.mdl", 
            Targetattachcount=0, Spelldetail=0, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNFreezingBreath.blp", Missilespeed=0, 
            Targetattach="origin", MissileHoming=0, 
        },
        Bprg={
            Buffubertip="该单位受到了净化的作用; 因此其移动速度被减慢了，而且身上所有的魔法效果都消失了。", 
            Bufftip="净化", race="orc", TargetArt="Abilities\\Spells\\Orc\\Purge\\PurgeBuffTarget.mdl", 
            Targetattachcount=0, Spelldetail=0, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNPurge.blp", Missilespeed=0, Targetattach="origin", 
            MissileHoming=0, 
        },
        Bmil={
            Buffubertip="该农民变成了民兵，所有其移动速度，攻击速度，攻击力，护甲都得到了加强。", 
            Bufftip="民兵", race="human", Spelldetail=0, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNCallToArms.blp", Missilespeed=0, Targetattachcount=0, 
            MissileHoming=0, 
        },
        BHad={
            Buffubertip="该单位处于专注光环的作用之下，因此提高了护甲。", 
            Bufftip="专注光环", race="human", 
            TargetArt="Abilities\\Spells\\Other\\GeneralAuraTarget\\GeneralAuraTarget.mdl", Targetattachcount=0, 
            Spelldetail=2, isEffect=0, Missilearc=0.0, Buffart="ReplaceableTextures\\CommandButtons\\BTNDevotion.blp", 
            Missilespeed=0, Targetattach="origin", MissileHoming=0, 
        },
        Bcmg={
            Buffubertip="这个单位可以被控制。它现在遵从一个新主人了。", 
            EffectArt="Abilities\\Spells\\Orc\\FeralSpirit\\feralspiritdone.mdl", race="human", Targetattachcount=0, 
            Spelldetail=0, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNControlMagic.blp", MissileHoming=0, Missilespeed=0, 
            Bufftip="控制魔法", 
        },
        Bslo={
            Buffubertip="该单位被减速了，其移动速度和攻击速度都会下降。", Bufftip="减速", 
            TargetArt="Abilities\\Spells\\Human\\slow\\slowtarget.mdl", race="human", Spelldetail=1, isEffect=0, 
            Missilearc=0.0, Buffart="ReplaceableTextures\\CommandButtons\\BTNSlow.blp", Missilespeed=0, 
            Targetattachcount=0, MissileHoming=0, 
        },
        Bshs={
            Buffubertip="该单位受到了影子权杖的作用; 因此其将暴露在敌人的视野之下。", 
            Bufftip="影子权杖", race="other", Spelldetail=0, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNWandOfShadowSight.blp", Missilespeed=0, 
            Targetattachcount=0, MissileHoming=0, 
        },
        Bdbl={
            Buffubertip="这个单位具有额外的生命值。但是这个额外的值会消失得很快。", 
            Bufftip="吸取生命", race="human", Spelldetail=0, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNLifeDrain.blp", Missilespeed=0, Targetattachcount=0, 
            MissileHoming=0, 
        },
        Bply={
            Buffubertip="该单位被施放了变形术，因此被变成了一头温顺的小绵羊。", 
            EffectArt="Abilities\\Spells\\Human\\Polymorph\\PolyMorphDoneGround.mdl", race="human", 
            Targetattachcount=0, Spelldetail=0, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNPolymorph.blp", MissileHoming=0, Missilespeed=0, 
            Bufftip="变形术", 
        },
        BOsh={
            EditorName="震荡波(施法者)", Spelldetail=0, isEffect=0, Missilearc=0.0, race="orc", Missilespeed=0, 
            Targetattachcount=0, MissileHoming=0, 
        },
        Bsha={
            EditorName="共享视野", Spelldetail=0, isEffect=0, Missilearc=0.0, race="other", Missilespeed=0, 
            Targetattachcount=0, MissileHoming=0, 
        },
        Boar={
            Buffubertip="加快生命值恢复速度。", Bufftip="治疗守卫光环", race="orc", 
            TargetArt="Abilities\\Spells\\Other\\ANrm\\ANrmTarget.mdl", Targetattachcount=0, Spelldetail=2, 
            isEffect=0, Missilearc=0.0, Buffart="ReplaceableTextures\\CommandButtons\\BTNHealingWard.blp", 
            MissileHoming=0, Missilespeed=0, Effectsoundlooped="FountainOfLifeLoop", 
        },
        BIpb={
            Targetattachcount=0, TargetArt="Abilities\\Weapons\\PoisonSting\\PoisonStingTarget.mdl", Spelldetail=2, 
            isEffect=0, Missilearc=0.0, Buffart="ReplaceableTextures\\CommandButtons\\BTNOrbOfVenom.blp", 
            MissileHoming=0, race="other", Missilespeed=0, 
        },
        BPSE={
            Buffubertip="该单位不能移动。", Bufftip="被击晕的", race="other", Targetattach="overhead", 
            EditorSuffix=" (暂停)", Targetattachcount=0, Spelldetail=0, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNStun.blp", MissileHoming=0, 
            TargetArt="Abilities\\Spells\\Human\\Thunderclap\\ThunderclapTarget.mdl", Missilespeed=0, 
        },
        Brpl={
            Buffubertip="此单位已被枯萎精髓击中；它的生命值已完全恢复。", 
            Bufftip="枯萎精髓", race="undead", Spelldetail=0, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNReplenishHealth.blp", Missilespeed=0, 
            Targetattachcount=0, MissileHoming=0, 
        },
        Broa={
            Buffubertip="该单位具有咆哮技能，因此其攻击力得到了加强。", Bufftip="咆哮", 
            race="nightelf", TargetArt="Abilities\\Spells\\NightElf\\BattleRoar\\RoarTarget.mdl", 
            Targetattachcount=0, Spelldetail=1, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNBattleRoar.blp", Missilespeed=0, 
            Targetattach="overhead", MissileHoming=0, 
        },
        Brej={
            Buffubertip="该单位具有生命恢复技能，因此其能持续地恢复自己的生命值。", 
            Bufftip="生命恢复", race="nightelf", 
            TargetArt="Abilities\\Spells\\NightElf\\Rejuvenation\\RejuvenationTarget.mdl", Targetattachcount=0, 
            Spelldetail=0, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNRejuvenation.blp", Missilespeed=0, 
            Targetattach="chest", MissileHoming=0, 
        },
        Bpxf={
            Buffubertip="该单位正受到凤凰火焰的灼伤，不断受到伤害。", Bufftip="凤凰火焰", 
            TargetArt="Abilities\\Spells\\Other\\BreathOfFire\\BreathOfFireDamage.mdl", race="human", Spelldetail=0, 
            isEffect=0, Missilearc=0.0, Buffart="ReplaceableTextures\\CommandButtons\\BTNMarkOfFire.blp", 
            Missilespeed=0, Targetattachcount=0, MissileHoming=0, 
        },
        Bpsh={
            Buffubertip="该单位处于消失的状态中，因此在短时间内不会受到任何的伤害。", 
            Bufftip="变相移动", race="nightelf", Targetattachcount=0, Spelldetail=0, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNPhaseShift.blp", Missilespeed=0, 
            SpecialArt="Abilities\\Spells\\NightElf\\FaerieDragonInvis\\FaerieDragon_Invis.mdl", MissileHoming=0, 
        },
        Bpsd={
            Buffubertip="该单位被毒刺攻击了, 因此会持续受到伤害。", Bufftip="毒", race="other", 
            EditorSuffix=" (堆积)", Targetattachcount=0, Spelldetail=2, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNEnvenomedSpear.blp", MissileHoming=0, 
            TargetArt="Abilities\\Weapons\\PoisonSting\\PoisonStingTarget.mdl", Missilespeed=0, 
        },
        Bpig={
            Specialattach="chest", race="other", 
            TargetArt="Abilities\\Spells\\Other\\ImmolationRed\\ImmolationRedTarget.mdl", Targetattachcount=0, 
            EditorSuffix=" (中立的单位但是是敌对的 2)", EditorName="永久的献祭", Spelldetail=0, 
            isEffect=0, Missilearc=0.0, Targetattach="chest", Missilespeed=0, 
            SpecialArt="Abilities\\Spells\\Other\\ImmolationRed\\ImmolationRedDamage.mdl", MissileHoming=0, 
        },
        AEtr={
            Targetattachcount=0, TargetArt="Abilities\\Spells\\NightElf\\Tranquility\\TranquilityTarget.mdl", 
            EditorName="宁静(目标)", Spelldetail=0, isEffect=0, Missilearc=0.0, MissileHoming=0, race="nightelf", 
            Missilespeed=0, 
        },
        Bpoi={
            Buffubertip="该单位被毒刺攻击了, 因此会持续受到伤害。", Bufftip="毒", race="other", 
            EditorSuffix=" (没有堆积)", Targetattachcount=0, Spelldetail=2, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNEnvenomedSpear.blp", MissileHoming=0, 
            TargetArt="Abilities\\Weapons\\PoisonSting\\PoisonStingTarget.mdl", Missilespeed=0, 
        },
        XEtq={
            EffectArt="Abilities\\Spells\\NightElf\\Tranquility\\Tranquility.mdl", race="nightelf", 
            EditorName="宁静(效果)", Spelldetail=0, isEffect=1, Missilearc=0.0, Effectsoundlooped="TranquilityLoop", 
            Missilespeed=0, Targetattachcount=0, MissileHoming=0, 
        },
        BNsa={
            Buffubertip="该单位处于避难权杖的效果之下，因此其生命值将持续地恢复，但是不能移动，攻击和施放任何魔法。", 
            Bufftip="避难权杖", 
            TargetArt="Abilities\\Spells\\Items\\StaffOfSanctuary\\Staff_Sanctuary_Target.mdl", race="other", 
            Spelldetail=0, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNStaffOfSanctuary.blp", Missilespeed=0, 
            Targetattachcount=0, MissileHoming=0, 
        },
        BNrd={
            Buffubertip="该单位受到火焰雨的攻击，它将不断受到伤害。", Bufftip="火焰雨", 
            TargetArt="Abilities\\Spells\\Human\\FlameStrike\\FlameStrikeDamageTarget.mdl", race="other", 
            Spelldetail=0, isEffect=0, Missilearc=0.0, Buffart="ReplaceableTextures\\CommandButtons\\BTNFire.blp", 
            Missilespeed=0, Targetattachcount=0, MissileHoming=0, 
        },
        Brpm={
            Buffubertip="这个单位被灵魂触摸击中；它的一些能量被恢复了。", 
            Bufftip="灵魂触摸", race="undead", Spelldetail=0, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNReplenishMana.blp", Missilespeed=0, 
            Targetattachcount=0, MissileHoming=0, 
        },
        BNcr={
            Buffubertip="这个单位受到了化学风暴的作用。他的移动速度和攻击速度都得到了提高。", 
            Bufftip="化学风暴", race="other", Spelldetail=0, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNChemicalRage.blp", Missilespeed=0, Targetattachcount=0, 
            MissileHoming=0, 
        },
        BUst={
            Targetattachcount=0, TargetArt="Abilities\\Spells\\Undead\\Sleep\\SleepSpecialArt.mdl", 
            EditorName="睡眠(震晕)", Spelldetail=0, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNSleep.blp", Missilespeed=0, race="undead", 
            MissileHoming=0, 
        },
        Babr={
            Buffubertip="该单位处在荒芜光环的作用之下，因此其生命值恢复速度加快了。", 
            Bufftip="荒芜光环", race="undead", 
            TargetArt="Abilities\\Spells\\Other\\GeneralAuraTarget\\GeneralAuraTarget.mdl", Targetattachcount=0, 
            Spelldetail=2, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNRegenerationAura.blp", Missilespeed=0, 
            Targetattach="origin", MissileHoming=0, 
        },
        Bcy2={
            Buffubertip="该单位处在飓风的作用之下，因此其不能移动，攻击和施放魔法。", 
            EffectArt="Abilities\\Spells\\NightElf\\Cyclone\\CycloneTarget.mdl", race="nightelf", 
            Effectattach="sprite,first", Targetattachcount=0, EditorSuffix=" (额外的)", Missilespeed=0, 
            Spelldetail=0, isEffect=0, Missilearc=0.0, Buffart="ReplaceableTextures\\CommandButtons\\BTNCyclone.blp", 
            MissileHoming=0, Effectsoundlooped="CycloneLoop", Bufftip="飓风", 
        },
        Bmfl={
            Buffubertip="该单位身上有魔力之焰的作用;周围任何敌方单位施放魔法都会受到伤害。", 
            Bufftip="魔力之焰", race="nightelf", Targetattach="overhead", LightningEffect="MFPB", 
            TargetArt="Abilities\\Spells\\Human\\ManaFlare\\ManaFlareBase.mdl", Targetattachcount=0, Spelldetail=0, 
            isEffect=0, Missilearc=0.0, Buffart="ReplaceableTextures\\CommandButtons\\BTNManaFlare.blp", 
            MissileHoming=0, Missilespeed=0, Effectsoundlooped="ManaFlareLoop", 
        },
        Bmfa={
            Buffubertip="该单位身上有魔力之焰的作用;周围任何敌方单位施放魔法都会受到伤害。", 
            race="nightelf", Bufftip="魔力之焰", 
            SpecialArt="Abilities\\Spells\\Human\\ManaFlare\\ManaFlareBoltImpact.mdl", Targetattachcount=0, 
            Targetattach="overhead", EditorSuffix=" (额外的)", 
            TargetArt="Abilities\\Spells\\Human\\ManaFlare\\ManaFlareTarget.mdl", Spelldetail=0, isEffect=0, 
            Missilearc=0.0, Buffart="ReplaceableTextures\\CommandButtons\\BTNManaFlare.blp", MissileHoming=1, 
            Missilespeed=1000, Missileart="Abilities\\Spells\\Human\\ManaFlare\\ManaFlareMissile.mdl", 
        },
        BNrf={
            EditorName="火焰雨(区域魔法)", Spelldetail=0, isEffect=0, Missilearc=0.0, race="other", Missilespeed=0, 
            Targetattachcount=0, MissileHoming=0, 
        },
        Bmec={
            Buffubertip="召唤出来的单位会受到驱逐魔法的伤害。", Bufftip="机械类的小玩艺", 
            Spelldetail=0, isEffect=0, Missilearc=0.0, race="other", Missilespeed=0, Targetattachcount=0, MissileHoming=0, 
        },
        Blsh={
            Buffubertip="该单位处在闪电护盾的作用之下，因此周围所有的单位都会受到一定的伤害。", 
            Bufftip="闪电护盾", race="orc", Targetattach="origin", 
            TargetArt="Abilities\\Spells\\Orc\\LightningShield\\LightningShieldTarget.mdl", Targetattachcount=0, 
            Spelldetail=0, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNLightningShield.blp", Missilespeed=0, 
            SpecialArt="Abilities\\Spells\\Orc\\LightningShield\\LightningShieldBuff.mdl", MissileHoming=0, 
        },
        BOea={
            EditorName="地震 (施法者)", Spelldetail=0, isEffect=0, Missilearc=0.0, race="orc", Missilespeed=0, 
            Targetattachcount=0, MissileHoming=0, 
        },
        XNcs={
            EditorName="Cluster Rockets (Effect)", Spelldetail=0, isEffect=1, Missilearc=0.0, race="other", 
            Missilespeed=0, Targetattachcount=0, MissileHoming=0, 
        },
        Bspl={
            Buffubertip="该单位处于灵魂锁链的作用之下，因此其遭到攻击的话会将其受到的伤害转移一部分到其他处于灵魂锁链作用之下的单位。", 
            Bufftip="灵魂锁链", race="orc", 
            TargetArt="Abilities\\Spells\\Orc\\SpiritLink\\SpiritLinkTarget.mdl", Targetattachcount=0, 
            Spelldetail=0, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNSpiritLink.blp", Missilespeed=0, Targetattach="chest", 
            MissileHoming=0, 
        },
        BNst={
            EditorName="惊吓", Spelldetail=0, isEffect=0, Missilearc=0.0, race="other", Missilespeed=0, 
            Targetattachcount=0, MissileHoming=0, 
        },
        BOeq={
            Buffubertip="该单位处于地震的作用之下，因此其移动速度被减慢了。", 
            Bufftip="地震", race="orc", TargetArt="Abilities\\Spells\\Orc\\StasisTrap\\StasisTotemTarget.mdl", 
            Targetattachcount=0, Spelldetail=0, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNEarthquake.blp", Missilespeed=0, 
            Targetattach="overhead", MissileHoming=0, 
        },
        Bivs={
            EditorName="隐形 (额外的)", Spelldetail=0, isEffect=0, Missilearc=0.0, race="human", Missilespeed=0, 
            Targetattachcount=0, MissileHoming=0, 
        },
        Binf={
            Buffubertip="该单位拥有心灵之火，所以其防御和攻击力都得到了加强。", 
            Bufftip="心灵之火", race="human", 
            TargetArt="Abilities\\Spells\\Human\\InnerFire\\InnerFireTarget.mdl", Targetattachcount=1, 
            Spelldetail=1, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNInnerFire.blp", Missilespeed=0, 
            Targetattach="overhead", MissileHoming=0, 
        },
        Bhea={
            Buffubertip="该单位正在被医疗，其丧失的生命值将得到恢复。", Bufftip="医疗", 
            race="human", Spelldetail=1, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNHeal.blp", Missilespeed=0, Targetattachcount=0, 
            MissileHoming=0, 
        },
        BUcs={
            EditorName="腐臭蜂群(施法者)", Spelldetail=0, isEffect=0, Missilearc=0.0, race="undead", 
            Missilespeed=0, Targetattachcount=0, MissileHoming=0, 
        },
        AEsd={
            Targetattachcount=0, TargetArt="Abilities\\Spells\\NightElf\\Starfall\\StarfallTarget.mdl", 
            EditorName="群星坠落(目标)", Spelldetail=0, isEffect=0, Missilearc=0.0, Targetattach="origin", 
            MissileHoming=0, race="nightelf", Missilespeed=0, 
        },
        Bgra={
            EditorName="拔树", Spelldetail=0, isEffect=0, Missilearc=0.0, race="nightelf", Missilespeed=0, 
            Targetattachcount=0, MissileHoming=0, 
        },
        Bfae={
            Buffubertip="该单位受到了精灵之火的作用，因此其护甲被削弱了，而且还会被敌人看见。", 
            Bufftip="精灵之火", race="nightelf", 
            TargetArt="Abilities\\Spells\\NightElf\\FaerieFire\\FaerieFireTarget.mdl", Targetattachcount=0, 
            Spelldetail=1, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNFaerieFire.blp", Missilespeed=0, Targetattach="head", 
            MissileHoming=0, 
        },
        Bams={
            Buffubertip="该单位具有反魔法外壳，因此对魔法免疫，反魔法外壳可以被驱逐掉。", 
            Bufftip="反魔法外壳", race="undead", 
            TargetArt="Abilities\\Spells\\Undead\\AntiMagicShell\\AntiMagicShell.mdl", Targetattachcount=0, 
            Spelldetail=0, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNAntiMagicShell.blp", Missilespeed=0, 
            Targetattach="overhead", MissileHoming=0, 
        },
        Bdtb={
            Targetattachcount=0, TargetArt="Abilities\\Spells\\Other\\Drain\\DrainTarget.mdl", 
            EditorName="汲取生命值和魔法值(目标)", Spelldetail=0, isEffect=0, Missilearc=0.0, 
            Targetattach="chest", MissileHoming=0, race="human", Missilespeed=0, 
        },
        Bdbm={
            Buffubertip="这个单位具有额外的魔法值。但是这个额外的值会消失得很快。", 
            Bufftip="吸取魔法", race="human", Spelldetail=0, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNManaDrain.blp", Missilespeed=0, Targetattachcount=0, 
            MissileHoming=0, 
        },
        Bcyc={
            Buffubertip="该单位处在飓风的作用之下，因此其不能移动，攻击和施放魔法。", 
            EffectArt="Abilities\\Spells\\NightElf\\Cyclone\\CycloneTarget.mdl", race="nightelf", Missilespeed=0, 
            Targetattachcount=0, Targetattach="sprite,first", Spelldetail=0, isEffect=0, Missilearc=0.0, 
            Effectsoundlooped="CycloneLoop", MissileHoming=0, Bufftip="飓风", 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNCyclone.blp", 
        },
        Beng={
            Buffubertip="该单位被诱捕了，因此其不能移动和飞行。", Bufftip="诱捕", race="orc", 
            EditorSuffix=" (地面的)", Targetattachcount=0, Spelldetail=0, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNEnsnare.blp", MissileHoming=0, 
            TargetArt="Abilities\\Spells\\Orc\\Ensnare\\ensnareTarget.mdl", Missilespeed=0, 
        },
        Buns={
            Bufftip="反召唤", race="undead", TargetArt="Abilities\\Spells\\Undead\\Unsummon\\UnsummonTarget.mdl", 
            Targetattachcount=0, Spelldetail=0, isEffect=0, Missilearc=0.0, Effectsoundlooped="AcolyteUnsummonLoop", 
            MissileHoming=0, Buffart="ReplaceableTextures\\CommandButtons\\BTNUnsummonBuilding.blp", Missilespeed=0, 
        },
        Bdtm={
            Targetattachcount=0, TargetArt="Abilities\\Spells\\Other\\Drain\\ManaDrainTarget.mdl", 
            EditorName="汲取魔法值 (目标)", Spelldetail=0, isEffect=0, Missilearc=0.0, Targetattach="chest", 
            MissileHoming=0, race="human", Missilespeed=0, 
        },
        BOmi={
            Buffubertip="一个剑圣的幻象。", Bufftip="镜像", race="orc", Targetattachcount=0, Spelldetail=0, 
            isEffect=0, Missilearc=0.0, Buffart="ReplaceableTextures\\CommandButtons\\BTNMirrorImage.blp", 
            Missilespeed=0, SpecialArt="Abilities\\Spells\\Orc\\MirrorImage\\MirrorImageDeathCaster.mdl", 
            MissileHoming=0, 
        },
        BNfy={
            Buffubertip="口袋工厂", Bufftip="口袋工厂", Spelldetail=0, isEffect=0, Missilearc=0.0, race="other", 
            Missilespeed=0, Targetattachcount=0, MissileHoming=0, 
        },
        Beat={
            EditorName="吃树", Spelldetail=0, isEffect=0, Missilearc=0.0, race="nightelf", Missilespeed=0, 
            Targetattachcount=0, MissileHoming=0, 
        },
        BEah={
            Buffubertip="该单位处在荆棘光环的作用之下，因此近战单位攻击它会受到伤害。", 
            Bufftip="荆棘光环", race="nightelf", Specialattach="head", Targetattachcount=0, 
            TargetArt="Abilities\\Spells\\Other\\GeneralAuraTarget\\GeneralAuraTarget.mdl", Targetattach="origin", 
            Spelldetail=2, isEffect=0, Missilearc=0.0, Buffart="ReplaceableTextures\\CommandButtons\\BTNThorns.blp", 
            Missilespeed=0, SpecialArt="Abilities\\Spells\\NightElf\\ThornsAura\\ThornsAuraDamage.mdl", 
            MissileHoming=0, 
        },
        Bdig={
            EditorName="吞噬 (施法者)", Spelldetail=0, isEffect=0, Missilearc=0.0, race="orc", Missilespeed=0, 
            Targetattachcount=0, MissileHoming=0, 
        },
        Bdet={
            Buffubertip="该单位被探测到了，这就意味着敌人可以看见你的单位。", 
            Bufftip="被探测到", race="other", Spelldetail=0, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNDustOfAppearance.blp", Missilespeed=0, 
            Targetattachcount=0, MissileHoming=0, 
        },
        Bdcb={
            Targetattachcount=0, TargetArt="Abilities\\Spells\\Other\\Drain\\DrainCaster.mdl", 
            EditorName="汲取生命值和魔法值(施法者)", Spelldetail=0, isEffect=0, Missilearc=0.0, 
            Targetattach="chest", MissileHoming=0, race="human", Missilespeed=0, 
        },
        BIpv={
            Buffubertip="该英雄使用了吸血药水;因此其攻击力得到了增加，而且攻击的同时也能增加自己的生命值。", 
            Bufftip="吸血药水", race="other", Spelldetail=0, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNPotionOfVampirism.blp", Missilespeed=0, 
            Targetattachcount=0, MissileHoming=0, 
        },
        Bcsi={
            Targetattachcount=0, EditorSuffix=" (信息)", EditorName="冰冻冷箭", Spelldetail=0, isEffect=0, 
            Missilearc=0.0, Missilespeed=0, race="other", MissileHoming=0, 
        },
        BNdm={
            Buffubertip="召唤出来的单位会受到驱逐魔法的伤害。", Bufftip="黑暗之奴", 
            race="other", Spelldetail=0, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNTheBlackArrow.blp", Missilespeed=0, 
            Targetattachcount=0, MissileHoming=0, 
        },
        BEim={
            Buffubertip="该单位有着献祭技能，因此其周围的地面单位会持续受到伤害。", 
            Bufftip="献祭", race="nightelf", Specialattach="head", 
            TargetArt="Abilities\\Spells\\NightElf\\Immolation\\ImmolationTarget.mdl", Targetattachcount=0, 
            Spelldetail=0, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNImmolationOn.blp", Missilespeed=0, 
            SpecialArt="Abilities\\Spells\\NightElf\\Immolation\\ImmolationDamage.mdl", MissileHoming=0, 
        },
        Bcsd={
            Buffubertip="该单位被冰冻冷箭给击中了，其攻击速度和移动速度都会减慢。", 
            Bufftip="冰冻冷箭", EditorSuffix=" (堆积)", race="other", Spelldetail=0, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNColdArrows.blp", MissileHoming=0, Targetattachcount=0, 
            Missilespeed=0, 
        },
        Bdef={
            Buffubertip="该单位受到了守护卷轴的作用，因此它的护甲暂时得到了加强。", 
            Bufftip="守护卷轴", race="other", TargetArt="Abilities\\Spells\\Items\\AIda\\AIdaTarget.mdl", 
            Targetattachcount=0, Spelldetail=1, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNScroll.blp", Missilespeed=0, Targetattach="overhead", 
            MissileHoming=0, 
        },
        Bchd={
            Buffubertip="该单位被击晕了，因此其移动速度和攻击速度都减慢了。", 
            Bufftip="击晕", race="other", TargetArt="Abilities\\Spells\\Orc\\StasisTrap\\StasisTotemTarget.mdl", 
            Targetattachcount=0, Spelldetail=0, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNDizzy.blp", Missilespeed=0, Targetattach="overhead", 
            MissileHoming=0, 
        },
        Xdis={
            EditorName="英雄  驱散 (效果)", Spelldetail=0, isEffect=1, Missilearc=0.0, race="other", Missilespeed=0, 
            Targetattachcount=0, MissileHoming=0, 
        },
        BNcg={
            Buffubertip="人工地精.", Bufftip="人工地精", Spelldetail=0, isEffect=0, Missilearc=0.0, race="other", 
            Missilespeed=0, Targetattachcount=0, MissileHoming=0, 
        },
        Bdcl={
            Targetattachcount=0, TargetArt="Abilities\\Spells\\Other\\Drain\\DrainCaster.mdl", 
            EditorName="汲取生命值(施法者)", Spelldetail=0, isEffect=0, Missilearc=0.0, Targetattach="chest", 
            MissileHoming=0, race="human", Missilespeed=0, 
        },
        Bmlc={
            Targetattachcount=0, EditorName="空中锁镣(施法者)", Spelldetail=0, isEffect=0, Missilearc=0.0, 
            Effectsoundlooped="AerialShacklesLoop", Missilespeed=0, race="human", MissileHoming=0, 
        },
        BNso={
            Buffubertip="该单位受到了灵魂燃烧的作用。不能施放魔法，攻击力会减小，并在一定时间内会持续受到伤害。", 
            Bufftip="灵魂燃烧", race="other", TargetArt="Abilities\\Spells\\Other\\SoulBurn\\SoulBurnbuff.mdl", 
            Targetattachcount=0, Spelldetail=0, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNSoulBurn.blp", Missilespeed=0, Targetattach="overhead", 
            MissileHoming=0, 
        },
        BIsh={
            EffectArt="Abilities\\Spells\\Orc\\FeralSpirit\\feralspiritdone.mdl", race="other", Spelldetail=0, 
            isEffect=0, Missilearc=0.0, Targetattachcount=0, MissileHoming=0, Bufftip="猎头者灵魂", Missilespeed=0, 
        },
        Bcri={
            Buffubertip="该单位受到了残废技能的作用，因此其移动速度和攻击速度都减慢了，攻击力也被削弱了许多。", 
            Bufftip="残废", TargetArt="Abilities\\Spells\\Undead\\Cripple\\CrippleTarget.mdl", race="undead", 
            Spelldetail=0, isEffect=0, Missilearc=0.0, Buffart="ReplaceableTextures\\CommandButtons\\BTNCripple.blp", 
            Missilespeed=0, Targetattachcount=0, MissileHoming=0, 
        },
        BNic={
            Buffubertip="这个单位处于了烈焰之中，在死去之后会对周围的单位造成一定的伤害。", 
            Bufftip="燃灰", race="other", Targetattach="chest", 
            TargetArt="Abilities\\Spells\\Other\\Incinerate\\IncinerateBuff.mdl", Targetattachcount=0, 
            Spelldetail=0, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNIncinerate.blp", Missilespeed=0, 
            SpecialArt="Abilities\\Spells\\Other\\Incinerate\\FireLordDeathExplode.mdl", MissileHoming=0, 
        },
        BUim={
            Buffubertip="该单位被穿刺攻击了，因此在短时间内会被抛在空中。", 
            EffectArt="Abilities\\Spells\\Undead\\Impale\\ImpaleHitTarget.mdl", race="undead", 
            TargetArt="Abilities\\Spells\\Human\\StormBolt\\StormBoltTarget.mdl", Targetattachcount=0, 
            Effectattach="sprite,first", Targetattach="overhead", Spelldetail=0, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNImpale.blp", MissileHoming=0, Missilespeed=0, 
            Bufftip="穿刺", 
        },
        BHtc={
            Buffubertip="该单位受到了雷霆一击的攻击，其移动速度和攻击速度都会减慢。", 
            Bufftip="雷霆一击", race="human", 
            TargetArt="Abilities\\Spells\\Orc\\StasisTrap\\StasisTotemTarget.mdl", Targetattachcount=0, 
            Spelldetail=0, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNThunderclap.blp", Missilespeed=0, 
            Targetattach="overhead", MissileHoming=0, 
        },
        Bcor={
            Buffubertip="该建筑物受到了腐蚀喷吐的攻击，因此其在一定的时间内会受到持续的伤害。", 
            Bufftip="腐蚀喷吐", 
            TargetArt="Abilities\\Spells\\NightElf\\CorrosiveBreath\\ChimaeraAcidTargetArt.mdl", race="nightelf", 
            Spelldetail=0, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNCorrosiveBreath.blp", Missilespeed=0, 
            Targetattachcount=0, MissileHoming=0, 
        },
        Bult={
            EditorName="夜视能力", Spelldetail=0, isEffect=0, Missilearc=0.0, race="nightelf", Missilespeed=0, 
            Targetattachcount=0, MissileHoming=0, 
        },
        BNwm={
            Buffubertip="召唤出来的单位会受到驱逐魔法的伤害。", 
            EffectArt="Abilities\\Spells\\Orc\\FeralSpirit\\feralspiritdone.mdl", race="other", Targetattachcount=0, 
            Spelldetail=0, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNMurgulTideWarrior.blp", MissileHoming=0, 
            Missilespeed=0, Bufftip="水奴", 
        },
        Bblo={
            Buffubertip="该单位具有嗜血术，因此其攻击速度和移动速度都加快了。", 
            Bufftip="嗜血术", race="orc", Targetattach1="hand,right", 
            TargetArt="Abilities\\Spells\\Orc\\Bloodlust\\BloodlustTarget.mdl,Abilities\\Spells\\Orc\\Bloodlust\\BloodlustSpecial.mdl", 
            Targetattachcount=2, Spelldetail=1, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNBloodLust.blp", Missilespeed=0, 
            Targetattach="hand,left", MissileHoming=0, 
        },
        Bssi={
            EditorName="慢性毒药(信息)", Spelldetail=0, isEffect=0, Missilearc=0.0, race="nightelf", Missilespeed=0, 
            Targetattachcount=0, MissileHoming=0, 
        },
        Bbar={
            Buffubertip="该单位具有树皮技能，因此其护甲得到了加强。", Bufftip="树皮", 
            race="nightelf", TargetArt="Abilities\\Spells\\NightElf\\Barkskin\\BarkSkinTarget.mdl", 
            Targetattachcount=0, Spelldetail=0, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNBarkskin.blp", Missilespeed=0, Targetattach="chest", 
            MissileHoming=0, 
        },
        XHbz={
            EffectArt="Abilities\\Spells\\Human\\Blizzard\\BlizzardTarget.mdl", race="human", Targetattachcount=0, 
            EditorName="暴风雪 (效果)", Spelldetail=0, isEffect=1, Missilearc=0.0, 
            Effectsoundlooped="BlizzardLoop", MissileHoming=0, Missilespeed=0, Effectsound="BlizzardWave", 
        },
        BNsl={
            Targetattachcount=0, race="other", EditorName="灵魂保存", Spelldetail=0, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNSleep.blp", Effectsound="SoulPreservation", 
            MissileHoming=0, Missilespeed=0, 
        },
        BHca={
            Buffubertip="该单位被冰冻冷箭给击中了，其攻击速度和移动速度都会减慢。", 
            Bufftip="冰冻冷箭", EditorSuffix=" (没有堆积)", race="other", Spelldetail=0, isEffect=0, 
            Missilearc=0.0, Buffart="ReplaceableTextures\\CommandButtons\\BTNColdArrows.blp", MissileHoming=0, 
            Targetattachcount=0, Missilespeed=0, 
        },
        BNin={
            Buffubertip="这个地狱火是大型的。", Bufftip="地狱火", Spelldetail=0, isEffect=0, 
            Missilearc=0.0, race="other", Missilespeed=0, Targetattachcount=0, MissileHoming=0, 
        },
        Bens={
            Targetattachcount=0, race="orc", TargetArt="Abilities\\Spells\\Orc\\Ensnare\\ensnareTarget.mdl", 
            EditorName="诱捕(一般的)", Spelldetail=0, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNEnsnare.blp", Missilespeed=0, Targetattach="origin", 
            MissileHoming=0, 
        },
        BOsf={
            Buffubertip="召唤出来的单位会受到驱逐魔法的伤害。", 
            EffectArt="Abilities\\Spells\\Orc\\FeralSpirit\\feralspiritdone.mdl", race="orc", Targetattachcount=0, 
            Spelldetail=0, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNSpiritWolf.blp", MissileHoming=0, Missilespeed=0, 
            Bufftip="野兽幽魂", 
        },
        BHwe={
            Buffubertip="召唤出来的单位容易遭到驱散。", Bufftip="水元素", race="human", 
            Spelldetail=0, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNSummonWaterElemental.blp", Missilespeed=0, 
            Targetattachcount=0, MissileHoming=0, 
        },
        BNmr={
            Buffubertip="该单位受到了心灵腐烂的攻击，因此其魔法值将在一定时间内持续地被减少。", 
            Bufftip="心灵腐烂", race="other", Spelldetail=0, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNTemp.blp", Missilespeed=0, Targetattachcount=0, 
            MissileHoming=0, 
        },
        Bcrs={
            Buffubertip="该单位受到了诅咒的作用，因此在攻击的时候会有一定的概率击空。", 
            Bufftip="诅咒", race="undead", TargetArt="Abilities\\Spells\\Undead\\Curse\\CurseTarget.mdl", 
            Targetattachcount=0, Spelldetail=1, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNCurse.blp", Missilespeed=0, Targetattach="overhead", 
            MissileHoming=0, 
        },
        BIcf={
            Buffubertip="该单位拥有火焰风衣，周围的地面单位会受到持续的伤害。", 
            Bufftip="火焰风衣", race="other", Specialattach="head", 
            TargetArt="Abilities\\Spells\\NightElf\\Immolation\\ImmolationTarget.mdl", Targetattachcount=0, 
            Spelldetail=0, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNCloakOfFlames.blp", Missilespeed=0, 
            SpecialArt="Abilities\\Spells\\NightElf\\Immolation\\ImmolationDamage.mdl", MissileHoming=0, 
        },
        BNva={
            EditorName="Volcano (Area)", Spelldetail=0, isEffect=0, Missilearc=0.0, race="other", Missilespeed=0, 
            Targetattachcount=0, MissileHoming=0, 
        },
        BNdc={
            Buffubertip="这个村民受到了黑暗转换的攻击，因此会陷入睡眠并变成一个僵尸。", 
            EffectArt="Abilities\\Spells\\Demon\\DarkConversion\\ZombifyTarget.mdl", race="other", 
            Targetattach="overhead", TargetArt="Abilities\\Spells\\Undead\\Sleep\\SleepTarget.mdl", 
            Targetattachcount=0, Spelldetail=0, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNSleep.blp", MissileHoming=0, Missilespeed=0, 
            Bufftip="黑暗转换", 
        },
        BNba={
            Buffubertip="该单位受到了黑暗之箭的攻击，如果其死亡的话，那么就会变成一个骷髅兵。", 
            Bufftip="黑暗之箭", race="other", Spelldetail=0, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNTheBlackArrow.blp", Missilespeed=0, 
            Targetattachcount=0, MissileHoming=0, 
        },
        BHab={
            Buffubertip="该单位处于辉煌光环之下，因此其魔法恢复速度将加快。", 
            Bufftip="辉煌光环", race="human", 
            TargetArt="Abilities\\Spells\\Other\\GeneralAuraTarget\\GeneralAuraTarget.mdl", Targetattachcount=0, 
            Spelldetail=2, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNBrilliance.blp", Missilespeed=0, Targetattach="origin", 
            MissileHoming=0, 
        },
        Bakb={
            Buffubertip="该单位受到了战鼓的作用，因此攻击力得到了加强。", Bufftip="战鼓", 
            race="orc", TargetArt="Abilities\\Spells\\Other\\GeneralAuraTarget\\GeneralAuraTarget.mdl", 
            Targetattachcount=0, Spelldetail=2, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNDrum.blp", Missilespeed=0, Targetattach="origin", 
            MissileHoming=0, 
        },
        Bapl={
            Buffubertip="该单位受到了疾病云雾的攻击，因此会在短时间内持续地受到伤害。", 
            Bufftip="疾病", race="undead", TargetArt="Units\\Undead\\PlagueCloud\\PlagueCloudtarget.mdl", 
            Targetattachcount=0, Spelldetail=2, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNPlagueCloud.blp", Missilespeed=0, Targetattach="head", 
            MissileHoming=0, 
        },
        BOhx={
            Buffubertip="该单位受到了妖术的作用，因此其变成了一只小动物。", 
            EffectArt="Abilities\\Spells\\Human\\Polymorph\\PolyMorphDoneGround.mdl", race="orc", 
            Targetattachcount=0, Spelldetail=0, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNHex.blp", MissileHoming=0, Missilespeed=0, 
            Bufftip="妖术", 
        },
        Bmlt={
            Buffubertip="该单位已受空中锁镣禁锢，无法移动或攻击，并且不断受到伤害。", 
            Bufftip="空中锁镣", race="human", 
            TargetArt="Abilities\\Spells\\Human\\AerialShackles\\AerialShacklesTarget.mdl", Targetattachcount=0, 
            Spelldetail=0, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNMagicLariet.blp", Missilespeed=0, 
            Targetattach="chest,mount", MissileHoming=0, 
        },
        BUsp={
            Targetattachcount=0, TargetArt="Abilities\\Spells\\Undead\\Sleep\\SleepSpecialArt.mdl", 
            EditorName="睡眠 (暂停)", Spelldetail=0, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNSleep.blp", Missilespeed=0, race="undead", 
            MissileHoming=0, 
        },
        BUsl={
            Buffubertip="该单位正在睡眠，因此其不能移动，攻击或者施放魔法。如果遭到攻击就会自动苏醒过来。", 
            Bufftip="睡眠", race="undead", Targetattach="overhead", 
            TargetArt="Abilities\\Spells\\Undead\\Sleep\\SleepTarget.mdl", Targetattachcount=0, Spelldetail=0, 
            isEffect=0, Missilearc=0.0, Buffart="ReplaceableTextures\\CommandButtons\\BTNSleep.blp", MissileHoming=0, 
            Missilespeed=0, Effectsoundlooped="CreepSleepSnoreLoop", 
        },
        BIpd={
            Targetattachcount=0, TargetArt="Abilities\\Weapons\\PoisonSting\\PoisonStingTarget.mdl", Spelldetail=2, 
            isEffect=0, Missilearc=0.0, Buffart="ReplaceableTextures\\CommandButtons\\BTNOrbOfVenom.blp", 
            MissileHoming=0, race="other", Missilespeed=0, 
        },
        BCbf={
            Buffubertip="该单位遭到了霜冻闪电的攻击，因此会持续地受到伤害。", 
            Bufftip="霜冻闪电", TargetArt="Abilities\\Spells\\Other\\BreathOfFrost\\BreathOfFrostTarget.mdl", 
            race="other", Spelldetail=0, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNBreathOfFrost.blp", Missilespeed=0, 
            Targetattachcount=0, MissileHoming=0, 
        },
        BIwb={
            EditorName="物品网", Spelldetail=0, isEffect=0, Missilearc=0.0, race="other", Missilespeed=0, 
            Targetattachcount=0, MissileHoming=0, 
        },
        BUts={
            Targetattach1="chest,right", Targetattachcount=4, race="undead", Targetattach2="chest,mount,left", 
            Targetattach3="chest,mount,right", 
            TargetArt="Abilities\\Spells\\Undead\\ThornyShield\\ThornyShieldTargetChestLeft.mdl,Abilities\\Spells\\Undead\\ThornyShield\\ThornyShieldTargetChestRight.mdl,Abilities\\Spells\\Undead\\ThornyShield\\ThornyShieldTargetChestMountLeft.mdl,Abilities\\Spells\\Undead\\ThornyShield\\ThornyShieldTargetChestMountRight.mdl", 
            EditorName="尖刺外壳", Spelldetail=0, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNThornShield.blp", Missilespeed=0, 
            Targetattach="chest,left", MissileHoming=0, 
        },
        BNtm={
            Buffubertip="这个单位受到了点金术的作用。将会变成金币。", Bufftip="点金术", 
            race="other", Targetattachcount=0, Spelldetail=0, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNTransmute.blp", Missilespeed=0, 
            SpecialArt="Abilities\\Spells\\Other\\Transmute\\PileofGold.mdl", MissileHoming=0, 
        },
        BUdd={
            Buffubertip="该单位受到了死亡凋零的作用，因此会持续地受到伤害。", 
            Bufftip="死亡凋零", TargetArt="Abilities\\Spells\\Undead\\DeathandDecay\\DeathandDecayDamage.mdl", 
            race="undead", Spelldetail=0, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNDeathAndDecay.blp", Missilespeed=0, 
            Targetattachcount=0, MissileHoming=0, 
        },
        BCtc={
            Buffubertip="该单位受到了雷霆一击的攻击，因此其移动速度和攻击速度都减慢了。", 
            Bufftip="雷霆一击", race="other", 
            TargetArt="Abilities\\Spells\\Orc\\StasisTrap\\StasisTotemTarget.mdl", Targetattachcount=0, 
            Spelldetail=0, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNGolemThunderclap.blp", Missilespeed=0, 
            Targetattach="overhead", MissileHoming=0, 
        },
        BUau={
            Buffubertip="该单位处在邪恶光环的作用之下; 因此它的移动速度和生命值恢复速度都加快了。", 
            Bufftip="邪恶光环", race="undead", 
            TargetArt="Abilities\\Spells\\Other\\GeneralAuraTarget\\GeneralAuraTarget.mdl", Targetattachcount=0, 
            Spelldetail=2, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNUnholyAura.blp", Missilespeed=0, Targetattach="origin", 
            MissileHoming=0, 
        },
        BIcb={
            Buffubertip="该单位受到了腐蚀之球的攻击，因此其护甲得到了削弱。", 
            Bufftip="腐蚀", race="other", Spelldetail=0, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNOrbOfCorruption.blp", Missilespeed=0, 
            Targetattachcount=0, MissileHoming=0, 
        },
        BNlm={
            Buffubertip="炎魔", Bufftip="炎魔", race="other", Spelldetail=0, isEffect=0, Missilearc=0.99, 
            Missileart="Abilities\\Weapons\\LavaSpawnMissile\\LavaSpawnBirthMissile.mdl", Missilespeed=200, 
            Targetattachcount=0, MissileHoming=1, 
        },
        BSTN={
            Buffubertip="该单位被击晕了，所以不能移动，攻击和施放魔法。", 
            Bufftip="被击晕的", race="other", 
            TargetArt="Abilities\\Spells\\Human\\Thunderclap\\ThunderclapTarget.mdl", Targetattachcount=0, 
            Spelldetail=0, isEffect=0, Missilearc=0.0, Buffart="ReplaceableTextures\\CommandButtons\\BTNStun.blp", 
            Missilespeed=0, Targetattach="overhead", MissileHoming=0, 
        },
        BNdh={
            Buffubertip="该单位遭到了醉酒云雾的攻击，因此其移动速度被减慢了，并有一定的概率不能击中其他单位。", 
            Bufftip="醉酒云雾", race="other", 
            TargetArt="Abilities\\Spells\\Other\\StrongDrink\\BrewmasterTarget.mdl", Targetattachcount=0, 
            Spelldetail=0, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNStrongDrink.blp", Missilespeed=0, 
            Targetattach="overhead", MissileHoming=0, 
        },
        BUav={
            Buffubertip="该单位处在吸血光环的作用之下，因此它对敌人的攻击会恢复自己的生命值。", 
            Bufftip="吸血光环", race="undead", Specialattach="origin", Targetattachcount=0, 
            TargetArt="Abilities\\Spells\\Other\\GeneralAuraTarget\\GeneralAuraTarget.mdl", Targetattach="origin", 
            Spelldetail=2, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNVampiricAura.blp", Missilespeed=0, 
            SpecialArt="Abilities\\Spells\\Undead\\VampiricAura\\VampiricAuraTarget.mdl", MissileHoming=0, 
        },
        BNeg={
            Targetattach1="chest,right", Bufftip="工程升级", race="other", Targetattachcount=4, 
            Targetattach3="chest,mount,right", 
            TargetArt="Abilities\\Spells\\Undead\\ThornyShield\\ThornyShieldTargetChestLeft.mdl,Abilities\\Spells\\Undead\\ThornyShield\\ThornyShieldTargetChestRight.mdl,Abilities\\Spells\\Undead\\ThornyShield\\ThornyShieldTargetChestMountLeft.mdl,Abilities\\Spells\\Undead\\ThornyShield\\ThornyShieldTargetChestMountRight.mdl", 
            Targetattach2="chest,mount,left", Spelldetail=0, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNEngineeringUpgrade.blp", Missilespeed=0, 
            Targetattach="chest,left", MissileHoming=0, 
        },
        BOww={
            EditorName="剑刃风暴(施法者)", Spelldetail=0, isEffect=0, Missilearc=0.0, race="orc", Missilespeed=0, 
            Targetattachcount=0, MissileHoming=0, 
        },
        BNht={
            Buffubertip="这个单位被恐怖嚎叫震住了；它已经丢失了魔法效果，并将持续一段时间减弱攻击。", 
            Bufftip="恐怖嚎叫", TargetArt="Abilities\\Spells\\Other\\HowlOfTerror\\HowlTarget.mdl", 
            race="other", Spelldetail=0, isEffect=0, Missilearc=0.0, 
            Buffart="ReplaceableTextures\\CommandButtons\\BTNHowlOfTerror.blp", Missilespeed=0, Targetattachcount=0, 
            MissileHoming=0, 
        },
        BIsv={
            Buffubertip="这是一个英雄的灵魂。", Bufftip="盗取灵魂", 
            TargetArt="Abilities\\Spells\\Items\\AIso\\BIsvTarget.mdl", race="other", Spelldetail=0, isEffect=0, 
            Missilearc=0.0, Buffart="ReplaceableTextures\\CommandButtons\\BTNUsedSoulGem.blp", Missilespeed=0, 
            Targetattachcount=0, MissileHoming=0, 
        },
        XNvc={
            Targetattachcount=0, race="other", SpecialArt="Abilities\\Spells\\Other\\Volcano\\VolcanoDeath.mdl", 
            EditorName="Volcano (Effect)", Spelldetail=0, isEffect=1, Missilearc=0.8, 
            Missileart="Abilities\\Spells\\Other\\Volcano\\VolcanoMissile.mdl", Missilespeed=400, 
            Effectsoundlooped="VolcanoLoop", MissileHoming=1, 
        },
        Xfhl={
            race="human", Targetattach1="sprite,second", Targetattach2="sprite,fifth", Targetattachcount=6, 
            Targetattach5="sprite,sixth", Targetattach4="sprite,fourth", Targetattach3="sprite,third", 
            TargetArt="Environment\\LargeBuildingFire\\LargeBuildingFire1.mdl,Environment\\LargeBuildingFire\\LargeBuildingFire0.mdl,Environment\\LargeBuildingFire\\LargeBuildingFire0.mdl,Environment\\SmallBuildingFire\\SmallBuildingFire1.mdl,Environment\\LargeBuildingFire\\LargeBuildingFire1.mdl,Environment\\SmallBuildingFire\\SmallBuildingFire0.mdl", 
            EditorName="建筑物伤害 – 人族  大", Spelldetail=0, isEffect=1, Missilearc=0.0, 
            Effectsoundlooped="HumanFireLarge", Missilespeed=0, Targetattach="sprite,first", MissileHoming=0, 
        },
        BFig={
            Buffubertip="对于驱逐魔法，召唤出来的单位将受到额外的伤害。", 
            EffectArt="Abilities\\Spells\\Orc\\FeralSpirit\\feralspiritdone.mdl", race="other", Spelldetail=0, 
            isEffect=0, Missilearc=0.0, Targetattachcount=0, MissileHoming=0, Bufftip="召唤出来的物品", 
            Missilespeed=0, 
        },
        Bphx={
            Buffubertip="火凤凰的力量显现了。", Bufftip="火凤凰", Spelldetail=0, isEffect=0, 
            Missilearc=0.0, race="human", Missilespeed=0, Targetattachcount=0, MissileHoming=0, 
        },
    },
    category="buff", 
}