return {
    keys={
        goldmod="每等级增加黄金", Art="图标", code4="效果 4 - %s", EditorSuffix3="编辑器后缀", 
        goldbase="基础黄金消耗", maxlevel="等级", Requires3="需求", Name1="名字", 
        EditorSuffix1="编辑器后缀", Ubertip2="提示工具 - 扩展", Hotkey2="热键", 
        lumbermod="每等级增加木材", global="只应用于之后生产的单位", 
        Buttonpos_2="按钮位置(Y)", Requires1="需求", base1="效果 1 - %s", Hotkey1="热键", 
        mod1="效果 1 - %s", EditorSuffix2="编辑器后缀", Buttonpos_1="按钮位置(X)", Art2="图标", 
        inherit="可随单位转移所有者", Ubertip="提示工具 - 扩展", Name3="名字", Hotkey="热键", 
        Hotkey3="热键", base2="效果 2 - %s", code3="效果 3 - %s", effect2="效果 2", Name2="名字", 
        Art3="图标", mod3="效果 3 - %s", Ubertip1="提示工具 - 扩展", EditorSuffix="编辑器后缀", 
        effect3="效果 3", race="种族", Requires="需求", Tip2="提示工具", Tip1="提示工具", 
        mod2="效果 2 - %s", Ubertip3="提示工具 - 扩展", code1="效果 1 - %s", 
        timebase="基础时间消耗", Tip="提示工具", Tip3="提示工具", mod4="效果 4 - %s", 
        class="升级类型", Art1="图标", base4="效果 4 - %s", code2="效果 2 - %s", 
        timemod="每等级增加时间", Requiresamount="需求值", Name="名字", Requires2="需求", 
        effect4="效果 4", effect1="效果 1", base3="效果 3 - %s", lumberbase="基础木材消耗", 
    },
    items={
        Rnsb={
            goldmod=0, Art="ReplaceableTextures\\CommandButtons\\BTNNagaBurrow.blp", code4="", goldbase=25, maxlevel=1, 
            lumbermod=0, global=0, Buttonpos_2=2, base1=0.0, mod1=0.0, Buttonpos_1=2, inherit=1, 
            Ubertip="给予娜迦暴徒和飞龙潜入水中，隐去行踪的能力。", Hotkey="U", base2=0.0, 
            code3="", effect2="", effect3="", race="naga", code1="", timebase=20, Tip="研究潜水(|cffffcc00U|r)", class="", 
            mod4=0.0, base4=0.0, code2="", mod3=0.0, Name="潜水", mod2=0.0, effect4="", effect1="", base3=0.0, lumberbase=25, 
        },
        Rowd={
            goldmod=0, class="caster", code4="", goldbase=100, effect4="ratd", Name1="巫医专家训练", lumbermod=100, 
            global=0, Buttonpos_2=2, Requires1="", base1=100.0, mod1=100.0, Buttonpos_1=1, 
            Art2="ReplaceableTextures\\CommandButtons\\BTNWitchDoctorMaster.blp", 
            Ubertip2="增加巫医的魔法最大值，魔法恢复速度，生命值和攻击力。还能使其获得静止治疗守卫技能。", 
            base2=0.325, code3="", effect2="rmnr", Name2="巫医大师训练", effect3="rhpx", Hotkey1="D", Hotkey2="D", 
            mod4=0.0, race="orc", code1="", timebase=60, 
            Ubertip1="增加巫医的魔法最大值，魔法恢复速度，生命值和攻击力。还能使其获得静止陷阱技能。", 
            mod3=40.0, mod2=0.325, maxlevel=2, Art1="ReplaceableTextures\\CommandButtons\\BTNWitchDoctorAdept.blp", 
            Tip1="巫医专家训练(|cffffcc00D|r)", code2="", inherit=1, base4=0.0, Requires2="ofrt", effect1="rmnx", 
            Tip2="巫医大师训练(|cffffcc00D|r)", base3=40.0, lumberbase=50, 
        },
        Rhri={
            goldmod=0, Art="ReplaceableTextures\\CommandButtons\\BTNDwarvenLongRifle.blp", code4="", goldbase=75, 
            effect4="", lumbermod=0, global=0, Buttonpos_2=2, base1=200.0, mod1=200.0, Buttonpos_1=1, inherit=1, 
            Ubertip="增加矮人火枪手的攻击范围。", Hotkey="L", base2=0.0, code3="", effect2="", effect3="", 
            race="human", Requires="harm", code1="", timebase=30, Tip="升级到长管火枪(|cffffcc00L|r)", mod3=0.0, 
            mod4=0.0, base4=0.0, code2="", class="", Name="长管火枪", mod2=0.0, maxlevel=1, effect1="ratr", base3=0.0, 
            lumberbase=125, 
        },
        Rhar={
            goldmod=25, class="armor", code4="", Hotkey3="P", effect4="", Name1="铁甲", lumbermod=100, global=0, 
            Buttonpos_2=1, Requires1="", base1=0.0, mod1=0.0, Buttonpos_1=0, 
            Art2="ReplaceableTextures\\CommandButtons\\BTNHumanArmorUpTwo.blp", Hotkey2="P", 
            Art3="ReplaceableTextures\\CommandButtons\\BTNHumanArmorUpThree.blp", base2=0.0, code3="", effect2="", 
            Name2="钢甲", effect1="rarm", Tip2="升级到钢甲(|cffffcc00P|r)", race="human", effect3="", 
            Name3="重金甲", mod4=0.0, mod3=0.0, mod2=0.0, maxlevel=3, 
            Ubertip3="进一步增加民兵、步兵、魔法破坏者、骑士、飞行机器和蒸汽机车的护甲。", 
            code1="", timebase=60, 
            Ubertip1="增加民兵、步兵、魔法破坏者、骑士、飞行机器和蒸汽机车的护甲。", 
            Tip3="升级到重金甲(|cffffcc00P|r)", inherit=0, goldbase=125, 
            Art1="ReplaceableTextures\\CommandButtons\\BTNHumanArmorUpOne.blp", Tip1="铁甲(|cffffcc00P|r)", 
            code2="", 
            Ubertip2="进一步增加民兵、步兵、魔法破坏者、骑士、飞行机器和蒸汽机车的护甲。", 
            Requires3="hcas", Requires2="hkee", Hotkey1="P", base4=0.0, base3=0.0, lumberbase=75, 
        },
        Ruex={
            goldmod=0, Art="ReplaceableTextures\\CommandButtons\\BTNExhumeCorpses.blp", code4="", goldbase=125, 
            effect4="", lumbermod=0, global=0, Buttonpos_2=2, base1=0.0, mod1=0.0, Buttonpos_1=0, inherit=1, 
            Ubertip="让绞肉车能制造出尸体。", Hotkey="E", base2=0.0, code3="", effect2="", effect3="", 
            race="undead", Requires="unp2", code1="", timebase=20, Tip="挖掘尸体(|cffffcc00E|r)", mod3=0.0, mod4=0.0, 
            base4=0.0, code2="", class="", Name="挖掘尸体", mod2=0.0, maxlevel=1, effect1="", base3=0.0, lumberbase=100, 
        },
        Rora={
            goldmod=50, class="ranged", code4="", Hotkey3="R", effect4="", Name1="钢铁远程武器", lumbermod=100, 
            global=0, Buttonpos_2=0, Requires1="", base1=1.0, mod1=1.0, Buttonpos_1=1, 
            Art2="ReplaceableTextures\\CommandButtons\\BTNThoriumRanged.blp", Hotkey2="R", 
            Art3="ReplaceableTextures\\CommandButtons\\BTNArcaniteRanged.blp", base2=0.0, code3="", effect2="", 
            Name2="金属远程武器", effect1="ratd", Tip2="升级到金属远程武器(|cffffcc00R|r)", race="orc", 
            effect3="", Name3="终极远程武器", mod4=0.0, mod3=0.0, mod2=0.0, maxlevel=3, 
            Ubertip3="进一步增加巨魔猎头者，风骑士，粉碎者和巨魔蝙蝠骑士的远程攻击力。", 
            code1="", timebase=60, 
            Ubertip1="能增加巨魔猎头者，风骑士，粉碎者和巨魔蝙蝠骑士的远程攻击力。", 
            Tip3="升级到终极远程武器(|cffffcc00R|r)", inherit=0, goldbase=100, 
            Art1="ReplaceableTextures\\CommandButtons\\BTNSteelRanged.blp", 
            Tip1="升级到钢铁远程武器(|cffffcc00R|r)", code2="", 
            Ubertip2="进一步增加巨魔猎头者，风骑士，粉碎者和巨魔蝙蝠骑士的远程攻击力。", 
            Requires3="ofrt", Requires2="ostr", Hotkey1="R", base4=0.0, base3=0.0, lumberbase=100, 
        },
        Rome={
            goldmod=50, class="melee", code4="", Hotkey3="M", effect4="", Name1="钢铁近战武器", lumbermod=100, global=0, 
            Buttonpos_2=0, Requires1="", base1=1.0, mod1=1.0, Buttonpos_1=0, 
            Art2="ReplaceableTextures\\CommandButtons\\BTNOrcMeleeUpTwo.blp", Hotkey2="M", 
            Art3="ReplaceableTextures\\CommandButtons\\BTNOrcMeleeUpThree.blp", base2=0.0, code3="", effect2="", 
            Name2="金属近战武器", effect1="ratd", Tip2="升级到金属近战武器(|cffffcc00M|r)", race="orc", 
            effect3="", Name3="终极近战武器", mod4=0.0, mod3=0.0, mod2=0.0, maxlevel=3, 
            Ubertip3="进一步增加兽族步兵，掠夺者，牛头人的攻击力。", code1="", timebase=60, 
            Ubertip1="增加兽族步兵，掠夺者，牛头人的攻击力。", 
            Tip3="升级到终极近战武器(|cffffcc00M|r)", inherit=0, goldbase=100, 
            Art1="ReplaceableTextures\\CommandButtons\\BTNOrcMeleeUpOne.blp", 
            Tip1="升级到钢铁近战武器(|cffffcc00M|r)", code2="", 
            Ubertip2="进一步增加兽族步兵，掠夺者，牛头人的攻击力。", Requires3="ofrt", 
            Requires2="ostr", Hotkey1="M", base4=0.0, base3=0.0, lumberbase=75, 
        },
        Reec={
            goldmod=0, class="", code4="", goldbase=25, effect4="", lumbermod=0, global=0, effect1="", base1=0.0, mod1=0.0, 
            Buttonpos_1=1, inherit=1, 
            Ubertip="让猛禽德鲁伊在风暴之鸦的状态下能施放精灵之火技能。", Hotkey="M", 
            base2=0.0, code3="", effect2="", effect3="", race="nightelf", Requires="Redt", code1="", timebase=20, 
            Tip="研究猛禽之痕(|cffffcc00M|r)", mod2=0.0, mod4=0.0, mod3=0.0, base4=0.0, code2="", Requiresamount="2", 
            Name="猛禽之痕", Art="ReplaceableTextures\\CommandButtons\\BTNEnchantedCrows.blp", maxlevel=1, 
            Buttonpos_2=1, base3=0.0, lumberbase=100, 
        },
        Rosp={
            goldmod=25, class="", code4="", Hotkey3="S", effect4="", Name1="尖刺障碍", lumbermod=100, global=0, 
            Buttonpos_2=0, Requires1="", base1=4.0, mod1=6.0, Buttonpos_1=2, 
            Art2="ReplaceableTextures\\CommandButtons\\BTNImprovedSpikedBarricades.blp", Hotkey2="S", 
            Art3="ReplaceableTextures\\CommandButtons\\BTNAdvancedSpikedBarricades.blp", base2=0.0, code3="", 
            effect2="", Name2="中级尖刺障碍", effect1="rspi", Tip2="升级到中级尖刺障碍(|cffffcc00S|r)", 
            race="orc", effect3="", Name3="高级尖刺障碍", mod4=0.0, mod3=0.0, mod2=0.0, maxlevel=3, 
            Ubertip3="使得兽族的建筑物周围都布满了具有攻击力的尖刺，如果敌人每进行一次近战攻击就会受到<Rosp,mod1>点伤害。", 
            code1="", timebase=60, 
            Ubertip1="使得兽族的建筑物周围都布满了具有攻击力的尖刺，如果敌人每进行一次近战攻击就会受到<Rosp,base1>点伤害。", 
            Tip3="升级到高级尖刺障碍(|cffffcc00S|r)", inherit=0, goldbase=25, 
            Art1="ReplaceableTextures\\CommandButtons\\BTNSpikedBarricades.blp", 
            Tip1="升级到尖刺障碍(|cffffcc00S|r)", code2="", 
            Ubertip2="使得兽族的建筑物周围都布满了具有攻击力的尖刺，如果敌人每进行一次近战攻击就会受到<Rosp,mod1>点伤害。", 
            Requires3="ofrt", Requires2="ostr", Hotkey1="S", base4=0.0, base3=0.0, lumberbase=75, 
        },
        Resi={
            goldmod=0, Art="ReplaceableTextures\\CommandButtons\\BTNDryadDispelMagic.blp", code4="", goldbase=50, 
            maxlevel=1, lumbermod=0, global=0, Buttonpos_2=2, base1=0.0, mod1=0.0, Buttonpos_1=0, inherit=1, 
            Ubertip="使得树妖能去除掉敌人身上的有利魔法效果和友军单位身上的不利魔法效果。|n能伤害召唤出来的单位。", 
            Hotkey="S", base2=0.0, code3="", effect2="", effect3="", race="nightelf", code1="", timebase=45, 
            Tip="研究驱散魔法(|cffffcc00S|r)", class="", mod4=0.0, base4=0.0, code2="", mod3=0.0, Name="驱逐魔法", 
            mod2=0.0, effect4="", effect1="", base3=0.0, lumberbase=50, 
        },
        Robk={
            goldmod=0, Art="ReplaceableTextures\\CommandButtons\\BTNHeadHunterBerserker.blp", code4="", goldbase=75, 
            effect4="", lumbermod=0, global=1, Buttonpos_2=2, base1=1.0, mod1=0.0, Buttonpos_1=1, inherit=1, 
            Ubertip="将巨魔猎头者变为巨魔狂暴战士。使其拥有更多的生命值和狂暴愤怒技能。", 
            Hotkey="E", base2=-1.0, code3="", effect2="rtma", effect3="", race="orc", Requires="ofrt,ofor", code1="ohun", 
            timebase=40, Tip="升级狂战士(|cffffcc00E|r)", mod3=0.0, mod4=0.0, base4=0.0, code2="otbk", class="", 
            Name="狂暴愤怒升级", mod2=0.0, maxlevel=1, effect1="rtma", base3=0.0, lumberbase=175, 
        },
        Reeb={
            goldmod=0, class="", code4="", goldbase=25, effect4="", lumbermod=0, global=0, effect1="", base1=0.0, mod1=0.0, 
            Buttonpos_1=1, inherit=1, Ubertip="让利爪德鲁伊在野熊的状态下能施放咆哮技能。", 
            Hotkey="M", base2=0.0, code3="", effect2="", effect3="", race="nightelf", Requires="Redc", code1="", timebase=20, 
            Tip="研究利爪之痕(|cffffcc00M|r)", mod2=0.0, mod4=0.0, mod3=0.0, base4=0.0, code2="", Requiresamount="2", 
            Name="利爪之痕", Art="ReplaceableTextures\\CommandButtons\\BTNEnchantedBears.blp", maxlevel=1, 
            Buttonpos_2=1, base3=0.0, lumberbase=100, 
        },
        Robs={
            goldmod=0, Art="ReplaceableTextures\\CommandButtons\\BTNBerserk.blp", code4="", goldbase=50, effect4="", 
            lumbermod=0, global=0, Buttonpos_2=2, base1=100.0, mod1=0.0, Buttonpos_1=0, inherit=1, 
            Ubertip="能增加兽族步兵<Robs,base1>点的生命值和<Robs,base2>点的攻击力。", 
            Hotkey="B", base2=3.0, code3="", effect2="ratx", effect3="", race="orc", Requires="ostr", code1="", timebase=40, 
            Tip="研究狂暴力量(|cffffcc00B|r)", mod3=0.0, mod4=0.0, base4=0.0, code2="", class="", Name="狂暴力量", 
            mod2=0.0, maxlevel=1, effect1="rhpx", base3=0.0, lumberbase=150, 
        },
        Resw={
            goldmod=75, class="ranged", code4="", Hotkey3="W", effect4="", Name1="野性力量", lumbermod=100, global=0, 
            Buttonpos_2=0, Requires1="", base1=1.0, mod1=1.0, Buttonpos_1=1, 
            Art2="ReplaceableTextures\\CommandButtons\\BTNImprovedStrengthOfTheWild.blp", Hotkey2="W", 
            Art3="ReplaceableTextures\\CommandButtons\\BTNAdvancedStrengthOfTheWild.blp", base2=0.0, code3="", 
            effect2="", Name2="中级野性力量", effect1="ratd", Tip2="升级到中级野性力量(|cffffcc00W|r)", 
            race="nightelf", effect3="", Name3="高级野性力量", mod4=0.0, mod3=0.0, mod2=0.0, maxlevel=3, 
            Ubertip3="进一步增加变熊之后的利爪德鲁伊，变为风暴之鸦之后的猛禽德鲁伊，树妖，角鹰兽，山岭巨人，精灵龙和奇美拉怪兽的攻击力。", 
            code1="", timebase=60, 
            Ubertip1="增加变熊之后的利爪德鲁伊，变为风暴之鸦之后的猛禽德鲁伊，树妖，角鹰兽，山岭巨人，精灵龙和奇美拉怪兽的攻击力。", 
            Tip3="升级到高级野性力量(|cffffcc00W|r)", inherit=0, goldbase=100, 
            Art1="ReplaceableTextures\\CommandButtons\\BTNStrengthOfTheWild.blp", 
            Tip1="升级到野性力量(|cffffcc00W|r)", code2="", 
            Ubertip2="进一步增加变熊之后的利爪德鲁伊，变为风暴之鸦之后的猛禽德鲁伊，树妖，角鹰兽，山岭巨人，精灵龙和奇美拉怪兽的攻击力。", 
            Requires3="etoe", Requires2="etoa", Hotkey1="W", base4=0.0, base3=0.0, lumberbase=75, 
        },
        Repb={
            goldmod=0, Art="ReplaceableTextures\\CommandButtons\\BTNVorpalBlades.blp", code4="", goldbase=125, 
            effect4="", lumbermod=0, global=0, Buttonpos_2=2, base1=200.0, mod1=0.0, Buttonpos_1=2, inherit=1, 
            Ubertip="使得投刃车的攻击能穿透敌人从而对其他站在后面的敌方单位也造成一定伤害。同时也能让投刃车能攻击树木。", 
            Hotkey="P", base2=2.0, code3="", effect2="renw", effect3="", race="nightelf", Requires="etoa,edob", code1="", 
            timebase=60, Tip="研究穿刺剑刃(|cffffcc00P|r)", mod3=0.0, mod4=0.0, base4=0.0, code2="", class="", 
            Name="穿刺剑刃", mod2=0.0, maxlevel=1, effect1="rasd", base3=0.0, lumberbase=100, 
        },
        Rhrt={
            goldmod=0, Art="ReplaceableTextures\\CommandButtons\\BTNScatterRockets.blp", code4="", goldbase=50, 
            effect4="", lumbermod=0, global=1, Buttonpos_2=2, base1=1.0, mod1=0.0, Buttonpos_1=2, inherit=1, 
            Ubertip="升级蒸汽机车，使其拥有弹幕攻击技能，从而可以对敌方的空中单位进行攻击。", 
            Hotkey="G", base2=-1.0, code3="", effect2="rtma", effect3="", race="human", Requires="hcas", code1="hmtt", 
            timebase=40, Tip="研究弹幕攻击(|cffffcc00G|r)", mod3=0.0, mod4=0.0, base4=0.0, code2="hrtt", class="", 
            Name="弹幕攻击", mod2=0.0, maxlevel=1, effect1="rtma", base3=0.0, lumberbase=150, 
        },
        Ruwb={
            goldmod=0, Art="ReplaceableTextures\\CommandButtons\\BTNWeb.blp", code4="", goldbase=75, effect4="", 
            lumbermod=0, global=0, Buttonpos_2=2, base1=0.0, mod1=0.0, Buttonpos_1=1, inherit=1, 
            Ubertip="使得穴居恶魔能将敌人的某个空中单位捕获到地面，从而让己方的地面单位可以对其进行攻击。", 
            Hotkey="W", base2=0.0, code3="", effect2="", effect3="", race="undead", Requires="ugrv,unp1", code1="", timebase=30, 
            Tip="研究蛛网(|cffffcc00W|r)", mod3=0.0, mod4=0.0, base4=0.0, code2="", class="", Name="蛛网", mod2=0.0, 
            maxlevel=1, effect1="", base3=0.0, lumberbase=75, 
        },
        Rhlh={
            goldmod=100, class="", code4="", goldbase=100, effect4="", Name1="改进型伐木效率", lumbermod=0, global=0, 
            Buttonpos_2=0, Requires1="hkee", base1=5.0, mod1=5.0, Buttonpos_1=0, 
            Art2="ReplaceableTextures\\CommandButtons\\BTNHumanLumberUpgrade2.blp", 
            Ubertip2="进一步增加<Rhlh,mod1>点农民每次能携带的木材数量。", base2=0.0, code3="", 
            effect2="", Name2="高级伐木效率", effect3="", Hotkey1="L", Hotkey2="L", mod4=0.0, race="human", code1="", 
            timebase=60, Ubertip1="增加<Rhlh,mod1>点农民每次能携带的木材数量。", mod3=0.0, mod2=0.0, 
            maxlevel=2, Art1="ReplaceableTextures\\CommandButtons\\BTNHumanLumberUpgrade1.blp", 
            Tip1="改进型伐木效率(|cffffcc00L|r)", code2="", inherit=1, base4=0.0, Requires2="hcas", effect1="rlum", 
            Tip2="高级伐木效率(|cffffcc00L|r)", base3=0.0, lumberbase=0, 
        },
        Rupc={
            goldmod=0, Art="ReplaceableTextures\\CommandButtons\\BTNPlagueCloud.blp", code4="", goldbase=100, 
            effect4="", lumbermod=0, global=0, Buttonpos_2=2, base1=0.0, mod1=0.0, Buttonpos_1=1, inherit=1, 
            Ubertip="使得憎恶能带有疾病云雾光环，从而在<Aap1,DataA1>内对周围的单位造成每秒<Aap1,DataB1>点的伤害。而绞肉车的攻击也可以带有疾病效果从而在<Aap2,DataA1>秒内对周围的单位造成每秒<Aap2,DataB1>点的伤害。|n不死族的单位对疾病云雾免疫。", 
            Hotkey="D", base2=0.0, code3="", effect2="", effect3="", race="undead", Requires="unp2", code1="", timebase=45, 
            Tip="研究疾病云雾(|cffffcc00D|r)", mod3=0.0, mod4=0.0, base4=0.0, code2="", class="", Name="疾病云雾", 
            mod2=0.0, maxlevel=1, effect1="", base3=0.0, lumberbase=200, 
        },
        Rguv={
            base2=0.0, code3="", effect2="", goldmod=50, maxlevel=1, class="", mod4=0.0, EditorSuffix=" (升级)", code4="", 
            race="unknown", goldbase=100, effect4="", mod3=0.0, mod2=0.0, mod1=0.0, code1="", timebase=60, lumbermod=50, global=0, 
            effect1="rauv", Art="ReplaceableTextures\\CommandButtons\\BTNGlyph.blp", base1=0.0, base4=0.0, code2="", 
            Buttonpos_1=0, Name="夜视浮雕", inherit=1, effect3="", Buttonpos_2=0, base3=0.0, lumberbase=100, 
        },
        Rhra={
            goldmod=75, class="ranged", code4="", Hotkey3="G", effect4="", Name1="黑火药", lumbermod=125, global=0, 
            Buttonpos_2=0, Requires1="", base1=1.0, mod1=1.0, Buttonpos_1=1, 
            Art2="ReplaceableTextures\\CommandButtons\\BTNHumanMissileUpTwo.blp", Hotkey2="G", 
            Art3="ReplaceableTextures\\CommandButtons\\BTNHumanMissileUpThree.blp", base2=0.0, code3="", effect2="", 
            Name2="精练火药", effect1="ratd", Tip2="升级到精练火药(|cffffcc00G|r)", race="human", effect3="", 
            Name3="终极火药", mod4=0.0, mod3=0.0, mod2=0.0, maxlevel=3, 
            Ubertip3="进一步增加矮人火枪手、迫击炮小队、蒸汽机车和飞行机器的攻击力。", 
            code1="", timebase=60, 
            Ubertip1="增加矮人火枪手、迫击炮小队、蒸汽机车和飞行机器的攻击力。", 
            Tip3="升级到终极火药(|cffffcc00G|r)", inherit=0, goldbase=100, 
            Art1="ReplaceableTextures\\CommandButtons\\BTNHumanMissileUpOne.blp", 
            Tip1="升级到黑火药(|cffffcc00G|r)", code2="", 
            Ubertip2="进一步增加矮人火枪手、迫击炮小队、蒸汽机车和飞行机器的攻击力。", 
            Requires3="hcas", Requires2="hkee", Hotkey1="G", base4=0.0, base3=0.0, lumberbase=50, 
        },
        Ruar={
            goldmod=75, class="armor", code4="", Hotkey3="U", effect4="", Name1="邪恶装甲", lumbermod=100, global=0, 
            Buttonpos_2=1, Requires1="", base1=0.0, mod1=0.0, Buttonpos_1=0, 
            Art2="ReplaceableTextures\\CommandButtons\\BTNImprovedUnholyArmor.blp", Hotkey2="U", 
            Art3="ReplaceableTextures\\CommandButtons\\BTNAdvancedUnholyArmor.blp", base2=0.0, code3="", effect2="", 
            Name2="中级邪恶装甲", effect1="rarm", Tip2="升级到中级邪恶装甲(|cffffcc00U|r)", 
            race="undead", effect3="", Name3="高级邪恶装甲", mod4=0.0, mod3=0.0, mod2=0.0, maxlevel=3, 
            Ubertip3="进一步增加食尸鬼，憎恶，骷髅战士和骷髅魔法师的防御力。", 
            code1="", timebase=60, 
            Ubertip1="增加食尸鬼，憎恶，骷髅战士和骷髅魔法师的防御力。", 
            Tip3="升级到高级邪恶装甲(|cffffcc00U|r)", inherit=0, goldbase=125, 
            Art1="ReplaceableTextures\\CommandButtons\\BTNUnholyArmor.blp", 
            Tip1="升级到邪恶装甲(|cffffcc00U|r)", code2="", 
            Ubertip2="进一步增加食尸鬼，憎恶，骷髅战士和骷髅魔法师的防御力。", 
            Requires3="unp2", Requires2="unp1", Hotkey1="U", base4=0.0, base3=0.0, lumberbase=50, 
        },
        Rerh={
            goldmod=50, class="armor", code4="", Hotkey3="R", effect4="", Name1="加强隐藏", lumbermod=100, global=0, 
            Buttonpos_2=1, Requires1="", base1=0.0, mod1=0.0, Buttonpos_1=1, 
            Art2="ReplaceableTextures\\CommandButtons\\BTNImprovedReinforcedHides.blp", Hotkey2="R", 
            Art3="ReplaceableTextures\\CommandButtons\\BTNAdvancedReinforcedHides.blp", base2=0.0, code3="", 
            effect2="", Name2="中级加强隐藏", effect1="rarm", Tip2="升级到中级加强隐藏(|cffffcc00R|r)", 
            race="nightelf", effect3="", Name3="高级加强隐藏", mod4=0.0, mod3=0.0, mod2=0.0, maxlevel=3, 
            Ubertip3="进一步增加变熊之后的利爪德鲁伊，变为风暴之鸦之后的猛禽德鲁伊，树妖，角鹰兽，山岭巨人，精灵龙和奇美拉怪兽的护甲。", 
            code1="", timebase=60, 
            Ubertip1="增加变熊之后的利爪德鲁伊，变为风暴之鸦之后的猛禽德鲁伊，树妖，角鹰兽，山岭巨人，精灵龙和奇美拉怪兽的护甲。", 
            Tip3="升级到高级加强隐藏(|cffffcc00R|r)", inherit=0, goldbase=150, 
            Art1="ReplaceableTextures\\CommandButtons\\BTNReinforcedHides.blp", 
            Tip1="升级到加强隐藏(|cffffcc00R|r)", code2="", 
            Ubertip2="进一步增加变熊之后的利爪德鲁伊，变为风暴之鸦之后的猛禽德鲁伊，树妖，角鹰兽，山岭巨人，精灵龙和奇美拉怪兽的护甲。", 
            Requires3="etoe", Requires2="etoa", Hotkey1="R", base4=0.0, base3=0.0, lumberbase=50, 
        },
        Rhss={
            goldmod=0, Art="ReplaceableTextures\\CommandButtons\\BTNControlMagic.blp", code4="", goldbase=75, 
            effect4="", lumbermod=0, global=0, Buttonpos_2=1, base1=0.0, mod1=0.0, Buttonpos_1=2, inherit=1, 
            Ubertip="让魔法破坏者可以利用敌人召唤出来的单位。", Hotkey="G", base2=0.0, code3="", 
            effect2="", effect3="", race="human", Requires="hvlt,hcas", code1="", timebase=45, 
            Tip="研究控制魔法(|cffffcc00G|r)", mod3=0.0, mod4=0.0, base4=0.0, code2="", class="", Name="控制魔法", 
            mod2=0.0, maxlevel=1, effect1="", base3=0.0, lumberbase=75, 
        },
        Rehs={
            goldmod=0, Art="ReplaceableTextures\\CommandButtons\\BTNHardenedSkin.blp", code4="", goldbase=100, 
            effect4="", lumbermod=0, global=0, Buttonpos_2=1, base1=0.0, mod1=0.0, Buttonpos_1=2, inherit=1, 
            Ubertip="让山岭巨人增加对攻击伤害的抵抗力。", Hotkey="H", base2=0.0, code3="", effect2="", 
            effect3="", race="nightelf", Requires="etoe,eden", code1="", timebase=40, 
            Tip="研究硬化皮肤(|cffffcc00H|r)", mod3=0.0, mod4=0.0, base4=0.0, code2="", class="", Name="硬化皮肤", 
            mod2=0.0, maxlevel=1, effect1="", base3=0.0, lumberbase=250, 
        },
        Rhac={
            goldmod=25, class="armor", code4="", Hotkey3="M", effect4="", Name1="加强型石工技术", lumbermod=75, 
            global=0, Buttonpos_2=0, Requires1="", base1=0.0, mod1=0.0, Buttonpos_1=1, 
            Art2="ReplaceableTextures\\CommandButtons\\BTNArcaniteArchitecture.blp", Hotkey2="M", 
            Art3="ReplaceableTextures\\CommandButtons\\BTNImbuedMasonry.blp", base2=0.2, code3="", effect2="rhpo", 
            Name2="高级石工技术", effect1="rarm", Tip2="升级到高级石工技术(|cffffcc00M|r)", 
            race="human", effect3="", Name3="终极石工技术", mod4=0.0, mod3=0.0, mod2=0.2, maxlevel=3, 
            Ubertip3="进一步增加人族建筑物的生命值和护甲。", code1="", timebase=60, 
            Ubertip1="增加人族建筑物的生命值和护甲。", 
            Tip3="升级到终极石工技术(|cffffcc00M|r)", inherit=0, goldbase=100, 
            Art1="ReplaceableTextures\\CommandButtons\\BTNStoneArchitecture.blp", 
            Tip1="升级到加强型石工技术(|cffffcc00M|r)", code2="", 
            Ubertip2="进一步增加人族建筑物的生命值和护甲。", Requires3="hcas", Requires2="hkee", 
            Hotkey1="M", base4=0.0, base3=0.0, lumberbase=100, 
        },
        Rhla={
            goldmod=50, class="armor", code4="", Hotkey3="A", effect4="", Name1="镶皮甲", lumbermod=75, global=0, 
            Buttonpos_2=1, Requires1="", base1=0.0, mod1=0.0, Buttonpos_1=1, 
            Art2="ReplaceableTextures\\CommandButtons\\BTNLeatherUpgradeTwo.blp", Hotkey2="A", 
            Art3="ReplaceableTextures\\CommandButtons\\BTNLeatherUpgradeThree.blp", base2=0.0, code3="", effect2="", 
            Name2="加强型镶皮甲", effect1="rarm", Tip2="升级到加强型镶皮甲(|cffffcc00A|r)", 
            race="human", effect3="", Name3="龙甲", mod4=0.0, mod3=0.0, mod2=0.0, maxlevel=3, 
            Ubertip3="进一步增加矮人火枪手、迫击炮小队、龙鹰骑士和狮鹫骑士的护甲。", 
            code1="", timebase=60, 
            Ubertip1="增加矮人火枪手、迫击炮小队、龙鹰骑士和狮鹫骑士的护甲。", 
            Tip3="升级到龙甲(|cffffcc00A|r)", inherit=0, goldbase=100, 
            Art1="ReplaceableTextures\\CommandButtons\\BTNLeatherUpgradeOne.blp", 
            Tip1="升级到镶皮甲(|cffffcc00A|r)", code2="", 
            Ubertip2="进一步增加矮人火枪手、迫击炮小队、龙鹰骑士和狮鹫骑士的护甲。", 
            Requires3="hcas", Requires2="hkee", Hotkey1="A", base4=0.0, base3=0.0, lumberbase=100, 
        },
        Ruba={
            goldmod=0, class="caster", code4="", goldbase=100, effect4="ratd", Name1="女妖专家训练", lumbermod=100, 
            global=0, Buttonpos_2=2, Requires1="", base1=100.0, mod1=100.0, Buttonpos_1=1, 
            Art2="ReplaceableTextures\\CommandButtons\\BTNBansheeMaster.blp", 
            Ubertip2="增加女妖的魔法最大值，魔法恢复速度，生命值和攻击力。并使其具有占据技能。", 
            base2=0.325, code3="", effect2="rmnr", Name2="女妖大师训练", effect3="rhpx", Hotkey1="A", Hotkey2="A", 
            mod4=0.0, race="undead", code1="", timebase=60, 
            Ubertip1="增加女妖的魔法最大值，魔法恢复速度，生命值和攻击力。并使其具有反魔法外壳技能。", 
            mod3=40.0, mod2=0.325, maxlevel=2, Art1="ReplaceableTextures\\CommandButtons\\BTNBansheeAdept.blp", 
            Tip1="女妖专家训练(|cffffcc00A|r)", code2="", inherit=1, base4=0.0, Requires2="unp2", effect1="rmnx", 
            Tip2="女妖大师训练(|cffffcc00A|r)", base3=40.0, lumberbase=50, 
        },
        Roen={
            goldmod=0, Art="ReplaceableTextures\\CommandButtons\\BTNEnsnare.blp", code4="", goldbase=50, maxlevel=1, 
            lumbermod=0, global=0, Buttonpos_2=2, base1=0.0, mod1=0.0, Buttonpos_1=0, inherit=1, 
            Ubertip="使得掠夺者能将目标空中单位困在地面上而不能移动。", Hotkey="N", 
            base2=0.0, code3="", effect2="", effect3="", race="orc", code1="", timebase=40, Tip="诱捕(|cffffcc00N|r)", 
            class="", mod4=0.0, base4=0.0, code2="", mod3=0.0, Name="诱捕", mod2=0.0, effect4="", effect1="", base3=0.0, 
            lumberbase=75, 
        },
        Reib={
            goldmod=0, Art="ReplaceableTextures\\CommandButtons\\BTNImprovedBows.blp", code4="", goldbase=50, 
            effect4="", lumbermod=0, global=0, Buttonpos_2=1, base1=200.0, mod1=200.0, Buttonpos_1=0, inherit=1, 
            Ubertip="增加弓箭手和角鹰兽骑士的攻击范围。", Hotkey="I", base2=0.0, code3="", effect2="", 
            effect3="", race="nightelf", Requires="etoa", code1="", timebase=35, Tip="研究硬弓(|cffffcc00I|r)", 
            mod3=0.0, mod4=0.0, base4=0.0, code2="", class="", Name="硬弓", mod2=0.0, maxlevel=1, effect1="ratr", base3=0.0, 
            lumberbase=100, 
        },
        Rhan={
            goldmod=0, Art="ReplaceableTextures\\CommandButtons\\BTNAnimalWarTraining.blp", code4="", goldbase=150, 
            effect4="", lumbermod=0, global=0, Buttonpos_2=2, base1=150.0, mod1=0.0, Buttonpos_1=2, inherit=1, 
            Ubertip="能增加骑士、龙鹰骑士和狮鹫骑士<Rhan,base1>点的生命值。", Hotkey="A", 
            base2=0.0, code3="", effect2="", effect3="", race="human", Requires="hlum,hcas,hbla", code1="", timebase=40, 
            Tip="研究动物作战训练(|cffffcc00A|r)", mod3=0.0, mod4=0.0, base4=0.0, code2="", class="", 
            Name="动物作战训练", mod2=0.0, maxlevel=1, effect1="rhpx", base3=0.0, lumberbase=250, 
        },
        Repm={
            goldmod=0, Art="ReplaceableTextures\\CommandButtons\\BTNPackBeast.blp", code4="", goldbase=50, effect4="", 
            lumbermod=0, global=0, Buttonpos_2=0, base1=0.0, mod1=0.0, Buttonpos_1=3, inherit=0, 
            Ubertip="给予指定的暗夜精灵地面单位携带物品的能力。", Hotkey="B", base2=0.0, 
            code3="", effect2="", EditorSuffix=" (暗夜精灵族)", effect3="", race="nightelf", Requires="eden", code1="", 
            timebase=20, Tip="研究背包技能(|cffffcc00B|r)", mod3=0.0, mod4=0.0, base4=0.0, code2="", mod2=0.0, 
            Name="背包技能", class="", maxlevel=1, effect1="", base3=0.0, lumberbase=25, 
        },
        Rufb={
            goldmod=0, Art="ReplaceableTextures\\CommandButtons\\BTNFreezingBreath.blp", code4="", goldbase=150, 
            maxlevel=1, lumbermod=0, global=0, Buttonpos_2=2, base1=0.0, mod1=0.0, Buttonpos_1=0, inherit=1, 
            Ubertip="使得霜冻巨龙的攻击能在一段时间内使受攻击的建筑物暂时失去功效。", 
            Hotkey="B", base2=0.0, code3="", effect2="", effect3="", race="undead", code1="", timebase=60, 
            Tip="研究冰冻喷吐(|cffffcc00B|r)", class="", mod4=0.0, base4=0.0, code2="", mod3=0.0, Name="冰冻喷吐", 
            mod2=0.0, effect4="", effect1="", base3=0.0, lumberbase=275, 
        },
        Rusl={
            goldmod=0, Art="ReplaceableTextures\\CommandButtons\\BTNSkeletalLongevity.blp", code4="", goldbase=100, 
            maxlevel=1, lumbermod=0, global=0, Buttonpos_2=2, base1=15.0, mod1=0.0, Buttonpos_1=2, inherit=1, 
            Ubertip="能增加召唤出来的骷髅战士的持续时间<Rusl,base1>秒。", Hotkey="S", base2=0.0, 
            code3="", effect2="", effect3="", race="undead", code1="", timebase=60, 
            Tip="研究骨质增强术(|cffffcc00S|r)", class="", mod4=0.0, base4=0.0, code2="", mod3=0.0, 
            Name="骨质增强术", mod2=0.0, effect4="", effect1="rrai", base3=0.0, lumberbase=75, 
        },
        Rhfs={
            goldmod=0, Art="ReplaceableTextures\\CommandButtons\\BTNFragmentationBombs.blp", code4="", goldbase=50, 
            effect4="", lumbermod=0, global=0, Buttonpos_2=1, base1=0.0, mod1=0.0, Buttonpos_1=1, inherit=1, 
            Ubertip="升级迫击炮炮弹，增加迫击炮小队对无护甲和中型护甲单位的伤害。", 
            Hotkey="S", base2=0.0, code3="", effect2="", effect3="", race="human", Requires="hcas", code1="", timebase=40, 
            Tip="研究碎片攻击(|cffffcc00S|r)", mod3=0.0, mod4=0.0, base4=0.0, code2="", class="", Name="碎片攻击", 
            mod2=0.0, maxlevel=1, effect1="", base3=0.0, lumberbase=100, 
        },
        Rhgb={
            goldmod=50, Art="ReplaceableTextures\\CommandButtons\\BTNHumanArtilleryUpOne.blp", code4="", goldbase=150, 
            effect4="", lumbermod=0, global=0, Buttonpos_2=2, base1=3.0, mod1=0.0, Buttonpos_1=0, inherit=1, 
            Ubertip="使得飞行机器能攻击地面单位。", Hotkey="B", base2=0.0, code3="", effect2="", effect3="", 
            race="human", Requires="hcas", code1="", timebase=35, Tip="研究飞行机器炸弹(|cffffcc00B|r)", mod3=0.0, 
            mod4=0.0, base4=0.0, code2="", class="", Name="飞行机器炸弹", mod2=0.0, maxlevel=1, effect1="renw", base3=0.0, 
            lumberbase=100, 
        },
        Rema={
            goldmod=50, class="armor", code4="", Hotkey3="A", effect4="", Name1="月之护甲", lumbermod=75, global=0, 
            Buttonpos_2=1, Requires1="", base1=0.0, mod1=0.0, Buttonpos_1=0, 
            Art2="ReplaceableTextures\\CommandButtons\\BTNImprovedMoonArmor.blp", Hotkey2="A", 
            Art3="ReplaceableTextures\\CommandButtons\\BTNAdvancedMoonArmor.blp", base2=0.0, code3="", effect2="", 
            Name2="中级月之护甲", effect1="rarm", Tip2="升级到中级月之护甲(|cffffcc00A|r)", 
            race="nightelf", effect3="", Name3="高级月之护甲", mod4=0.0, mod3=0.0, mod2=0.0, maxlevel=3, 
            Ubertip3="进一步增加弓箭手，女猎手和角鹰兽骑士的防御力。", code1="", timebase=60, 
            Ubertip1="增加弓箭手，女猎手和角鹰兽骑士的防御力。", 
            Tip3="升级到高级月之护甲(|cffffcc00A|r)", inherit=0, goldbase=150, 
            Art1="ReplaceableTextures\\CommandButtons\\BTNMoonArmor.blp", 
            Tip1="升级到月之护甲(|cffffcc00A|r)", code2="", 
            Ubertip2="进一步增加弓箭手，女猎手和角鹰兽骑士的防御力。", Requires3="etoe", 
            Requires2="etoa", Hotkey1="A", base4=0.0, base3=0.0, lumberbase=75, 
        },
        Rusm={
            goldmod=0, Art="ReplaceableTextures\\CommandButtons\\BTNSkeletonMage.blp", code4="", goldbase=125, 
            effect4="", lumbermod=0, global=0, Buttonpos_2=1, base1=1.0, mod1=1.0, Buttonpos_1=2, inherit=1, 
            Ubertip="让复活死尸技能召唤出来的两个骷髅中的一个成为骷髅魔法师。", 
            Hotkey="M", base2=0.0, code3="", effect2="", effect3="", race="undead", Requires="unp2", code1="Arai", timebase=45, 
            Tip="研究骷髅法术(|cffffcc00M|r)", mod3=0.0, mod4=0.0, base4=0.0, code2="", class="", Name="骷髅法术", 
            mod2=0.0, maxlevel=1, effect1="rlev", base3=0.0, lumberbase=150, 
        },
        Redc={
            goldmod=0, class="caster", code4="", goldbase=100, effect4="ratd", Name1="利爪德鲁伊专家训练", 
            lumbermod=100, global=0, Buttonpos_2=2, Requires1="", base1=100.0, mod1=100.0, Buttonpos_1=1, 
            Art2="ReplaceableTextures\\CommandButtons\\BTNDOCMasterTraining.blp", 
            Ubertip2="增加利爪德鲁伊暗夜精灵状态下的魔法最大值，魔法恢复速度，生命值和攻击力。并使其拥有变熊技能。", 
            base2=0.325, code3="", effect2="rmnr", Name2="利爪德鲁伊大师训练", effect3="rhpx", Hotkey1="L", 
            Hotkey2="L", mod4=1.0, race="nightelf", code1="", timebase=45, 
            Ubertip1="增加利爪德鲁伊暗夜精灵状态下的魔法最大值，魔法恢复速度，生命值和攻击力。并使其拥有生命恢复技能。", 
            mod3=75.0, mod2=0.325, maxlevel=2, Art1="ReplaceableTextures\\CommandButtons\\BTNDOCAdeptTraining.blp", 
            Tip1="利爪德鲁伊专家训练(|cffffcc00L|r)", code2="", inherit=1, base4=1.0, Requires2="etoe", 
            effect1="rmnx", Tip2=" 利爪德鲁伊大师训练(|cffffcc00L|r)", base3=75.0, lumberbase=50, 
        },
        Rhfl={
            goldmod=0, Art="ReplaceableTextures\\CommandButtons\\BTNFlare.blp", code4="", goldbase=50, effect4="", 
            lumbermod=0, global=0, Buttonpos_2=2, base1=0.0, mod1=0.0, Buttonpos_1=1, inherit=1, 
            Ubertip="让每个迫击炮小队拥有一个照明弹,照明弹能驱散地图中任何一个区域内的战争迷雾。|n能探测到隐形单位。", 
            Hotkey="R", base2=0.0, code3="", effect2="", effect3="", race="human", Requires="hkee", code1="", timebase=30, 
            Tip="研究照明弹(|cffffcc00R|r)", mod3=0.0, mod4=0.0, base4=0.0, code2="", class="", Name="照明弹", 
            mod2=0.0, maxlevel=1, effect1="", base3=0.0, lumberbase=50, 
        },
        Rhhb={
            goldmod=0, Art="ReplaceableTextures\\CommandButtons\\BTNStormHammer.blp", code4="", goldbase=125, 
            maxlevel=1, lumbermod=0, global=0, Buttonpos_2=2, base1=200.0, mod1=0.0, Buttonpos_1=0, inherit=1, 
            Ubertip="让狮鹫骑士的战锤能进行弹射，从而对多个敌人造成伤害。", Hotkey="H", 
            base2=0.0, code3="", effect2="", effect3="", race="human", code1="", timebase=45, 
            Tip="研究风暴战锤(|cffffcc00H|r)", class="", mod4=0.0, base4=0.0, code2="", mod3=0.0, Name="风暴战锤", 
            mod2=0.0, effect4="", effect1="rasd", base3=0.0, lumberbase=225, 
        },
        Recb={
            goldmod=0, Art="ReplaceableTextures\\CommandButtons\\BTNCorrosiveBreath.blp", code4="", goldbase=125, 
            maxlevel=1, lumbermod=0, global=0, Buttonpos_2=2, base1=3.0, mod1=0.0, Buttonpos_1=0, inherit=1, 
            Ubertip="使得奇美拉怪兽能对敌方的建筑物喷出酸性的毒汁。", Hotkey="B", base2=0.0, 
            code3="", effect2="", effect3="", race="nightelf", code1="", timebase=40, 
            Tip="研究腐蚀喷吐(|cffffcc00B|r)", class="", mod4=0.0, base4=0.0, code2="", mod3=0.0, Name="腐蚀喷吐", 
            mod2=0.0, effect4="", effect1="renw", base3=0.0, lumberbase=225, 
        },
        Rhse={
            goldmod=0, Art="ReplaceableTextures\\CommandButtons\\BTNMagicalSentry.blp", code4="", goldbase=50, 
            maxlevel=1, lumbermod=0, global=0, Buttonpos_2=2, base1=0.0, mod1=0.0, Buttonpos_1=2, inherit=0, 
            Ubertip="让人族的各类塔能探测到隐形单位。", Hotkey="M", base2=0.0, code3="", effect2="", 
            effect3="", race="human", code1="", timebase=30, Tip="研究魔法岗哨(|cffffcc00M|r)", class="", mod4=0.0, 
            base4=0.0, code2="", mod3=0.0, Name="魔法岗哨", mod2=0.0, effect4="", effect1="", base3=0.0, lumberbase=50, 
        },
        Rolf={
            goldmod=0, Art="ReplaceableTextures\\CommandButtons\\BTNLiquidFire.blp", code4="", goldbase=75, effect4="", 
            lumbermod=0, global=0, Buttonpos_2=2, base1=0.0, mod1=0.0, Buttonpos_1=2, inherit=1, 
            Ubertip="让巨魔蝙蝠骑士具有液体炸弹技能，从而可以对敌人的建筑物造成持续性的伤害，被液体炸弹攻击到的各类防御塔都会被减慢攻击速度。", 
            Hotkey="L", base2=0.0, code3="", effect2="", effect3="", race="orc", Requires="ofrt,ovln", code1="", timebase=75, 
            Tip="研究液体炸弹(|cffffcc00L|r)", mod3=0.0, mod4=0.0, base4=0.0, code2="", class="", Name="液体炸弹", 
            mod2=0.0, maxlevel=1, effect1="", base3=0.0, lumberbase=125, 
        },
        Resm={
            goldmod=50, class="melee", code4="", Hotkey3="M", effect4="", Name1="月之力量", lumbermod=100, global=0, 
            Buttonpos_2=0, Requires1="", base1=1.0, mod1=1.0, Buttonpos_1=0, 
            Art2="ReplaceableTextures\\CommandButtons\\BTNImprovedStrengthOfTheMoon.blp", Hotkey2="M", 
            Art3="ReplaceableTextures\\CommandButtons\\BTNAdvancedStrengthOfTheMoon.blp", base2=0.0, code3="", 
            effect2="", Name2="中级月之力量", effect1="ratd", Tip2="升级到中级月之力量(|cffffcc00M|r)", 
            race="nightelf", effect3="", Name3="高级月之力量", mod4=0.0, mod3=0.0, mod2=0.0, maxlevel=3, 
            Ubertip3="进一步增加弓箭手，女猎手，投刃车和角鹰兽骑士的攻击力。", 
            code1="", timebase=60, 
            Ubertip1="增加弓箭手，女猎手，投刃车和角鹰兽骑士的攻击力。", 
            Tip3="升级到高级月之力量(|cffffcc00M|r)", inherit=0, goldbase=125, 
            Art1="ReplaceableTextures\\CommandButtons\\BTNStrengthOfTheMoon.blp", 
            Tip1="升级到月之力量(|cffffcc00M|r)", code2="", 
            Ubertip2="进一步增加弓箭手，女猎手，投刃车和角鹰兽骑士的攻击力。", 
            Requires3="etoe", Requires2="etoa", Hotkey1="M", base4=0.0, base3=0.0, lumberbase=75, 
        },
        Rhpm={
            goldmod=0, Art="ReplaceableTextures\\CommandButtons\\BTNPackBeast.blp", code4="", goldbase=50, effect4="", 
            lumbermod=0, global=0, Buttonpos_2=0, base1=0.0, mod1=0.0, Buttonpos_1=3, inherit=0, 
            Ubertip="给人族地面部队携带物品的能力。", Hotkey="B", base2=0.0, code3="", effect2="", 
            EditorSuffix=" (人族)", effect3="", race="human", Requires="hvlt", code1="", timebase=20, 
            Tip="研究背包技能(|cffffcc00B|r)", mod3=0.0, mod4=0.0, base4=0.0, code2="", mod2=0.0, Name="背包技能", 
            class="", maxlevel=1, effect1="", base3=0.0, lumberbase=25, 
        },
        Rune={
            goldmod=0, class="caster", code4="", goldbase=100, effect4="ratd", Name1="不死族巫师专家训练", 
            lumbermod=100, global=0, Buttonpos_2=2, Requires1="", base1=100.0, mod1=100.0, Buttonpos_1=0, 
            Art2="ReplaceableTextures\\CommandButtons\\BTNNecromancerMaster.blp", 
            Ubertip2="增加不死族巫师的魔法最大值，魔法恢复速度，生命值和攻击力。并使其具有残废技能。", 
            base2=0.325, code3="", effect2="rmnr", Name2="不死族巫师大师训练", effect3="rhpx", Hotkey1="E", 
            Hotkey2="E", mod4=0.0, race="undead", code1="", timebase=60, 
            Ubertip1="增加不死族巫师的魔法最大值，魔法恢复速度，生命值和攻击力。并使其具有邪恶狂热技能。", 
            mod3=40.0, mod2=0.325, maxlevel=2, Art1="ReplaceableTextures\\CommandButtons\\BTNNecromancerAdept.blp", 
            Tip1="不死族巫师专家训练(|cffffcc00E|r)", code2="", inherit=1, base4=0.0, Requires2="unp2", 
            effect1="rmnx", Tip2="不死族巫师大师训练(|cffffcc00E|r)", base3=40.0, lumberbase=50, 
        },
        Rhpt={
            goldmod=0, class="caster", code4="", goldbase=100, effect4="ratd", Name1="牧师专家训练", lumbermod=100, 
            global=0, Buttonpos_2=2, Requires1="", base1=100.0, mod1=100.0, Buttonpos_1=1, 
            Art2="ReplaceableTextures\\CommandButtons\\BTNPriestMaster.blp", 
            Ubertip2="增加牧师的魔法值、魔法恢复速度、生命值、攻击力，还能使其拥有心灵之火技能。", 
            base2=0.325, code3="", effect2="rmnr", Name2="牧师大师训练", effect3="rhpx", Hotkey1="T", Hotkey2="T", 
            mod4=0.0, race="human", code1="", timebase=60, 
            Ubertip1="增加牧师的魔法值、魔法恢复速度、生命值、攻击力，还能使其拥有驱逐魔法技能。", 
            mod3=40.0, mod2=0.325, maxlevel=2, Art1="ReplaceableTextures\\CommandButtons\\BTNPriestAdept.blp", 
            Tip1="牧师专家训练(|cffffcc00T|r)", code2="", inherit=1, base4=0.0, Requires2="hcas", effect1="rmnx", 
            Tip2="牧师大师训练(|cffffcc00T|r)", base3=40.0, lumberbase=50, 
        },
        Rume={
            goldmod=75, class="melee", code4="", Hotkey3="S", effect4="", Name1="邪恶力量", lumbermod=100, global=0, 
            Buttonpos_2=0, Requires1="", base1=1.0, mod1=1.0, Buttonpos_1=0, 
            Art2="ReplaceableTextures\\CommandButtons\\BTNImprovedUnholyStrength.blp", Hotkey2="S", 
            Art3="ReplaceableTextures\\CommandButtons\\BTNAdvancedUnholyStrength.blp", base2=0.0, code3="", 
            effect2="", Name2="中级邪恶力量", effect1="ratd", Tip2="升级到中级邪恶力量(|cffffcc00S|r)", 
            race="undead", effect3="", Name3="高级邪恶力量", mod4=0.0, mod3=0.0, mod2=0.0, maxlevel=3, 
            Ubertip3="进一步增加食尸鬼，绞肉车，憎恶，骷髅战士和骷髅魔法师的攻击力。", 
            code1="", timebase=60, 
            Ubertip1="增加食尸鬼，绞肉车，憎恶，骷髅战士和骷髅魔法师的攻击力。", 
            Tip3="升级到高级邪恶力量(|cffffcc00S|r)", inherit=0, goldbase=125, 
            Art1="ReplaceableTextures\\CommandButtons\\BTNUnholyStrength.blp", 
            Tip1="升级到邪恶力量(|cffffcc00S|r)", code2="", 
            Ubertip2="进一步增加食尸鬼，绞肉车，憎恶，骷髅战士和骷髅魔法师的攻击力。", 
            Requires3="unp2", Requires2="unp1", Hotkey1="S", base4=0.0, base3=0.0, lumberbase=50, 
        },
        Rusp={
            goldmod=0, Art="ReplaceableTextures\\CommandButtons\\BTNDestroyer.blp", code4="", goldbase=75, effect4="", 
            lumbermod=0, global=0, Buttonpos_2=2, base1=0.0, mod1=0.0, Buttonpos_1=2, inherit=1, 
            Ubertip="让十胜石雕像能变成破坏者，一种必须吞噬其他单位的魔法能量来维持自己的魔法能量的大型飞行单位。破坏者具有吞噬魔法，吸收魔法，魔法免疫和毁灭之球技能。|n|n|cffffcc00能攻击地面和空中单位。|r", 
            Hotkey="X", base2=0.0, code3="", effect2="", effect3="", race="undead", Requires="unp2,utom", code1="", timebase=60, 
            Tip="研究破坏者形态(|cffffcc00X|r)", mod3=0.0, mod4=0.0, base4=0.0, code2="", class="", 
            Name="破坏者形态", mod2=0.0, maxlevel=1, effect1="", base3=0.0, lumberbase=150, 
        },
        Rusf={
            goldmod=0, Art="ReplaceableTextures\\CommandButtons\\BTNStoneForm.blp", code4="", goldbase=75, effect4="", 
            lumbermod=0, global=0, Buttonpos_2=2, base1=0.0, mod1=0.0, Buttonpos_1=2, inherit=1, 
            Ubertip="石像形态技能能使石像鬼变成一座具有极高护甲，魔法免疫，生命值恢复加快的雕像。在这期间石像鬼也不能攻击任何敌人。", 
            Hotkey="S", base2=0.0, code3="", effect2="", effect3="", race="undead", Requires="ugrv,unp2", code1="", timebase=40, 
            Tip="研究石像形态(|cffffcc00S|r)", mod3=0.0, mod4=0.0, base4=0.0, code2="", class="", Name="石像形态", 
            mod2=0.0, maxlevel=1, effect1="", base3=0.0, lumberbase=150, 
        },
        Rura={
            goldmod=50, class="ranged", code4="", Hotkey3="A", effect4="", Name1="生物攻击", lumbermod=75, global=0, 
            Buttonpos_2=0, Requires1="", base1=1.0, mod1=1.0, Buttonpos_1=1, 
            Art2="ReplaceableTextures\\CommandButtons\\BTNImprovedCreatureAttack.blp", Hotkey2="A", 
            Art3="ReplaceableTextures\\CommandButtons\\BTNAdvancedCreatureAttack.blp", base2=0.0, code3="", 
            effect2="", Name2="中级生物攻击", effect1="ratd", Tip2="升级到中级生物攻击(|cffffcc00A|r)", 
            race="undead", effect3="", Name3="高级生物攻击", mod4=0.0, mod3=0.0, mod2=0.0, maxlevel=3, 
            Ubertip3="进一步增加穴居恶魔、石像鬼、冰霜巨龙和破坏者的攻击力。", 
            code1="", timebase=60, 
            Ubertip1="增加穴居恶魔、石像鬼、冰霜巨龙和破坏者的攻击力。", 
            Tip3="升级到高级生物攻击(|cffffcc00A|r)", inherit=0, goldbase=150, 
            Art1="ReplaceableTextures\\CommandButtons\\BTNCreatureAttack.blp", 
            Tip1="升级到生物攻击(|cffffcc00A|r)", code2="", 
            Ubertip2="进一步增加穴居恶魔、石像鬼、冰霜巨龙和破坏者的攻击力。", 
            Requires3="unp2", Requires2="unp1", Hotkey1="A", base4=0.0, base3=0.0, lumberbase=50, 
        },
        Rupm={
            goldmod=0, Art="ReplaceableTextures\\CommandButtons\\BTNPackBeast.blp", code4="", goldbase=50, effect4="", 
            lumbermod=0, global=0, Buttonpos_2=0, base1=0.0, mod1=0.0, Buttonpos_1=3, inherit=0, 
            Ubertip="给予指定的不死族地面单位携带物品的能力。", Hotkey="B", base2=0.0, code3="", 
            effect2="", EditorSuffix=" (不死族)", effect3="", race="undead", Requires="utom", code1="", timebase=20, 
            Tip="研究背包技能(|cffffcc00B|r)", mod3=0.0, mod4=0.0, base4=0.0, code2="", mod2=0.0, Name="背包技能", 
            class="", maxlevel=1, effect1="", base3=0.0, lumberbase=25, 
        },
        Rnen={
            goldmod=0, Art="ReplaceableTextures\\CommandButtons\\BTNEnsnare.blp", code4="", goldbase=50, maxlevel=1, 
            lumbermod=0, global=0, Buttonpos_2=2, base1=0.0, mod1=0.0, Buttonpos_1=0, inherit=1, 
            Ubertip="使娜迦暴徒能够使用诱捕技能。能将一个目标空中单位固定在地面上，使其不能移动。被诱捕的空中单位可以当作地面单位进行攻击。", 
            Hotkey="N", base2=0.0, code3="", effect2="", effect3="", race="naga", code1="", timebase=40, 
            Tip="研究诱捕(|cffffcc00N|r)", class="", mod4=0.0, base4=0.0, code2="", mod3=0.0, Name="诱捕", mod2=0.0, 
            effect4="", effect1="", base3=0.0, lumberbase=75, 
        },
        Rhst={
            goldmod=0, class="caster", code4="", goldbase=100, effect4="ratd", Name1="女巫专家训练", lumbermod=100, 
            global=0, Buttonpos_2=2, Requires1="", base1=100.0, mod1=100.0, Buttonpos_1=0, 
            Art2="ReplaceableTextures\\CommandButtons\\BTNSorceressMaster.blp", 
            Ubertip2="增加牧师的魔法值、魔法恢复速度、生命值、攻击力，还能使其拥有变形技能。", 
            base2=0.325, code3="", effect2="rmnr", Name2="女巫大师训练", effect3="rhpx", Hotkey1="O", Hotkey2="O", 
            mod4=0.0, race="human", code1="", timebase=60, 
            Ubertip1="增加牧师的魔法值、魔法恢复速度、生命值、攻击力，还能使其拥有隐形技能。", 
            mod3=40.0, mod2=0.325, maxlevel=2, Art1="ReplaceableTextures\\CommandButtons\\BTNSorceressAdept.blp", 
            Tip1="女巫专家训练(|cffffcc00O|r)", code2="", inherit=1, base4=0.0, Requires2="hcas", effect1="rmnx", 
            Tip2="女巫大师训练(|cffffcc00O|r)", base3=40.0, lumberbase=50, 
        },
        Rwdm={
            goldmod=0, Art="ReplaceableTextures\\CommandButtons\\BTNDrum.blp", code4="", goldbase=100, effect4="", 
            lumbermod=0, global=0, Buttonpos_2=2, base1=0.1, mod1=0.1, Buttonpos_1=1, inherit=1, 
            Ubertip="经过升级以后，科多兽的战鼓光环能给予周围的单位更多的攻击力附加值。", 
            Hotkey="D", base2=0.0, code3="", effect2="", effect3="", race="orc", Requires="ofrt,ofor", code1="Aakb", 
            timebase=40, Tip="升级战鼓(|cffffcc00D|r)", mod3=0.0, mod4=0.0, base4=0.0, code2="", timemod=0, class="", 
            Name="战鼓攻击力升级", mod2=0.0, maxlevel=1, effect1="raud", base3=0.0, lumberbase=150, 
        },
        Rost={
            goldmod=0, class="caster", code4="", goldbase=100, effect4="ratd", Name1="萨满祭司专家训练", 
            lumbermod=100, global=0, Buttonpos_2=2, Requires1="", base1=100.0, mod1=100.0, Buttonpos_1=0, 
            Art2="ReplaceableTextures\\CommandButtons\\BTNShamanMaster.blp", 
            Ubertip2="增加萨满祭司的魔法最大值，魔法恢复速度，生命值和攻击力。还能使其获得嗜血术。", 
            base2=0.325, code3="", effect2="rmnr", Name2="萨满祭司大师训练", effect3="rhpx", Hotkey1="M", 
            Hotkey2="M", mod4=0.0, race="orc", code1="", timebase=60, 
            Ubertip1="增加萨满祭司的魔法最大值，魔法恢复速度，生命值和攻击力。还能使其获得闪电护盾技能。", 
            mod3=40.0, mod2=0.325, maxlevel=2, Art1="ReplaceableTextures\\CommandButtons\\BTNShamanAdept.blp", 
            Tip1="萨满祭司专家训练(|cffffcc00M|r)", code2="", inherit=1, base4=0.0, Requires2="ofrt", 
            effect1="rmnx", Tip2=" 萨满祭司大师训练(|cffffcc00M|r)", base3=40.0, lumberbase=50, 
        },
        Rucr={
            goldmod=50, class="armor", code4="", Hotkey3="C", effect4="", Name1="生物甲壳", lumbermod=125, global=0, 
            Buttonpos_2=1, Requires1="", base1=0.0, mod1=0.0, Buttonpos_1=1, 
            Art2="ReplaceableTextures\\CommandButtons\\BTNImprovedCreatureCarapace.blp", Hotkey2="C", 
            Art3="ReplaceableTextures\\CommandButtons\\BTNAdvancedCreatureCarapace.blp", base2=0.0, code3="", 
            effect2="", Name2="中级生物甲壳", effect1="rarm", Tip2="升级到中级生物甲壳(|cffffcc00C|r)", 
            race="undead", effect3="", Name3="高级生物甲壳", mod4=0.0, mod3=0.0, mod2=0.0, maxlevel=3, 
            Ubertip3="进一步增加地穴恶魔、石像鬼、冰霜巨龙和破坏者的护甲。", code1="", 
            timebase=60, Ubertip1="增加地穴恶魔、石像鬼、 冰霜巨龙和破坏者的护甲。 ", 
            Tip3="升级到生物甲壳(|cffffcc00C|r)", inherit=0, goldbase=150, 
            Art1="ReplaceableTextures\\CommandButtons\\BTNCreatureCarapace.blp", 
            Tip1="升级到生物甲壳(|cffffcc00C|r)", code2="", 
            Ubertip2="进一步增加地穴恶魔、石像鬼、冰霜巨龙和破坏者的护甲。 ", 
            Requires3="unp2", Requires2="unp1", Hotkey1="C", base4=0.0, base3=0.0, lumberbase=75, 
        },
        Rubu={
            goldmod=0, Art="ReplaceableTextures\\CommandButtons\\BTNCryptFiendBurrow.blp", code4="", goldbase=75, 
            effect4="", lumbermod=0, global=0, Buttonpos_2=1, base1=0.0, mod1=0.0, Buttonpos_1=1, inherit=1, 
            Ubertip="让穴居恶魔具有钻地技能。钻地的穴居恶魔是隐形的，并获得提升的生命恢复速度，但不可攻击。", 
            Hotkey="B", base2=0.0, code3="", effect2="", effect3="", race="undead", Requires="unp1,ugrv", code1="", timebase=45, 
            Tip="研究钻地(|cffffcc00B|r)", mod3=0.0, mod4=0.0, base4=0.0, code2="", class="", Name="钻地", mod2=0.0, 
            maxlevel=1, effect1="", base3=0.0, lumberbase=75, 
        },
        Rowt={
            goldmod=0, class="caster", code4="", goldbase=100, effect4="ratd", Name1="灵魂行者专家训练", 
            lumbermod=100, global=0, Buttonpos_2=2, Requires1="", base1=150.0, mod1=150.0, Buttonpos_1=2, 
            Art2="ReplaceableTextures\\CommandButtons\\BTNSpiritWalkerMasterTraining.blp", 
            Ubertip2="增加灵魂行者的最大魔法值，魔法恢复速度和最大生命值。并让其具有先祖幽灵技能。", 
            base2=0.42, code3="", effect2="rmnr", Name2="灵魂行者大师训练", effect3="rhpx", Hotkey1="R", 
            Hotkey2="R", mod4=0.0, race="orc", code1="", timebase=60, 
            Ubertip1="增加灵魂行者的最大魔法值，魔法恢复速度和最大生命值。并让其具有消魔技能。", 
            mod3=60.0, mod2=0.42, maxlevel=2, 
            Art1="ReplaceableTextures\\CommandButtons\\BTNSpiritWalkerAdeptTraining.blp", 
            Tip1="灵魂行者专家训练(|cffffcc00R|r)", code2="", inherit=1, base4=0.0, Requires2="ofrt", 
            effect1="rmnx", Tip2=")灵魂行者大师训练(|cffffcc00R|r)", base3=60.0, lumberbase=50, 
        },
        Ruac={
            goldmod=0, Art="ReplaceableTextures\\CommandButtons\\BTNCannibalize.blp", code4="", goldbase=75, maxlevel=1, 
            lumbermod=0, global=0, Buttonpos_2=1, base1=0.0, mod1=0.0, Buttonpos_1=0, inherit=1, 
            Ubertip="使得食尸鬼和憎恶能吞食附近的一个尸体来恢复自己的生命值。", 
            Hotkey="C", base2=0.0, code3="", effect2="", effect3="", race="undead", code1="", timebase=30, 
            Tip="研究吞食尸体(|cffffcc00C|r)", class="", mod4=0.0, base4=0.0, code2="", mod3=0.0, Name="吞食尸体", 
            mod2=0.0, effect4="", effect1="", base3=0.0, lumberbase=0, 
        },
        Ropg={
            goldmod=0, Art="ReplaceableTextures\\CommandButtons\\BTNPillage.blp", code4="", goldbase=75, maxlevel=1, 
            lumbermod=0, global=0, Buttonpos_2=0, base1=0.0, mod1=0.0, Buttonpos_1=2, inherit=1, 
            Ubertip="使得苦工，兽族步兵和掠夺者对敌人建筑物的攻击能掠夺到一定的资源。", 
            Hotkey="G", base2=0.0, code3="", effect2="", effect3="", race="orc", code1="", timebase=45, 
            Tip="掠夺(|cffffcc00G|r)", class="", mod4=0.0, base4=0.0, code2="", mod3=0.0, Name="掠夺", mod2=0.0, effect4="", 
            effect1="", base3=0.0, lumberbase=25, 
        },
        Resc={
            goldmod=0, Art="ReplaceableTextures\\CommandButtons\\BTNSentinel.blp", code4="", goldbase=100, effect4="", 
            lumbermod=0, global=0, Buttonpos_2=1, base1=0.0, mod1=0.0, Buttonpos_1=1, inherit=1, 
            Ubertip="使得女猎手能放出一只猫头鹰栖息在一棵树上进行侦察。|n能看见隐形单位。", 
            Hotkey="S", base2=0.0, code3="", effect2="", effect3="", race="nightelf", Requires="edob,etoa", code1="", 
            timebase=20, Tip="研究哨兵(|cffffcc00S|r)", mod3=0.0, mod4=0.0, base4=0.0, code2="", class="", Name="哨兵", 
            mod2=0.0, maxlevel=1, effect1="", base3=0.0, lumberbase=100, 
        },
        Rows={
            goldmod=0, Art="ReplaceableTextures\\CommandButtons\\BTNSmash.blp", code4="", goldbase=100, maxlevel=1, 
            lumbermod=0, global=0, Buttonpos_2=2, base1=0.0, mod1=0.0, Buttonpos_1=0, inherit=1, 
            Ubertip="让牛头人具有粉碎技能，从而使得牛头人具有一定的概率造成范围性攻击。", 
            Hotkey="P", base2=0.0, code3="", effect2="", effect3="", race="orc", code1="", timebase=40, 
            Tip="研究粉碎(|cffffcc00P|r)", class="", mod4=0.0, base4=0.0, code2="", mod3=0.0, Name="粉碎", mod2=0.0, 
            effect4="", effect1="", base3=0.0, lumberbase=250, 
        },
        Rews={
            goldmod=0, Art="ReplaceableTextures\\CommandButtons\\BTNWellSpring.blp", code4="", goldbase=75, effect4="", 
            lumbermod=0, global=0, Buttonpos_2=0, base1=200.0, mod1=0.0, Buttonpos_1=3, inherit=1, 
            Ubertip="月亮井所能存储的魔法值增加<Rews,base1>点，魔法值恢复速度加快<Rews,base2,%>%。", 
            Hotkey="E", base2=0.83, code3="", effect2="rmnr", effect3="", race="nightelf", Requires="etoe", code1="", 
            timebase=30, Tip="研究月井之春(|cffffcc00E|r)", mod3=0.0, mod4=0.0, base4=0.0, code2="", class="", 
            Name="月井之春", mod2=0.0, maxlevel=1, effect1="rmnx", base3=0.0, lumberbase=150, 
        },
        Rers={
            goldmod=0, Art="ReplaceableTextures\\CommandButtons\\BTNResistantSkin.blp", code4="", goldbase=50, 
            effect4="", lumbermod=0, global=0, Buttonpos_2=2, base1=0.0, mod1=0.0, Buttonpos_1=2, inherit=1, 
            Ubertip="让山岭巨人增加对魔法攻击的抵抗力。", Hotkey="T", base2=0.0, code3="", effect2="", 
            effect3="", race="nightelf", Requires="etoe,eden", code1="", timebase=75, 
            Tip="研究抗性皮肤(|cffffcc00T|r)", mod3=0.0, mod4=0.0, base4=0.0, code2="", class="", Name="抗性皮肤", 
            mod2=0.0, maxlevel=1, effect1="", base3=0.0, lumberbase=100, 
        },
        Rotr={
            goldmod=0, Art="ReplaceableTextures\\CommandButtons\\BTNRegenerate.blp", code4="", goldbase=100, effect4="", 
            lumbermod=0, global=0, Buttonpos_2=1, base1=0.8, mod1=1.0, Buttonpos_1=1, inherit=1, 
            Ubertip="加快巫医，巨魔蝙蝠骑士和巨魔猎头者的生命值恢复。", Hotkey="R", 
            base2=0.0, code3="", effect2="", effect3="", race="orc", Requires="ostr,ofor", code1="", timebase=35, 
            Tip="研究巨魔再生(|cffffcc00R|r)", mod3=0.0, mod4=0.0, base4=0.0, code2="", class="", Name="巨魔再生", 
            mod2=0.0, maxlevel=1, effect1="rhpr", base3=0.0, lumberbase=100, 
        },
        Rugf={
            goldmod=0, Art="ReplaceableTextures\\CommandButtons\\BTNGhoulFrenzy.blp", code4="", goldbase=100, 
            effect4="", lumbermod=0, global=0, Buttonpos_2=2, base1=0.25, mod1=0.0, Buttonpos_1=0, inherit=1, 
            Ubertip="增加食尸鬼<Rugf,base1,%>%的攻击速度并加快其移动速度。", Hotkey="Z", 
            base2=80.0, code3="", effect2="rmvx", effect3="", race="undead", Requires="ugrv,unp2", code1="", timebase=45, 
            Tip="研究食尸鬼狂热(|cffffcc00Z|r)", mod3=0.0, mod4=0.0, base4=0.0, code2="", class="", 
            Name="食尸鬼狂热", mod2=0.0, maxlevel=1, effect1="rats", base3=0.0, lumberbase=150, 
        },
        Rhme={
            goldmod=75, class="melee", code4="", Hotkey3="S", effect4="", Name1="铁剑术", lumbermod=125, global=0, 
            Buttonpos_2=0, Requires1="", base1=1.0, mod1=1.0, Buttonpos_1=0, 
            Art2="ReplaceableTextures\\CommandButtons\\BTNThoriumMelee.blp", Hotkey2="S", 
            Art3="ReplaceableTextures\\CommandButtons\\BTNArcaniteMelee.blp", base2=0.0, code3="", effect2="", 
            Name2="钢剑术", effect1="ratd", Tip2="升级到钢剑术(|cffffcc00S|r)", race="human", effect3="", 
            Name3="毒剑术", mod4=0.0, mod3=0.0, mod2=0.0, maxlevel=3, 
            Ubertip3="进一步增加民兵、步兵、魔法破坏者、龙鹰骑士、狮鹫骑士和骑士的攻击力。", 
            code1="", timebase=60, 
            Ubertip1="增加民兵、步兵、魔法破坏者、龙鹰骑士、狮鹫骑士和骑士的攻击力。", 
            Tip3="升级到毒剑术(|cffffcc00S|r)", inherit=0, goldbase=100, 
            Art1="ReplaceableTextures\\CommandButtons\\BTNSteelMelee.blp", 
            Tip1="升级到铁剑术(|cffffcc00S|r)", code2="", 
            Ubertip2="进一步增加民兵、步兵、魔法破坏者、龙鹰骑士、狮鹫骑士和骑士的攻击力。", 
            Requires3="hcas", Requires2="hkee", Hotkey1="S", base4=0.0, base3=0.0, lumberbase=50, 
        },
        Rovs={
            goldmod=0, Art="ReplaceableTextures\\CommandButtons\\BTNEnvenomedSpear.blp", code4="", goldbase=100, 
            effect4="", lumbermod=0, global=0, Buttonpos_2=1, base1=0.0, mod1=0.0, Buttonpos_1=2, inherit=1, 
            Ubertip="使得风骑士的攻击带有毒性。一个被浸毒武器攻击到的单位会在一段时间内持续受到伤害。", 
            Hotkey="E", base2=0.0, code3="", effect2="", effect3="", race="orc", Requires="ofrt", code1="", timebase=40, 
            Tip="研究浸毒武器(|cffffcc00E|r)", mod3=0.0, mod4=0.0, base4=0.0, code2="", class="", Name="浸毒武器", 
            mod2=0.0, maxlevel=1, effect1="", base3=0.0, lumberbase=150, 
        },
        Rorb={
            goldmod=0, Art="ReplaceableTextures\\CommandButtons\\BTNReinforcedBurrows.blp", code4="", goldbase=50, 
            effect4="", lumbermod=0, global=0, Buttonpos_2=1, base1=1.0, mod1=0.0, Buttonpos_1=2, inherit=0, 
            Ubertip="升级地洞和了望塔从而让它们拥有加强型的护甲。", Hotkey="D", base2=0.0, 
            code3="", effect2="", effect3="", race="orc", Requires="ofrt", code1="", timebase=60, 
            Tip="加强型防御(|cffffcc00D|r)", mod3=0.0, mod4=0.0, base4=0.0, code2="", class="", Name="加强型防御", 
            mod2=0.0, maxlevel=1, effect1="rart", base3=0.0, lumberbase=200, 
        },
        Reuv={
            goldmod=0, Art="ReplaceableTextures\\CommandButtons\\BTNUltravision.blp", code4="", goldbase=50, maxlevel=1, 
            lumbermod=0, global=0, Buttonpos_2=0, base1=0.0, mod1=0.0, Buttonpos_1=2, inherit=1, 
            Ubertip="使得暗夜精灵族单位能在夜间和白天看得一样远。", Hotkey="U", base2=0.0, 
            code3="", effect2="", effect3="", race="nightelf", code1="", timebase=45, 
            Tip="升级到夜视能力(|cffffcc00U|r)", class="", mod4=0.0, base4=0.0, code2="", mod3=0.0, 
            Name="夜视能力", mod2=0.0, effect4="", effect1="", base3=0.0, lumberbase=50, 
        },
        Rhcd={
            goldmod=0, Art="ReplaceableTextures\\CommandButtons\\BTNCloudOfFog.blp", code4="", goldbase=50, effect4="", 
            lumbermod=0, global=0, Buttonpos_2=2, base1=0.0, mod1=0.0, Buttonpos_1=1, inherit=1, 
            Ubertip="使龙鹰骑士掌握乌云技能，从而使得敌人远程防御建筑不能攻击。", 
            Hotkey="C", base2=0.0, code3="", effect2="", effect3="", race="human", Requires="hvlt", code1="", timebase=35, 
            Tip="研究乌云(|cffffcc00C|r)", mod3=0.0, mod4=0.0, base4=0.0, code2="", class="", Name="乌云技能", 
            mod2=0.0, maxlevel=1, effect1="", base3=0.0, lumberbase=100, 
        },
        Rgfo={
            goldmod=50, class="", code4="", goldbase=100, effect4="", Name1="防御浮雕", lumbermod=50, global=0, 
            Buttonpos_2=0, base1=0.0, mod1=0.0, EditorSuffix2="(升级 2)", Buttonpos_1=0, 
            Art2="ReplaceableTextures\\CommandButtons\\BTNGlyph.blp", inherit=0, 
            Art3="ReplaceableTextures\\CommandButtons\\BTNGlyph.blp", base2=0.2, code3="", effect2="rhpo", 
            Name2="防御浮雕", effect3="", Name3="防御浮雕", code1="", timebase=60, EditorSuffix1=" (升级 1)", 
            mod4=0.0, race="unknown", Art1="ReplaceableTextures\\CommandButtons\\BTNGlyph.blp", base4=0.0, code2="", 
            mod3=0.0, mod2=0.2, maxlevel=3, EditorSuffix3="(升级 3)", effect1="rarm", base3=0.0, lumberbase=100, 
        },
        Ropm={
            goldmod=0, Art="ReplaceableTextures\\CommandButtons\\BTNPackBeast.blp", code4="", goldbase=50, effect4="", 
            lumbermod=0, global=0, Buttonpos_2=0, base1=0.0, mod1=0.0, Buttonpos_1=3, inherit=0, 
            Ubertip="让某个特定的兽族地面单位能替英雄携带物品。", Hotkey="B", base2=0.0, 
            code3="", effect2="", EditorSuffix=" (兽族)", effect3="", race="orc", Requires="ovln", code1="", timebase=20, 
            Tip="研究背包技能(|cffffcc00B|r)", mod3=0.0, mod4=0.0, base4=0.0, code2="", mod2=0.0, Name="背包技能", 
            class="", maxlevel=1, effect1="", base3=0.0, lumberbase=25, 
        },
        Rnsw={
            goldmod=0, class="caster", code4="", goldbase=100, effect4="ratd", Name1="娜迦海妖专家训练", 
            lumbermod=100, global=0, effect1="rmnx", base1=100.0, mod1=100.0, Buttonpos_1=0, 
            Art2="ReplaceableTextures\\CommandButtons\\BTNSirenMaster.blp", 
            Ubertip2="增加娜迦海妖的魔力容量、魔力回复速率、生命值并给予她们施放飓风的能力。", 
            base2=0.325, code3="", effect2="rmnr", Name2="娜迦海妖大师训练", effect3="rhpx", Hotkey1="N", 
            maxlevel=2, race="naga", code1="", timebase=60, 
            Ubertip1="增加娜迦海妖的魔力容量、魔力回复速率、生命值，并给予她们施放霜冻护甲的能力。", 
            mod4=0.0, mod3=40.0, mod2=0.325, Art1="ReplaceableTextures\\CommandButtons\\BTNSirenAdept.blp", base4=0.0, 
            code2="", Tip2="研究娜迦海妖大师训练(|cffffcc00N|r)", inherit=1, Buttonpos_2=2, 
            Tip1="研究娜迦海妖专家训练(|cffffcc00N|r)", Hotkey2="N", base3=40.0, lumberbase=50, 
        },
        Roch={
            base2=0.0, code3="", effect2="", goldmod=0, class="", maxlevel=1, mod4=0.0, code4="", race="demon", goldbase=0, 
            effect4="", mod3=0.0, mod2=0.0, mod1=0.0, code1="", timebase=0, lumbermod=0, global=1, effect1="", 
            Art="ReplaceableTextures\\CommandButtons\\BTNOrcMeleeUpOne.blp", base1=0.0, base4=0.0, code2="", 
            Buttonpos_1=0, Name="混乱的", inherit=0, Buttonpos_2=0, effect3="", base3=0.0, lumberbase=0, 
        },
        Remg={
            goldmod=0, Art="ReplaceableTextures\\CommandButtons\\BTNUpgradeMoonGlaive.blp", code4="", goldbase=100, 
            effect4="", lumbermod=0, global=0, Buttonpos_2=2, base1=1.0, mod1=0.0, Buttonpos_1=1, inherit=1, 
            Ubertip="使得女猎手的月刃剑能在攻击的时候进行弹射，从而伤害到敌人其他的单位。", 
            Hotkey="G", base2=0.0, code3="", effect2="", effect3="", race="nightelf", Requires="edob,etoe", code1="", 
            timebase=35, Tip="升级月刃(|cffffcc00G|r)", mod3=0.0, mod4=0.0, base4=0.0, code2="", class="", 
            Name="升级月刃", mod2=0.0, maxlevel=1, effect1="ratc", base3=0.0, lumberbase=150, 
        },
        Robf={
            goldmod=0, Art="ReplaceableTextures\\CommandButtons\\BTNFireRocks.blp", code4="", goldbase=50, effect4="", 
            lumbermod=0, global=0, Buttonpos_2=2, base1=0.0, mod1=0.0, Buttonpos_1=2, inherit=1, 
            Ubertip="升级粉碎者，使其能投出包裹石油的燃烧石块，从而能燃烧地面。", 
            Hotkey="N", base2=0.0, code3="", effect2="", effect3="", race="orc", Requires="ofrt", code1="", timebase=30, 
            Tip="燃烧之油(|cffffcc00N|r)", mod3=0.0, mod4=0.0, base4=0.0, code2="", class="", Name="燃烧之油", 
            mod2=0.0, maxlevel=1, effect1="", base3=0.0, lumberbase=150, 
        },
        Roar={
            goldmod=75, class="armor", code4="", Hotkey3="A", effect4="", Name1="钢铁护甲", lumbermod=150, global=0, 
            Buttonpos_2=1, Requires1="", base1=0.0, mod1=0.0, Buttonpos_1=0, 
            Art2="ReplaceableTextures\\CommandButtons\\BTNThoriumArmor.blp", Hotkey2="A", 
            Art3="ReplaceableTextures\\CommandButtons\\BTNArcaniteArmor.blp", base2=0.0, code3="", effect2="", 
            Name2="金属护甲", effect1="rarm", Tip2="升级到钢铁护甲(|cffffcc00A|r)", race="orc", effect3="", 
            Name3="终极护甲", mod4=0.0, mod3=0.0, mod2=0.0, maxlevel=3, 
            Ubertip3="进一步增加兽族步兵，掠夺者，牛头人，巨魔猎头者，巨魔蝙蝠骑士，风骑士和粉碎者的护甲。", 
            code1="", timebase=60, 
            Ubertip1="增加兽族步兵，掠夺者，牛头人，巨魔猎头者，巨魔蝙蝠骑士，风骑士和粉碎者的护甲。", 
            Tip3="升级到终极护甲(|cffffcc00A|r)", inherit=0, goldbase=150, 
            Art1="ReplaceableTextures\\CommandButtons\\BTNSteelArmor.blp", 
            Tip1="升级到钢铁护甲(|cffffcc00A|r)", code2="", 
            Ubertip2="进一步增加兽族步兵，掠夺者，牛头人，巨魔猎头者，巨魔蝙蝠骑士，风骑士和粉碎者的护甲。", 
            Requires3="ofrt", Requires2="ostr", Hotkey1="A", base4=0.0, base3=0.0, lumberbase=75, 
        },
        Rnsi={
            goldmod=0, Art="ReplaceableTextures\\CommandButtons\\BTNDryadDispelMagic.blp", code4="", goldbase=50, 
            maxlevel=1, lumbermod=0, global=0, Buttonpos_2=2, base1=0.0, mod1=0.0, Buttonpos_1=1, inherit=1, 
            Ubertip="给予飞蛇驱散敌单位正面效果的魔法，及友方单位负面效果魔法的能力。|n对召唤单位造成伤害。", 
            Hotkey="B", base2=0.0, code3="", effect2="", effect3="", race="naga", code1="", timebase=45, 
            Tip="研究驱逐魔法(|cffffcc00B|r)", class="", mod4=0.0, base4=0.0, code2="", mod3=0.0, Name="驱逐魔法", 
            mod2=0.0, effect4="", effect1="", base3=0.0, lumberbase=50, 
        },
        Rnat={
            goldmod=75, class="melee", code4="", Hotkey3="B", effect4="", Name1="珊瑚剑", lumbermod=150, global=0, 
            Buttonpos_2=2, base1=1.0, mod1=1.0, Buttonpos_1=0, 
            Art2="ReplaceableTextures\\CommandButtons\\BTNNagaWeaponUp2.blp", 
            Ubertip2="进一步增加娜迦族攻击单位的攻击。", 
            Art3="ReplaceableTextures\\CommandButtons\\BTNNagaWeaponUp3.blp", base2=0.0, code3="", effect2="", 
            Name2="壳质剑", inherit=0, effect3="", Name3="尖刺剑", mod2=0.0, race="naga", mod4=0.0, mod3=0.0, 
            Ubertip3="增加娜迦族攻击单位的攻击。", code1="", timebase=60, 
            Ubertip1="增加娜迦族攻击单位的攻击力。", Tip3="升级到尖刺剑(|cffffcc00B|r)", 
            maxlevel=3, Hotkey2="B", Art1="ReplaceableTextures\\CommandButtons\\BTNNagaWeaponUp1.blp", 
            Tip1="升级到珊瑚剑(|cffffcc00B|r)", code2="", goldbase=150, Hotkey1="B", effect1="ratd", 
            Tip2="升级到壳质剑(|cffffcc00B|r)", base4=0.0, base3=0.0, lumberbase=75, 
        },
        Rhfc={
            goldmod=0, Art="ReplaceableTextures\\CommandButtons\\BTNFlakCannons.blp", code4="", goldbase=100, 
            effect4="", lumbermod=0, global=0, Buttonpos_2=1, base1=0.0, mod1=0.0, Buttonpos_1=0, inherit=1, 
            Ubertip="升级飞行机器的武器，使他们能够对空中单位造成区域性伤害。", 
            Hotkey="C", base2=0.0, code3="", effect2="", effect3="", race="human", Requires="hcas", code1="", timebase=40, 
            Tip="研究高射炮火(|cffffcc00C|r)", mod3=0.0, mod4=0.0, base4=0.0, code2="", class="", Name="高射炮火", 
            mod2=0.0, maxlevel=1, effect1="", base3=0.0, lumberbase=150, 
        },
        Redt={
            goldmod=0, class="caster", code4="", goldbase=100, effect4="ratd", Name1="猛禽德鲁伊专家训练", 
            lumbermod=100, global=0, Buttonpos_2=2, Requires1="", base1=100.0, mod1=100.0, Buttonpos_1=1, 
            Art2="ReplaceableTextures\\CommandButtons\\BTNDOTMasterTraining.blp", 
            Ubertip2="增加猛禽德鲁伊暗夜精灵状态下的魔法最大值，魔法恢复速度，生命值和攻击力。并使其拥有飓风技能。", 
            base2=0.325, code3="", effect2="rmnr", Name2="猛禽德鲁伊大师训练", effect3="rhpx", Hotkey1="A", 
            Hotkey2="A", mod4=0.0, race="nightelf", code1="", timebase=60, 
            Ubertip1="增加猛禽德鲁伊暗夜精灵状态下的魔法最大值，魔法恢复速度，生命值和攻击力。并使其拥有风暴之鸦技能。", 
            mod3=40.0, mod2=0.325, maxlevel=2, Art1="ReplaceableTextures\\CommandButtons\\BTNDOTAdeptTraining.blp", 
            Tip1="猛禽德鲁伊专家训练(|cffffcc00A|r)", code2="", inherit=1, base4=0.0, Requires2="etoe", 
            effect1="rmnx", Tip2=" 猛禽德鲁伊大师训练(|cffffcc00A|r)", base3=40.0, lumberbase=50, 
        },
        Rnam={
            goldmod=100, class="armor", code4="", Hotkey3="C", effect4="", Name1="珊瑚鳞甲", lumbermod=150, global=0, 
            Buttonpos_2=2, base1=0.0, mod1=0.0, Buttonpos_1=1, 
            Art2="ReplaceableTextures\\CommandButtons\\BTNNagaArmorUp2.blp", 
            Ubertip2="进一步增加娜迦攻击单位的防御力。", 
            Art3="ReplaceableTextures\\CommandButtons\\BTNNagaArmorUp3.blp", base2=0.0, code3="", effect2="", 
            Name2="壳质鳞甲", inherit=0, effect3="", Name3="尖刺鳞甲", mod2=0.0, race="naga", mod4=0.0, mod3=0.0, 
            Ubertip3="进一步增加娜迦攻击单位的防御力。", code1="", timebase=60, 
            Ubertip1="增加娜迦族攻击单位的防御力。", Tip3="升级到尖刺鳞甲(|cffffcc00C|r)", 
            maxlevel=3, Hotkey2="C", Art1="ReplaceableTextures\\CommandButtons\\BTNNagaArmorUp1.blp", 
            Tip1="升级到珊瑚鳞甲(|cffffcc00C|r)", code2="", goldbase=125, Hotkey1="C", effect1="rarm", 
            Tip2="升级壳质鳞甲(|cffffcc00C|r)", base4=0.0, base3=0.0, lumberbase=75, 
        },
        Reht={
            goldmod=0, Art="ReplaceableTextures\\CommandButtons\\BTNTameHippogriff.blp", code4="", goldbase=75, 
            maxlevel=1, lumbermod=0, global=0, Buttonpos_2=2, base1=0.0, mod1=0.0, Buttonpos_1=0, inherit=1, 
            Ubertip="使得弓箭手能骑乘在角鹰兽的背上从而成为角鹰兽骑士。角鹰兽骑士既能攻击地面单位也能攻击空中单位。", 
            Hotkey="I", base2=0.0, code3="", effect2="", effect3="", race="nightelf", code1="", timebase=30, 
            Tip="研究驯服角鹰兽(|cffffcc00I|r)", class="", mod4=0.0, base4=0.0, code2="", mod3=0.0, 
            Name="驯服角鹰兽", mod2=0.0, effect4="", effect1="", base3=0.0, lumberbase=75, 
        },
        Remk={
            goldmod=0, Art="ReplaceableTextures\\CommandButtons\\BTNMarksmanship.blp", code4="", goldbase=100, 
            effect4="", lumbermod=0, global=0, Buttonpos_2=2, base1=3.0, mod1=0.0, Buttonpos_1=0, inherit=1, 
            Ubertip="能增加弓箭手和角鹰兽骑士<Remk,base1>点的攻击力。", Hotkey="M", base2=0.0, 
            code3="", effect2="", effect3="", race="nightelf", Requires="edob,etoe", code1="", timebase=40, 
            Tip="研究射击术(|cffffcc00M|r)", mod3=0.0, mod4=0.0, base4=0.0, code2="", class="", Name="射击术", 
            mod2=0.0, maxlevel=1, effect1="ratx", base3=0.0, lumberbase=175, 
        },
        Renb={
            goldmod=0, Art="ReplaceableTextures\\CommandButtons\\BTNNaturesBlessing.blp", code4="", goldbase=150, 
            effect4="", lumbermod=0, global=0, Buttonpos_2=0, base1=40.0, mod1=0.0, Buttonpos_1=2, inherit=1, 
            Ubertip="能提高所有古树和树人的移动速度和护甲。", Hotkey="N", base2=0.0, code3="", 
            effect2="rarm", effect3="", race="nightelf", Requires="etoa", code1="", timebase=60, 
            Tip="研究自然的祝福(|cffffcc00N|r)", mod3=0.0, mod4=0.0, base4=0.0, code2="", class="", 
            Name="自然的祝福", mod2=0.0, maxlevel=1, effect1="rmvx", base3=0.0, lumberbase=200, 
        },
        Rhde={
            goldmod=0, Art="ReplaceableTextures\\CommandButtons\\BTNDefend.blp", code4="", goldbase=150, maxlevel=1, 
            lumbermod=0, global=0, Buttonpos_2=2, base1=0.0, mod1=0.0, Buttonpos_1=0, inherit=1, 
            Ubertip="使得步兵能拥有防御技能，有效地抵抗敌人的穿刺型攻击。", Hotkey="D", 
            base2=0.0, code3="", effect2="", effect3="", race="human", code1="", timebase=45, 
            Tip="研究防御(|cffffcc00D|r)", class="", mod4=0.0, base4=0.0, code2="", mod3=0.0, Name="防御", mod2=0.0, 
            effect4="", effect1="", base3=0.0, lumberbase=100, 
        },
    },
    category="upgrade", 
}