return {
    items={
        A001={
            _parent="Aroc", Area1=1000.0000, Missileart="abilities\\weapons\\catapult\\catapultmissile.mdl", 
            Art="ReplaceableTextures\\CommandButtons\\BTNSteelRanged.blp", Missilespeed=2000, Tip="Multi-Attack", 
            DataB1=99999.0000, Requires="", Name="Multi-Attack", DataA1=450.0000, Missilearc=0.3500, Cool1=0.1000, 
            DataC1=10, 
        },
        A00C={
            Ubertip="This tower attacks so devistatingly hard that it gives enemies brain damage.", 
            _parent="Afra", Tip="Slow", Name="Slow", Art="ReplaceableTextures\\CommandButtons\\BTNSlow.blp", 
            Missileart="", Dur1=0.1000, HeroDur1=0.1000, 
        },
        A005={
            _parent="ANdp", hero=0, Ubertip="Frank and Jack set down a Flaming Poop Bag for an enemy to step on.", 
            Art="ReplaceableTextures\\CommandButtons\\BTNDustOfAppearance.blp", 
            Tip="|cffffcc00F|rlaming Poop Bag", DataA1="n000", DataB1=1, 
            EffectArt="Abilities\\Spells\\Human\\DispelMagic\\DispelMagicTarget.mdl", Name="Flaming Poop Bag", 
            Hotkey="F", ResearchArt="ReplaceableTextures\\CommandButtons\\BTNDustOfAppearance.blp", 
            Researchhotkey="F", DataC1=1, 
        },
        A00B={
            _parent="ACat", TargetArt="Abilities\\Spells\\Other\\Drain\\ManaDrainTarget.mdl", Name="Goos Frabah", 
            Art="ReplaceableTextures\\CommandButtons\\BTNSleep.blp", Tip="Goos Frabah", 
        },
        A008={
            Cost1=0, Art="ReplaceableTextures\\CommandButtons\\BTNAvatarOff.blp", Requires="", DataA1=0.6000, 
            Unart="ReplaceableTextures\\CommandButtons\\BTNAvatarOff.blp", _parent="Ablo", Name="Get Pissed", 
            Hotkey="S", Unhotkey="S", Tip="Get Pi|cffffcc00s|rsed", Requiresamount="", 
        },
        A002={
            checkDep=0, Cost1=0, BuffID1="", Orderoff="carrionswarm", Rng1=1200.0000, Order="carrionswarm", 
            Name="Car Attack", Orderon="carrionswarm", Cool1=0.5000, _parent="Acrs", 
        },
        A00A={
            Cost1=0, Art="ReplaceableTextures\\CommandButtons\\BTNAvatarOff.blp", Requires="", DataA1=0.1000, 
            Unart="ReplaceableTextures\\CommandButtons\\BTNAvatarOff.blp", _parent="Ablo", Name="Get Pissed", 
            Hotkey="S", Unhotkey="S", Tip="Get Pi|cffffcc00s|rsed", Requiresamount="", 
        },
        A004={
            _parent="Amgr", Name="Car Attack", Tip="Car Attack", 
            Art="ReplaceableTextures\\CommandButtons\\BTNSeigeEngine.blp", 
        },
        A007={
            _parent="Ablo", Art="ReplaceableTextures\\CommandButtons\\BTNVialFull.blp", Requires="", Cost1=0, 
            Unart="ReplaceableTextures\\CommandButtons\\BTNVialFull.blp", Name="Steroids", Hotkey="S", Unhotkey="S", 
            Tip="|cffffcc00S|rteroids", Requiresamount="", 
        },
        A009={
            Cost1=0, EditorSuffix="3", Art="ReplaceableTextures\\CommandButtons\\BTNAvatarOff.blp", Requires="", 
            Requiresamount="", Unart="ReplaceableTextures\\CommandButtons\\BTNAvatarOff.blp", _parent="Ablo", 
            Name="Get Pissed", Hotkey="S", Unhotkey="S", Tip="Get Pi|cffffcc00s|rsed", DataA1=0.3000, 
        },
        A006={
            DataB1=7.0000, Name="Pot Smoke (Abomination)", 
            Ubertip="Infects nearby enemy living units with Pot Smoke. The smoke deals <Aap1,DataB1> damage per second. |nLasts <Aap1,DataA1> seconds.", 
            _parent="Aap1", Tip="Smoke", Requires="", 
        },
        A003={
            checkDep=0, _parent="Aakb", Name="It's all in the hips.", 
            Ubertip="Boosts the confidence of nearby friendly units making them have a 30% damage increase.", 
            Tip="It's all in the hips.", Art="ReplaceableTextures\\PassiveButtons\\PASBTNGnollCommandAura.blp", 
            DataA1=0.3000, 
        },
        AUcs={
            _parent="AUcs", DataA2=125.0000, Missileart="units\\human\\WarWagon\\WarWagon_V1.mdl", Rng1=1200.0000, 
            DataB1=125.0000, Rng2=700.0000, DataC1=1200.0000, Rng3=700.0000, 
            Art="ReplaceableTextures\\CommandButtons\\BTNSeigeEngine.blp", DataA3=200.0000, 
            ResearchArt="ReplaceableTextures\\CommandButtons\\BTNSeigeEngine.blp", DataB2=600.0000, DataA1=25.0000, 
            DataB3=1000.0000, DataC3=800.0000, DataC2=800.0000, 
        },
        A000={
            _parent="ACca", Missileart="units\\human\\WarWagon\\WarWagon_V1.mdl", 
            SpecialArt="Objects\\Spawnmodels\\Human\\HumanLargeDeathExplode\\HumanLargeDeathExplode.mdl", 
            Rng1=1200.0000, DataB1=125.0000, Orderon="curseon", Tip="|cffffcc00C|rar Attack", DataA1=25.0000, Cost1=0, 
            Unorder="curseoff", Art="ReplaceableTextures\\CommandButtons\\BTNSeigeEngine.blp", Orderoff="curseoff", 
            Ubertip="Donald runs over enemies in his car.", Name="Car Attack", DataC1=1200.0000, Cool1=0.5000, 
            Order="curseon", 
        },
        Amnx={_parent="Amnx"}, 
    },
    keys={
        _parent="目标允许", EditorSuffix="编辑器后缀", Rng1="施法距离", DataB1="每秒伤害", 
        Unhotkey="热键 -关闭", Researchhotkey="热键 - 学习", DataA3="伤害", Rng3="施法距离", 
        TargetArt="效果 - 目标", Area1="影响区域", BuffID1="魔法效果", Requires="需求", 
        Ubertip="提示工具 - 普通 - 扩展", ResearchArt="图标 - 学习", Name="名字", 
        Cool1="魔法施放时间间隔", hero="英雄技能", checkDep="检查等价所属", DataA2="伤害", 
        levels="等级", DataD1="部分伤害数值", Missileart="效果 - 投射物图像", 
        SpecialArt="效果 -特殊", HeroDur1="持续时间 - 英雄", EffectArt="效果 - 目标点", 
        targs1="目标允许", Dur1="持续时间 - 普通", Missilearc="效果 - 射弹弧度", 
        Rng2="施法距离", DataC1="最大单位数", Unart="图标 -关闭", Cost1="魔法消耗", 
        Requiresamount="需求值", DataB2="最大伤害", Unorder="命令串 - 关闭", 
        Orderon="命令串 - 激活", Art="图标 - 普通", Missilespeed="效果 - 射弹速度", 
        DataB3="最大伤害", Order="命令串 - 使用/打开", DataC3="距离", DataA1="攻击速度增加(%)", 
        Hotkey="热键 - 普通", Orderoff="命令串 - 取消激活", Tip="提示工具 - 普通", 
        DataC2="距离", 
    },
    category="ability", 
}