return {
    keys={
        BuffID1="魔法效果", EffectArt="效果 - 目标点", Unhotkey="热键 -关闭", Art="图标 - 普通", 
        DataA3="伤害", Cost1="魔法消耗", levels="等级", DataA2="伤害", Researchhotkey="热键 - 学习", 
        DataC1="最大单位数", DataB2="最大伤害", _parent="目标允许", 
        Missileart="效果 - 投射物图像", Missilespeed="效果 - 射弹速度", Hotkey="热键 - 普通", 
        HeroDur1="持续时间 - 英雄", DataC2="距离", DataC3="距离", Order="命令串 - 使用/打开", 
        Dur1="持续时间 - 普通", Cool1="魔法施放时间间隔", Rng1="施法距离", 
        TargetArt="效果 - 目标", EditorSuffix="编辑器后缀", Requires="需求", Unart="图标 -关闭", 
        Rng2="施法距离", SpecialArt="效果 -特殊", checkDep="检查等价所属", 
        Unorder="命令串 - 关闭", hero="英雄技能", Tip="提示工具 - 普通", Area1="影响区域", 
        DataD1="部分伤害数值", DataB3="最大伤害", DataB1="每秒伤害", DataA1="攻击速度增加(%)", 
        Orderoff="命令串 - 取消激活", targs1="目标允许", Requiresamount="需求值", 
        Rng3="施法距离", Missilearc="效果 - 射弹弧度", ResearchArt="图标 - 学习", 
        Ubertip="提示工具 - 普通 - 扩展", Orderon="命令串 - 激活", Name="名字", 
    },
    items={
        A00B={
            _parent="ACat", Name="Goos Frabah", Art="ReplaceableTextures\\CommandButtons\\BTNSleep.blp", 
            Tip="Goos Frabah", TargetArt="Abilities\\Spells\\Other\\Drain\\ManaDrainTarget.mdl", 
        },
        A005={
            hero=0, Tip="|cffffcc00F|rlaming Poop Bag", 
            EffectArt="Abilities\\Spells\\Human\\DispelMagic\\DispelMagicTarget.mdl", DataB1=1, 
            Art="ReplaceableTextures\\CommandButtons\\BTNDustOfAppearance.blp", DataC1=1, DataA1="n000", 
            _parent="ANdp", Name="Flaming Poop Bag", 
            ResearchArt="ReplaceableTextures\\CommandButtons\\BTNDustOfAppearance.blp", 
            Ubertip="Frank and Jack set down a Flaming Poop Bag for an enemy to step on.", Hotkey="F", 
            Researchhotkey="F", 
        },
        A001={
            Tip="Multi-Attack", Area1=1000.0000, DataB1=99999.0000, 
            Art="ReplaceableTextures\\CommandButtons\\BTNSteelRanged.blp", Cool1=0.1000, DataA1=450.0000, 
            _parent="Aroc", Name="Multi-Attack", Missilearc=0.3500, 
            Missileart="abilities\\weapons\\catapult\\catapultmissile.mdl", Missilespeed=2000, Requires="", DataC1=10, 
        },
        A003={
            _parent="Aakb", Name="It's all in the hips.", Tip="It's all in the hips.", 
            Ubertip="Boosts the confidence of nearby friendly units making them have a 30% damage increase.", 
            Art="ReplaceableTextures\\PassiveButtons\\PASBTNGnollCommandAura.blp", checkDep=0, DataA1=0.3000, 
        },
        A00A={
            Tip="Get Pi|cffffcc00s|rsed", Unhotkey="S", Art="ReplaceableTextures\\CommandButtons\\BTNAvatarOff.blp", 
            Cost1=0, _parent="Ablo", Requires="", Unart="ReplaceableTextures\\CommandButtons\\BTNAvatarOff.blp", 
            Requiresamount="", Name="Get Pissed", Hotkey="S", DataA1=0.1000, 
        },
        A00C={
            Ubertip="This tower attacks so devistatingly hard that it gives enemies brain damage.", 
            _parent="Afra", Name="Slow", Dur1=0.1000, Missileart="", 
            Art="ReplaceableTextures\\CommandButtons\\BTNSlow.blp", Tip="Slow", HeroDur1=0.1000, 
        },
        A007={
            Tip="|cffffcc00S|rteroids", Unhotkey="S", Art="ReplaceableTextures\\CommandButtons\\BTNVialFull.blp", 
            Cost1=0, Requiresamount="", Requires="", Unart="ReplaceableTextures\\CommandButtons\\BTNVialFull.blp", 
            _parent="Ablo", Hotkey="S", Name="Steroids", 
        },
        A000={
            DataB1=125.0000, Art="ReplaceableTextures\\CommandButtons\\BTNSeigeEngine.blp", Cool1=0.5000, 
            DataA1=25.0000, 
            SpecialArt="Objects\\Spawnmodels\\Human\\HumanLargeDeathExplode\\HumanLargeDeathExplode.mdl", 
            Tip="|cffffcc00C|rar Attack", Ubertip="Donald runs over enemies in his car.", Unorder="curseoff", 
            DataC1=1200.0000, Orderoff="curseoff", _parent="ACca", Name="Car Attack", Order="curseon", 
            Missileart="units\\human\\WarWagon\\WarWagon_V1.mdl", Rng1=1200.0000, Cost1=0, Orderon="curseon", 
        },
        A004={
            _parent="Amgr", Name="Car Attack", Art="ReplaceableTextures\\CommandButtons\\BTNSeigeEngine.blp", 
            Tip="Car Attack", 
        },
        A002={
            BuffID1="", Order="carrionswarm", Cool1=0.5000, Cost1=0, _parent="Acrs", Name="Car Attack", 
            Orderon="carrionswarm", Rng1=1200.0000, checkDep=0, Orderoff="carrionswarm", 
        },
        A008={
            Tip="Get Pi|cffffcc00s|rsed", Unhotkey="S", Art="ReplaceableTextures\\CommandButtons\\BTNAvatarOff.blp", 
            Cost1=0, _parent="Ablo", Requires="", Unart="ReplaceableTextures\\CommandButtons\\BTNAvatarOff.blp", 
            Requiresamount="", Name="Get Pissed", Hotkey="S", DataA1=0.6000, 
        },
        A006={
            _parent="Aap1", Requires="", DataB1=7.0000, 
            Ubertip="Infects nearby enemy living units with Pot Smoke. The smoke deals <Aap1,DataB1> damage per second. |nLasts <Aap1,DataA1> seconds.", 
            Tip="Smoke", Name="Pot Smoke (Abomination)", 
        },
        A009={
            Tip="Get Pi|cffffcc00s|rsed", Unhotkey="S", Art="ReplaceableTextures\\CommandButtons\\BTNAvatarOff.blp", 
            Unart="ReplaceableTextures\\CommandButtons\\BTNAvatarOff.blp", Cost1=0, _parent="Ablo", Name="Get Pissed", 
            Requiresamount="", Requires="", DataA1=0.3000, Hotkey="S", EditorSuffix="3", 
        },
        AUcs={
            DataC2=800.0000, DataC3=800.0000, DataB1=125.0000, 
            Art="ReplaceableTextures\\CommandButtons\\BTNSeigeEngine.blp", DataA3=200.0000, DataA1=25.0000, 
            Rng2=700.0000, DataA2=125.0000, DataC1=1200.0000, DataB2=600.0000, _parent="AUcs", Rng3=700.0000, 
            Missileart="units\\human\\WarWagon\\WarWagon_V1.mdl", DataB3=1000.0000, Rng1=1200.0000, 
            ResearchArt="ReplaceableTextures\\CommandButtons\\BTNSeigeEngine.blp", 
        },
        Amnx={_parent="Amnx"}, 
    },
    category="ability", 
}