return {
    items={
        o010={
            goldcost=75, abilList="A008,Abds,Arbr,Aspi", blue=50, 
            Missileart_1="Abilities\\Weapons\\BrewmasterMissile\\BrewmasterMissile.mdl", Trains="o00I", green=50, 
            file="units\\orc\\HeroShadowHunter\\HeroShadowHunter.mdl", Tip="Build |cffffcc00C|rhuck", bldtm=1, 
            preventPlace="unwalkable", lumbercost=0, red=50, sides1=4, 
            Art="ReplaceableTextures\\CommandButtons\\BTNShadowHunter.blp", Requires="", points=60, acquire=800.0000, 
            rangeN1=450, Name="Chuck", Hotkey="C", dmgplus1=90, cool1=0.4000, _parent="owtw", 
        },
        h004={
            def=4.0000, collision=10.0000, dmgplus1=999, Name="Leonardo Dicaprio", 
            file="units\\critters\\HighElfPeasant\\HighElfPeasant.mdl", HP=125, _parent="hfoo", 
        },
        e004={
            _parent="esen", abilList="Aesn,Amgl,Aien,Ault", dmgplus1=999, defType="hero", collision=10.0000, def=5.0000, 
            file="units\\other\\Proudmoore\\Proudmoore.mdl", modelScale=2.5000, HP=35000, Name="Tom Cruise", 
        },
        o004={
            Harea1=120, _parent="owtw", abilList="A001", 
            Missileart_2="abilities\\weapons\\catapult\\catapultmissile.mdl", atkType1="siege", Farea1=100, 
            cool2=0.1500, Qarea1=150, file="units\\critters\\VillagerKid\\VillagerKid.mdl", weapType1="RockHeavyBash", 
            bldtm=1, sides2=45, dice1=2, preventPlace="unwalkable", armor="Stone", RngBuff2=250.0000, Requires="", 
            Missilearc_2=0.3500, acquire=1000.0000, atkType2="pierce", Name="\"Frankenstein\"", 
            weapType2="RockHeavyBash", goldcost=350, targs2="air", splashTargs1="enemies,ground,notself,organic", 
            Trains="o00I", lumbercost=0, targs1="enemies,ground", weapTp2="missile", 
            Tip="Build |cffffcc00F|rrankenstein", unitSound="VillagerKid", weapTp1="msplash", dmgpt2=0.3000, 
            rangeN2=1000, targCount2=5, sides1=75, points=263, 
            Art="ReplaceableTextures\\CommandButtons\\BTNVillagerKid.blp", 
            Missileart_1="abilities\\weapons\\catapult\\catapultmissile.mdl", Missilespeed_2=2000, dmgplus1=173, 
            backSw2=0.3000, 
            Ubertip="Equiped with nothing more than a slingshot, Frankenstein is able to do massive damage.  He also has a special attack against air which is able to hit multiple targets.", 
            Hotkey="F", dice2=3, cool1=0.4000, dmgplus2=422, 
        },
        o00X={
            goldcost=400, points=300, atkType1="siege", dmgplus1=479, Trains="o00I", lumbercost=0, 
            file="units\\nightelf\\MalFurion\\MalFurionNoStag.mdl", Tip="Build H|cffffcc00e|rnry", bldtm=1, 
            preventPlace="unwalkable", sides1=1, Art="ReplaceableTextures\\CommandButtons\\BTNFurion.blp", 
            Requires="", acquire=1000.0000, rangeN1=1000, Name="Henry", Hotkey="E", 
            Missileart_1="units\\critters\\Penguin\\Penguin.mdl", cool1=0.4000, _parent="owtw", 
        },
        u009={
            dice1=1, defUp=14.0000, dmgplus1=999, type="", defType="small", collision=10.0000, sides1=1, Name="David Spade", 
            file="units\\human\\Priest\\Priest_V1.mdl", _parent="ugho", HP=1100, def=5.0000, 
        },
        uaco={
            abilList="", _parent="uaco", Name="Big Daddy", Hotkey="B", Builds="", Tip="|cffffcc00B|rig Daddy", 
            Ubertip="Builds units from Big Daddy.  This race excels in ", 
        },
        o017={
            _parent="owtw", points=125, atkType1="hero", dmgplus1=74, Trains="o00I", lumbercost=0, 
            targs1="air,enemies,ground", file="units\\creeps\\assassin\\assassin.mdl", 
            Tip="Build |cffffcc00P|ram Dawson", bldtm=1, preventPlace="unwalkable", sides1=8, 
            Art="ReplaceableTextures\\CommandButtons\\BTNAssassin.blp", Requires="", rangeN1=750, 
            Name="\"Pam Dawson\"", Hotkey="P", 
            Missileart_1="Abilities\\Spells\\Other\\FrostBolt\\FrostBoltMissile.mdl", cool1=0.0500, goldcost=150, 
        },
        o00Z={
            Harea1=35, _parent="owtw", abilList="A009", 
            Missileart_2="Objects\\InventoryItems\\TreasureChest\\treasurechest.mdl", atkType1="siege", 
            Missileart_1="Objects\\InventoryItems\\TreasureChest\\treasurechest.mdl", Farea2=20, Qarea1=50, 
            file="Units\\Creeps\\BansheeRanger\\BansheeRanger.mdl", Harea2=35, sides2=3, preventPlace="unwalkable", 
            MissileHoming_1=1, targCount1=3, Requires="", acquire=1200.0000, atkType2="siege", Name="Stacy", goldcost=50, 
            targs2="air,enemies", splashTargs1="enemies,ground", Trains="o00I", lumbercost=0, targs1="enemies,ground", 
            Tip="Build |cffffcc00S|rtacy", weapTp1="msplash", targCount2=3, rangeN2=450, rangeN1=450, Qarea2=50, points=40, 
            Art="ReplaceableTextures\\CommandButtons\\BTNBansheeRanger.blp", dmgplus1=52, Missilespeed_2=1800, 
            Ubertip="\"Stacy: Uh, we're in the adult film industry, and, we're lovers. \"", bldtm=1, dice2=1, 
            Hotkey="D", dmgplus2=52, cool1=0.5700, Farea1=20, 
        },
        h007={
            dice1=1, defUp=23.0000, dmgplus1=999, defType="large", collision=10.0000, Name="Halle Berry", 
            file="units\\nightelf\\Vengeance\\Vengeance.mdl", _parent="hrif", HP=4500, def=7.0000, 
        },
        o00C={
            dice1=0, dmgplus1=1000, defType="large", collision=50.0000, Name="Ozzy Osbourne", _parent="owyv", HP=950, 
            def=5.0000, 
        },
        o015={
            goldcost=30, abilList="A00C,Abds,Arbr,Aspi", points=25, atkType1="hero", dmgplus1=18, Trains="o00I", 
            lumbercost=0, targs1="air,enemies,ground", file="units\\orc\\spiritwalker\\spiritwalker.mdl", 
            Tip="Build |cffffcc00J|ran", bldtm=1, preventPlace="unwalkable", sides1=5, 
            Art="ReplaceableTextures\\CommandButtons\\BTNSpiritWalker.blp", Requires="", 
            Ubertip="\"I'm sorry all I heard was blah blah blah I'm a dirty tramp.\"", rangeN1=750, Name="Jan", 
            Hotkey="J", Missileart_1="Abilities\\Weapons\\WingedSerpentMissile\\WingedSerpentMissile.mdl", 
            cool1=0.0500, _parent="owtw", 
        },
        u003={
            _parent="uaco", spd=522, abilList="Avul", atkType1="unknown", Builds="o00Y,o00Z,o010,o011,o012", 
            Art="ReplaceableTextures\\CommandButtons\\BTNHeroAlchemist.blp", moveHeight=200.0000, goldcost=0, 
            Ubertip="Builds units from Anger Management.  These towers have high damage but lack in range. Most towers can get pissed off too.", 
            file="Units\\Creeps\\HeroGoblinAlchemist\\HeroGoblinAlchemist.mdl", Name="Lou", Hotkey="L", movetp="fly", 
            Tip="|cffffcc00L|rou", bldtm=1, 
        },
        o007={
            _parent="ogru", dmgplus1=999, defType="fort", collision=10.0000, Name="Tom Green", 
            file="units\\creeps\\Zombie\\Zombie.mdl", HP=150, def=6.0000, 
        },
        o00K={
            Harea1=40, _parent="owtw", points=900, atkType1="chaos", 
            Missileart_1="Abilities\\Weapons\\SpiritOfVengeanceMissile\\SpiritOfVengeanceMissile.mdl", 
            targs1="air,enemies,ground", splashTargs1="air,enemies,ground", Trains="o00I", lumbercost=0, Qarea1=60, 
            file="units\\human\\HeroArchMage\\HeroArchMage.mdl", sides1=75, Tip="Build |cffffcc00B|rob Barker", 
            bldtm=1, Missilespeed_1=3000, dice1=3, preventPlace="unwalkable", Missilearc_1=0.6500, goldcost=800, 
            MissileHoming_1=1, Art="ReplaceableTextures\\CommandButtons\\BTNHeroArchMage.blp", Requires="", 
            dmgplus1=747, acquire=10000.0000, rangeN1=10000, Name="Bob Barker", Hotkey="B", Farea1=20, cool1=0.1700, 
            Ubertip="\"Now, you've had enough... bitch.\" This tower has incredible range with a touch of splash.", 
        },
        o00R={
            Harea1=60, _parent="owtw", blue=50, atkType1="normal", 
            Missileart_1="Abilities\\Weapons\\MeatwagonMissile\\MeatwagonMissile.mdl", 
            splashTargs1="air,enemies,ground,notself,organic", Trains="o00I", green=50, Qarea1=75, 
            file="units\\orc\\Shaman\\Shaman.mdl", Tip="Build |cffffcc00N|razo", bldtm=1, lumbercost=0, 
            preventPlace="unwalkable", red=50, points=30, sides1=39, 
            Art="ReplaceableTextures\\CommandButtons\\BTNShaman.blp", Requires="", goldcost=40, acquire=800.0000, 
            dmgplus1=1, Name="Nazo", Hotkey="N", Farea1=55, cool1=0.4000, 
            Ubertip="\"Fish! Pony! Hip, Hip Hop, Hip Hop anonymous? Damn you! You gave him the easy ones.\"", 
        },
        o00U={
            _parent="owtw", abilList="A006,Abds,Arbr,Aspi", blue=50, atkType1="normal", dmgplus1=59, Trains="o00I", 
            green=50, targs1="air,enemies,ground", file="units\\creeps\\OrcWarlock\\OrcWarlock.mdl", 
            Tip="Build |cffffcc00U|rla", bldtm=1, preventPlace="unwalkable", points=30, red=50, sides1=1, 
            Art="ReplaceableTextures\\CommandButtons\\BTNOrcWarlock.blp", Requires="", lumbercost=0, acquire=800.0000, 
            goldcost=50, Name="Ula", Hotkey="U", 
            Ubertip="Ula: [dressed up as Lucy, with a coconut bra on] Aquariums make me super horny! ", 
            cool1=0.4000, Missileart_1="Abilities\\Spells\\Undead\\PlagueCloud\\PlagueCloudCaster.mdl", 
        },
        o016={
            _parent="owtw", points=75, atkType1="hero", dmgplus1=49, Trains="o00I", lumbercost=0, 
            targs1="air,enemies,ground", file="units\\orc\\HeroShadowHunter\\HeroShadowHunter.mdl", 
            Tip="Build |cffffcc00C|rrazy Eyes", bldtm=1, preventPlace="unwalkable", sides1=8, 
            Art="ReplaceableTextures\\CommandButtons\\BTNShadowHunter.blp", Requires="", 
            Ubertip="\"I watch the stock market channel all the time - I just watch because I suspect that anchor man of being an evil leprechaun... he can bullshit everybody else, but he ain't fooling me.\"", 
            rangeN1=750, Name="Crazy Eyes", Hotkey="C", 
            Missileart_1="Abilities\\Weapons\\AvengerMissile\\AvengerMissile.mdl", cool1=0.0500, goldcost=90, 
        },
        h006={
            dice1=1, defUp=22.0000, dmgplus1=999, collision=10.0000, Name="Patrick Stewart", 
            file="units\\undead\\Tichondrius\\Tichondrius.mdl", _parent="hrif", HP=3750, def=5.0000, 
        },
        o00P={
            _parent="owtw", points=300, atkType1="normal", dmgplus1=0, Trains="o00I", lumbercost=0, 
            file="units\\undead\\HeroDreadLord\\HeroDreadLord.mdl", Tip="Build |cffffcc00E|rric", bldtm=1, dice1=14, 
            preventPlace="unwalkable", sides1=100, Art="ReplaceableTextures\\CommandButtons\\BTNHeroDreadLord.blp", 
            Requires="", goldcost=400, acquire=1000.0000, rangeN1=1000, Name="Eric", Hotkey="E", 
            Ubertip="\"Oh, gross... did you see that guys balls?\"  \"Yeah... they were weird looking.\"", 
            cool1=0.4000, Missileart_1="Abilities\\Weapons\\SkeletalMageMissile\\SkeletalMageMissile.mdl", 
        },
        u001={
            _parent="uaco", spd=522, abilList="Avul", atkType1="unknown", Builds="o000,o00O,o002,o001,o00P,o00Q", 
            Art="ReplaceableTextures\\CommandButtons\\BTNHeroPaladin.blp", moveHeight=200.0000, goldcost=0, 
            Ubertip="Builds units from Billy Madison.  These towers have sporadic attacks.", 
            file="units\\human\\HeroPaladin\\HeroPaladin.mdl", Name="Brian Madison", Hotkey="B", movetp="fly", 
            Tip="|cffffcc00B|rrian Madison", bldtm=1, 
        },
        o00G={
            _parent="otau", sides1=1, dmgplus1=999, collision=10.0000, def=7.0000, 
            file="units\\nightelf\\DruidoftheClaw\\DruidoftheClaw.mdl", HP=12000, Name="Sean Connery", 
        },
        h001={
            _parent="hfoo", dmgplus1=999, defType="normal", collision=10.0000, Name="Carrot Top", 
            file="units\\human\\Sorceress\\Sorceress_V1.mdl", HP=20, def=1.0000, 
        },
        h003={
            _parent="hfoo", dmgplus1=999, defType="medium", collision=10.0000, Name="William Shatner", 
            file="units\\creeps\\OgreOneHeaded\\OgreOneHeaded.mdl", HP=95, def=3.0000, 
        },
        o013={
            Harea1=120, _parent="owtw", abilList="A001", points=120, atkType1="siege", 
            Missileart_1="abilities\\weapons\\catapult\\catapultmissile.mdl", 
            splashTargs1="air,enemies,ground,notself,organic", Trains="o00I", lumbercost=0, Qarea1=150, 
            file="units\\human\\Sorceress\\Sorceress_V1.mdl", Tip="Build |cffffcc00C|rorinne", bldtm=1, 
            weapTp1="msplash", unitSound="Sorceress", preventPlace="unwalkable", targs1="enemies,ground", sides1=10, 
            armor="Stone", Art="ReplaceableTextures\\CommandButtons\\BTNSorceress.blp", Requires="", goldcost=180, 
            acquire=1000.0000, dmgplus1=124, Name="Corinne Maloney", Hotkey="C", Farea1=100, cool1=0.4000, 
            Ubertip="\"We wasted the good surprise on you!\"", 
        },
        u000={
            _parent="uaco", abilList="Avul", atkType1="unknown", type="peon", Tip="Build |cffffcc00S|rcuba Steve", 
            bldtm=1, moveHeight=200.0000, Builds="o005,o00R,o00S,o013,o004", 
            Art="ReplaceableTextures\\CommandButtons\\BTNSpellBreaker.blp", Ubertip="Builds units from Big Daddy", 
            file="units\\human\\BloodElfSpellThief\\BloodElfSpellThief.mdl", Name="Scuba Steve", Hotkey="S", 
            movetp="fly", goldcost=0, spd=522, 
        },
        owtw={
            goldcost=7, abilList="", dmgplus1=1, Requires="", lumbercost=0, Name="Giant Penguin", 
            file="units\\critters\\Penguin\\Penguin.mdl", Tip="Build |cffffcc00G|riant Penguin", _parent="owtw", 
        },
        o00I={
            _parent="ogru", Art="ReplaceableTextures\\CommandButtons\\BTNPillage.blp", goldcost=0, 
            Ubertip="Simply put, you use this and it sells this tower for 75% of its original cost.", fused=0, 
            Name="Sell", Hotkey="E", Tip="S|cffffcc00e|rll this tower.", HP=1, bldtm=1, 
        },
        o00D={
            _parent="otau", sides1=1, dmgplus1=999, defType="normal", collision=10.0000, Name="Nicholas Cage", 
            file="units\\creeps\\HumanMage\\HumanMage.mdl", HP=7000, def=7.0000, 
        },
        o00E={
            _parent="otau", sides1=1, dmgplus1=999, defType="small", collision=10.0000, Name="Angelina Jolie", 
            file="units\\creeps\\assassin\\assassin.mdl", HP=8500, def=6.0000, 
        },
        o00B={
            _parent="ogru", dmgplus1=999, defType="hero", collision=10.0000, Name="Barbra Streisand", 
            file="units\\undead\\Banshee\\Banshee.mdl", modelScale=2.1000, HP=6000, def=10.0000, 
        },
        e000={
            _parent="esen", abilList="Aesn,Amgl,Aien,Ault", dmgplus1=999, defType="medium", collision=10.0000, def=7.0000, 
            file="units\\creeps\\OrcWarlock\\OrcWarlock.mdl", HP=1400, Name="Robert De Niro", 
        },
        o012={
            _parent="owtw", points=250, atkType1="chaos", dmgplus1=323, Trains="o00I", lumbercost=0, 
            file="units\\creeps\\Bandit\\Bandit.mdl", Tip="Build |cffffcc00D|rave", bldtm=1, dice1=3, 
            preventPlace="unwalkable", sides1=5, Art="ReplaceableTextures\\CommandButtons\\BTNBandit.blp", 
            Requires="", 
            Ubertip="\"Dave Buznik: Look everybody, Pana Banana's got a heinie! He's got a heinie! \"", 
            rangeN1=450, Name="Dave", Hotkey="D", Missileart_1="Abilities\\Weapons\\GlaiveMissile\\GlaiveMissile.mdl", 
            goldcost=300, 
        },
        h000={
            _parent="htow", preventPlace="unwalkable", abilList="Avul", Trains="u005,u004,u003,u000,u001,u002", fmade=2, 
            Researches="", Name="Movie Selector", Upgrade="", 
        },
        n000={
            _parent="nglm", Name="Flaming Poop Bag", file="Objects\\InventoryItems\\Rune\\Rune.mdl", 
            Art="ReplaceableTextures\\CommandButtons\\BTNDustOfAppearance.blp", modelScale=0.4000, 
        },
        o000={
            _parent="owtw", lumberRep=0, atkType1="magic", 
            Missileart_1="Abilities\\Spells\\Other\\FrostBolt\\FrostBoltMissile.mdl", Trains="o00I", lumbercost=0, 
            file="units\\critters\\Penguin\\Penguin.mdl", Tip="Build |cffffcc00G|riant Penguin", bldtm=1, 
            preventPlace="unwalkable", sides1=10, Art="ReplaceableTextures\\CommandButtons\\BTNPenguin.blp", 
            Requires="", points=6, Ubertip="\"It's too damn hot for a penguin to be just walkin' around.\"", 
            rangeN1=700, Name="Giant Penguin", Hotkey="G", modelScale=2.2500, dmgplus1=0, goldcost=8, 
        },
        o00J={
            goldcost=200, lumberRep=0, atkType1="siege", dmgplus1=299, Trains="o00I", lumbercost=0, 
            file="Units\\Creeps\\PandarenBrewmaster\\PandarenBrewmaster.mdl", 
            Tip="Build |cffffcc00S|rhooter McGavin", bldtm=1, preventPlace="unwalkable", 
            Ubertip="\"I eat pieces of shit like you for breakfast.\"", sides1=50, 
            Art="ReplaceableTextures\\CommandButtons\\BTNPandarenBrewmaster.blp", Requires="", points=168, 
            acquire=3000.0000, rangeN1=3000, Name="Shooter McGavin", Hotkey="S", 
            Missileart_1="abilities\\weapons\\DemolisherMissile\\DemolisherMissile.mdl", cool1=0.5500, 
            _parent="owtw", 
        },
        o00F={
            _parent="otau", sides1=1, dmgplus1=999, defType="medium", collision=10.0000, Name="Mel Gibson", 
            file="units\\orc\\Thrall\\Thrall.mdl", HP=10000, def=5.0000, 
        },
        u005={
            _parent="uaco", abilList="Avul", atkType1="unknown", spd=522, Builds="o014,o015,o016,o017,o018", 
            moveHeight=200.0000, goldcost=0, Name="Mr. Deeds", Hotkey="D", movetp="fly", Tip="Mr. |cffffcc00D|reeds", 
            bldtm=1, 
        },
        o00H={
            _parent="otau", sides1=1, dmgplus1=999, defType="hero", collision=10.0000, red=100, Name="Samuel L. Jackson", 
            file="units\\demon\\Kiljaeden\\Kiljaeden.mdl", modelScale=2.7500, HP=50000, def=10.0000, 
        },
        o00V={
            goldcost=175, abilList="A00C,A007,Abds,Arbr,Aspi", points=131, 
            Missileart_1="Abilities\\Weapons\\Banditmissile\\Banditmissile.mdl", Trains="o00I", lumbercost=0, 
            file="units\\orc\\Grunt\\Grunt.mdl", Tip="Build |cffffcc00D|roug", bldtm=1, preventPlace="unwalkable", 
            sides1=1, Art="ReplaceableTextures\\CommandButtons\\BTNGrunt.blp", Requires="", 
            Ubertip="\"Doug: Well, I may not able to kick your ath but my thithter thure can.\" Very weak but can give out steroids.", 
            rangeN1=900, Name="Doug", Hotkey="D", dmgplus1=59, _parent="owtw", 
        },
        e001={
            _parent="esen", abilList="Aesn,Amgl,Aien,Ault", dmgplus1=999, defType="large", collision=10.0000, def=5.0000, 
            file="units\\other\\DalaranMutant\\DalaranMutant.mdl", HP=1700, Name="Matt Damon", 
        },
        o00N={
            Harea1=35, _parent="owtw", abilList="A004", points=45, atkType1="siege", 
            Missileart_1="units\\human\\WarWagon\\WarWagon_V1.mdl", splashTargs1="air,enemies,ground", 
            Trains="o00I", lumbercost=0, Qarea1=50, file="units\\creeps\\Zombie\\Zombie.mdl", 
            targs1="air,enemies,ground", Tip="Build |cffffcc00D|ronald", bldtm=1, targCount1=0, 
            preventPlace="unwalkable", sides1=16, dmgplus1=19, MissileHoming_1=1, 
            Art="ReplaceableTextures\\CommandButtons\\BTNZombie.blp", Requires="", goldcost=60, acquire=1200.0000, 
            rangeN1=1200, Name="Donald", Hotkey="D", Farea1=20, cool1=0.5700, 
            Ubertip="\"You suck! Ya Jackass!\" This tower runs the enemy over with his car.", 
        },
        o00A={defType="medium", collision=10.0000, def=9.0000, Name="Ray Romano", dmgplus1=999, HP=320, _parent="ogru"}, 
        u008={
            dice1=1, defUp=13.0000, dmgplus1=999, defType="normal", collision=10.0000, sides1=1, Name="Jon Stewart", 
            file="units\\other\\BloodElfLieutenant\\BloodElfLieutenant.mdl", _parent="ugho", HP=800, def=6.0000, 
        },
        o00Y={
            _parent="owtw", abilList="A00A,Abds,Arbr,Aspi", points=3, dmgplus1=3, splashTargs1="air,enemies,ground", 
            Trains="o00I", lumbercost=0, targs1="air,enemies,ground", file="units\\creeps\\IceTroll\\IceTroll.mdl", 
            Tip="Build |cffffcc00N|rate", bldtm=1, preventPlace="unwalkable", sides1=1, 
            Art="ReplaceableTextures\\CommandButtons\\BTNIceTrollBeserker.blp", Requires="", 
            Ubertip="\"Nate: Oh, it's perfectely fine Mr. Rydell. I got it under control. See? Iverson just missed the shot, the Sixers lose. Who cares?... THE ANGER SHARKS ARE SWIMMING MY HEAD. YOU GOTTA DUNK THAT SHIT! YOU GOTTA DUNK THAT SHIT!\"", 
            rangeN1=450, Name="Nate", Hotkey="N", 
            Missileart_1="Abilities\\Weapons\\VoidWalkerMissile\\VoidWalkerMissile.mdl", cool1=0.5000, goldcost=5, 
        },
        o00T={
            Harea1=40, _parent="owtw", abilList="A00C,Abds,Arbr,Aspi", points=7, atkType1="normal", dmgplus1=20, 
            splashTargs1="air,enemies,ground", Trains="o00I", lumbercost=0, Qarea1=50, 
            file="units\\human\\HeroBloodElf\\HeroBloodElf.mdl", Tip="Build 10 Second |cffffcc00T|rom", bldtm=1, 
            preventPlace="unwalkable", unitSound="Peasant", 
            Art="ReplaceableTextures\\CommandButtons\\BTNHeroBloodElfPrince.blp", Requires="", 
            targs1="air,enemies,ground", goldcost=10, rangeN1=750, Name="10 Second Tom", Hotkey="T", Farea1=30, 
            cool1=2.0000, Missileart_1="Abilities\\Weapons\\WingedSerpentMissile\\WingedSerpentMissile.mdl", 
        },
        e002={
            _parent="esen", abilList="Aesn,Amgl,Aien,Ault", dmgplus1=999, defType="fort", collision=10.0000, def=6.0000, 
            file="units\\creeps\\HighElfArcher\\HighElfArcher.mdl", HP=2000, Name="Johnny Depp", 
        },
        o008={
            _parent="ogru", dmgplus1=999, defType="normal", collision=10.0000, Name="Jerry Seinfeld", 
            file="units\\other\\Dranai\\Dranai.mdl", HP=200, def=7.0000, 
        },
        u007={
            dice1=1, sides1=1, dmgplus1=999, defType="fort", collision=10.0000, Name="Sandra Bullock", 
            file="units\\critters\\VillagerWoman\\VillagerWoman.mdl", _parent="ugho", HP=600, def=7.0000, 
        },
        u006={
            _parent="ugho", blue=40, sides1=1, dmgplus1=999, red=40, collision=10.0000, green=40, Name="Will Smith", 
            file="units\\critters\\VillagerMan1\\VillagerMan1.mdl", def=5.0000, HP=475, dice1=1, 
        },
        o00M={
            _parent="owtw", points=7, atkType1="normal", dmgplus1=5, Trains="o00I", lumbercost=0, 
            file="units\\orc\\Peon\\Peon.mdl", Tip="Build |cffffcc00J|rack Beard", bldtm=1, preventPlace="unwalkable", 
            sides1=4, Art="ReplaceableTextures\\CommandButtons\\BTNPeon.blp", Requires="", 
            Ubertip="\"Looks like a slight hill. What do you think?  \"And a slant to the left.\"   \"Nah, it looks that way cause you've only got one shoe on.", 
            rangeN1=1200, Name="Jack Beard", Hotkey="J", acquire=1200.0000, goldcost=10, 
        },
        o011={
            Harea1=40, _parent="owtw", abilList="A00B,Abds,Arbr,Aspi", points=165, atkType1="normal", dmgplus1=179, 
            splashTargs1="air,enemies,ground", Trains="o00I", lumbercost=0, Qarea1=50, 
            file="units\\other\\DranaiMage\\DranaiMage.mdl", Tip="Build Buddy R|cffffcc00y|rdell", bldtm=1, 
            preventPlace="unwalkable", unitSound="GoblinSapper", sides1=1, 
            Art="ReplaceableTextures\\CommandButtons\\BTNDranaiMage.blp", Requires="", targs1="air,enemies,ground", 
            goldcost=190, rangeN1=450, Name="Buddy Rydell", Hotkey="Y", Farea1=30, cool1=2.0000, 
            Missileart_1="Abilities\\Weapons\\WingedSerpentMissile\\WingedSerpentMissile.mdl", 
        },
        h008={
            dice1=1, defUp=24.0000, dmgplus1=999, defType="fort", collision=10.0000, Name="Ben Stiller", 
            file="units\\human\\Peasant\\Peasant.mdl", _parent="hrif", HP=5500, def=5.0000, 
        },
        h002={
            defType="small", collision=10.0000, dmgplus1=999, Name="Keanu Reeves", 
            file="units\\nightelf\\HeroDemonHunter\\HeroDemonHunter.mdl", HP=45, _parent="hfoo", 
        },
        o018={
            _parent="owtw", points=215, atkType1="hero", dmgplus1=119, Trains="o00I", lumbercost=0, 
            targs1="air,enemies,ground", file="units\\critters\\VillagerMan\\VillagerMan.mdl", 
            Tip="Build |cffffcc00L|rongfellow Deeds", bldtm=1, preventPlace="unwalkable", sides1=21, 
            Art="ReplaceableTextures\\CommandButtons\\BTNVillagerMan.blp", Requires="", rangeN1=750, 
            Name="Longfellow Deeds", Hotkey="L", 
            Missileart_1="Abilities\\Spells\\Other\\FrostBolt\\FrostBoltMissile.mdl", cool1=0.0500, goldcost=240, 
        },
        u004={
            _parent="uaco", spd=522, abilList="Avul", atkType1="unknown", Builds="o00T,o00U,o00W,o00V,o00X", 
            Art="ReplaceableTextures\\CommandButtons\\BTNDruidOfTheClaw.blp", moveHeight=200.0000, goldcost=0, 
            Ubertip="Builds units from 50 First Dates.  These towers excel in slowing units. (not fully balanced)", 
            file="units\\nightelf\\DruidoftheClaw\\DruidoftheClaw.mdl", Name="Marlin", Hotkey="M", movetp="fly", 
            Tip="|cffffcc00M|rarlin", bldtm=1, 
        },
        o00W={
            auto="A003", _parent="owtw", abilList="A00C", lumberRep=0, atkType1="normal", Missileart_1=".mdl", 
            Trains="o00I", lumbercost=0, targs1="air,enemies,ground", file="units\\nightelf\\Runner\\Runner.mdl", 
            Tip="Build |cffffcc00L|rucy", bldtm=1, preventPlace="unwalkable", sides1=1, 
            Art="ReplaceableTextures\\CommandButtons\\BTNNightElfRunner.blp", Requires="", points=94, 
            acquire=500.0000, rangeN1=100, Name="Lucy", Hotkey="L", goldcost=120, cool1=0.3000, dmgplus1=64, 
        },
        o009={
            _parent="ogru", dmgplus1=999, defType="small", collision=10.0000, Name="Drew Carey", 
            file="Units\\Creeps\\tuskar\\tuskar.mdl", HP=255, def=8.0000, 
        },
        u002={
            _parent="uaco", spd=522, abilList="Avul", atkType1="unknown", Builds="o00M,o00N,o00L,o00J,o003,o00K", 
            Art="ReplaceableTextures\\CommandButtons\\BTNVillagerWoman.blp", moveHeight=200.0000, goldcost=0, 
            Ubertip="Builds units from Happy Gilmore.  These towers excel in range. (not balanced)", 
            file="units\\critters\\VillagerWoman\\VillagerWoman.mdl", Name="Virginia", Hotkey="V", movetp="fly", 
            Tip="Build |cffffcc00V|rirginia", bldtm=1, 
        },
        o001={
            _parent="owtw", points=131, dmgplus1=0, Trains="o00I", lumbercost=0, 
            file="units\\critters\\HighElfPeasant\\HighElfPeasant.mdl", Tip="Build |cffffcc00C|rarl", bldtm=1, 
            dice1=3, preventPlace="unwalkable", sides1=95, 
            Art="ReplaceableTextures\\CommandButtons\\BTNBloodElfPeasant.blp", Requires="", 
            Ubertip="\"He did that little weasel laugh he does.  You know, Hee-Hee-Hee-Hee-Hee-Hee.\"", 
            rangeN1=900, Name="Carl", Hotkey="C", 
            Missileart_1="Abilities\\Weapons\\FaerieDragonMissile\\FaerieDragonMissile.mdl", goldcost=175, 
        },
        o002={
            Harea1=45, _parent="owtw", abilList="A005,Abds,Arbr,Aspi", points=60, atkType1="siege", 
            Missileart_1="Abilities\\Weapons\\FragDriller\\FragDriller.mdl", splashTargs1="air,enemies,ground", 
            Trains="o00I", lumbercost=0, Qarea1=60, file="units\\human\\MortarTeam\\MortarTeam.mdl", 
            Tip="Build |cffffcc00F|rrank and Jack", bldtm=1, dice1=2, preventPlace="unwalkable", sides1=60, 
            Art="ReplaceableTextures\\CommandButtons\\BTNMortarTeam.blp", Requires="", targs1="air,enemies,ground", 
            Ubertip="\"When I graduated from first grade, all my dad did was tell me to get a job.\" Frank and Jack are able to set flaming bags of \"poop\" for the enemy to step on and have a little splash.", 
            goldcost=80, Name="Frank and Jack", Hotkey="F", dmgplus1=0, cool1=0.5000, Farea1=30, 
        },
        o005={
            Harea1=40, _parent="owtw", points=7, atkType1="normal", dmgplus1=5, splashTargs1="air,enemies,ground", 
            Trains="o00I", lumbercost=0, Qarea1=50, file="units\\critters\\VillagerKid\\VillagerKid.mdl", 
            Tip="Build |cffffcc00J|rulien", bldtm=1, preventPlace="unwalkable", unitSound="VillagerKid", 
            Art="ReplaceableTextures\\CommandButtons\\BTNVillagerKid.blp", Requires="", targs1="air,enemies,ground", 
            Ubertip="Julian is able to both pee and throw-up on the enemies.", rangeN1=750, Name="Julien", Hotkey="J", 
            goldcost=10, Farea1=30, Missileart_1="Objects\\Spawnmodels\\Demon\\DemonBlood\\DemonBloodPitlord.mdl", 
        },
        o00S={
            Harea1=80, _parent="owtw", points=60, atkType1="siege", 
            Missileart_1="abilities\\weapons\\catapult\\catapultmissile.mdl", splashTargs1="air,enemies,ground", 
            Trains="o00I", lumbercost=0, Qarea1=90, file="Units\\Critters\\Shoveler\\Shoveler.mdl", 
            Tip="Build |cffffcc00H|romeless Guy", bldtm=1, preventPlace="unwalkable", sides1=1, 
            Art="ReplaceableTextures\\CommandButtons\\BTNKobold.blp", Requires="", targs1="air,enemies,ground", 
            goldcost=80, Name="Homeless Guy", Hotkey="F", Farea1=75, cool1=0.5000, dmgplus1=59, 
        },
        h009={
            dice1=0, defUp=25.0000, dmgplus1=1000, defType="fort", collision=50.0000, Name="Harrison Ford", _parent="hgry", 
            HP=4000, def=10.0000, 
        },
        o006={
            _parent="owyv", Art="ReplaceableTextures\\CommandButtons\\BTNHarpy.blp", defType="none", 
            collision=50.0000, dmgplus1=1000, Name="Meryl Streep", def=5.0000, HP=105, dice1=0, 
        },
        e003={
            _parent="esen", abilList="Aesn,Amgl,Aien,Ault", dmgplus1=999, defType="normal", collision=10.0000, def=5.0000, 
            file="units\\human\\Knight\\Knight.mdl", HP=2500, Name="John Travolta", 
        },
        o00L={
            auto="A003", _parent="owtw", abilList="A003", lumberRep=0, atkType1="magic", dmgplus1=79, Trains="o00I", 
            lumbercost=0, file="units\\creeps\\SasquatchShaman\\SasquatchShaman.mdl", 
            Tip="Build |cffffcc00C|rhubbs", bldtm=1, preventPlace="unwalkable", goldcost=120, sides1=30, 
            Art="ReplaceableTextures\\CommandButtons\\BTNSasquatchShaman.blp", Requires="", points=94, 
            acquire=2000.0000, rangeN1=2000, Name="Chubbs", Hotkey="C", 
            Ubertip="\"HELL no. Damn alligator bit my hand off!\"", cool1=0.5000, 
            Missileart_1="Abilities\\Spells\\Items\\AIso\\AIsoTarget.mdl", 
        },
        o00Q={
            Harea1=40, _parent="owtw", points=600, atkType1="chaos", 
            Missileart_1="Abilities\\Weapons\\LordofFlameMissile\\LordofFlameMissile.mdl", 
            splashTargs1="air,enemies,ground", Trains="o00I", lumbercost=0, Qarea1=150, 
            file="units\\creeps\\BanditLord\\BanditLord.mdl", Tip="Build |cffffcc00B|rilly Madison", bldtm=1, 
            dice1=20, preventPlace="unwalkable", targs1="air,enemies,ground", sides1=100, 
            Art="ReplaceableTextures\\CommandButtons\\BTNBanditLord.blp", Requires="", goldcost=800, 
            acquire=1500.0000, rangeN1=1500, Name="Billy Madison", Hotkey="B", dmgplus1=0, cool1=0.4000, 
            Ubertip="\"T-T-T-TODAY JUNIOR!\" Has good splash damage.", 
        },
        h005={
            dice1=1, defUp=21.0000, dmgplus1=999, defType="small", collision=10.0000, modelScale=1.4500, Name="Brad Pitt", 
            file="units\\human\\Footman\\Footman.mdl", _parent="hrif", HP=3250, def=6.0000, 
        },
        o003={
            _parent="owtw", points=338, atkType1="chaos", dmgplus1=547, Trains="o00I", lumbercost=0, 
            file="units\\human\\HeroPaladin\\HeroPaladin.mdl", Tip="Build Happy |cffffcc00G|rilmore", bldtm=1, 
            dice1=3, preventPlace="unwalkable", Missilearc_1=0.5000, sides1=100, 
            Art="ReplaceableTextures\\CommandButtons\\BTNHeroPaladin.blp", Requires="", goldcost=350, 
            acquire=4000.0000, rangeN1=4000, Name="Happy Gilmore", Hotkey="G", 
            Ubertip="\"Why don't you just go home? That's your home! Are you too good for your home?\"", 
            cool1=0.7000, Missileart_1="Abilities\\Weapons\\DemonHunterMissile\\DemonHunterMissile.mdl", 
        },
        o00O={
            _parent="owtw", blue=50, atkType1="normal", dmgplus1=0, Trains="o00I", green=50, 
            file="units\\creeps\\Wendigo\\Wendigo.mdl", Tip="Build |cffffcc00J|ruanita", bldtm=1, 
            preventPlace="unwalkable", points=30, red=50, sides1=70, 
            Art="ReplaceableTextures\\CommandButtons\\BTNWendigo.blp", Requires="", lumbercost=0, acquire=800.0000, 
            goldcost=40, Name="Juanita", Hotkey="J", 
            Ubertip="\"If you're gonna stay home today, you can help me shave my armpits.\"", cool1=0.4000, 
            Missileart_1="Abilities\\Weapons\\BrewmasterMissile\\BrewmasterMissile.mdl", 
        },
        o014={
            goldcost=10, blue=50, atkType1="hero", dmgplus1=4, Trains="o00I", green=25, targs1="air,enemies,ground", 
            file="units\\critters\\VillagerMan1\\VillagerMan1.mdl", Tip="Build |cffffcc00E|rmilio", bldtm=1, 
            preventPlace="unwalkable", lumbercost=0, red=50, sides1=4, 
            Art="ReplaceableTextures\\CommandButtons\\BTNVillagerMan1.blp", Requires="", points=7, 
            Ubertip="\"The hideousness of that foot will haunt my dreams forever.\" Emilio throws fire pokers.", 
            rangeN1=750, Name="Emilio", Hotkey="E", 
            Missileart_1="Abilities\\Weapons\\Banditmissile\\Banditmissile.mdl", cool1=0.0500, _parent="owtw", 
        },
    },
    keys={
        _parent="单位类别", Missileart_2="攻击 2 - 投射物图像", atkType1="攻击 1 - 攻击类型", 
        Farea2="攻击 2 - 全伤害范围", weapsOn="允许攻击模式", Researches="可研究项目", 
        file="模型文件", Harea2="攻击 2 - 中伤害范围", dice1="攻击 1 - 伤害骰子数量", 
        MissileHoming_1="攻击 1 - 射弹自导允许", collision="碰撞体积", fmade="提供人口", 
        Name="名字", lumberRep="修理木材消耗", targs2="攻击 2 - 目标允许", 
        splashTargs1="攻击 1 - 范围影响目标", def="基础护甲", type="单位类别", 
        Tip="提示工具 - 基础", weapTp1="攻击 1 - 武器类型", upgrades="使用科技", Hotkey="热键", 
        Harea1="攻击 1 - 中伤害范围", red="颜色值(红)", abilList="普通", 
        Missileart_1="攻击 1 - 投射物图像", cool2="攻击 2 - 攻击间隔", 
        Qarea1="攻击 1 - 小伤害范围", weapType1="攻击 1 - 武器声音", bldtm="建造时间", 
        sides2="攻击 2 - 伤害骰子面数", moveHeight="高度", preventPlace="放置要求", 
        spd="基础速度", green="颜色值(绿)", Builds="可建造建筑", 
        targCount2="攻击 2 -最大目标数", Requires="需求", Missilearc_2="攻击 2 - 射弹弧度", 
        acquire="主动攻击范围", rangeN1="攻击 1 - 攻击范围", Upgrade="建筑升级", 
        Qarea2="攻击 2 - 小伤害范围", movetp="类型", weapType2="攻击 2 - 武器声音", 
        blue="颜色值(蓝)", auto="默认主动技能", dmgplus2="攻击 2 - 基础伤害", 
        targCount1="攻击 1 -最大目标数", Missilespeed_1="攻击 1 - 射弹速率", fused="占用人口", 
        dmgplus1="攻击 1 - 基础伤害", unitSound="单位声音设置", 
        sides1="攻击 1 - 伤害骰子面数", modelScale="模型缩放", Trains="训练单位", 
        lumbercost="木材消耗", targs1="攻击 1 - 目标允许", Ubertip="提示工具 - 扩展", 
        Missilespeed_2="攻击 2 - 射弹速率", Art="图标 - 游戏界面", 
        RngBuff2="攻击 2 - 攻击范围缓冲", Farea1="攻击 1 - 全伤害范围", 
        dmgpt2="攻击 2 - 动画伤害点", rangeN2="攻击 2 - 攻击范围", 
        Missilearc_1="攻击 1 - 射弹弧度", defType="护甲类型", defUp="防御升级奖励", 
        armor="装甲类型", atkType2="攻击 2 - 攻击类型", weapTp2="攻击 2 - 武器类型", 
        backSw2="攻击 2 - 动画回复点", goldcost="黄金消耗", dice2="攻击 2 - 伤害骰子数量", 
        HP="生命最大值", stockMax="最大库存量", cool1="攻击 1 - 攻击间隔", 
        points="单位附加值", 
    },
    category="unit", 
}