return {
    keys={
        upgrades="使用科技", dmgpt2="攻击 2 - 动画伤害点", bldtm="建造时间", 
        backSw2="攻击 2 - 动画回复点", targs2="攻击 2 - 目标允许", 
        atkType2="攻击 2 - 攻击类型", abilList="普通", stockMax="最大库存量", 
        weapsOn="允许攻击模式", Ubertip="提示工具 - 扩展", acquire="主动攻击范围", 
        movetp="类型", preventPlace="放置要求", weapType2="攻击 2 - 武器声音", defType="护甲类型", 
        Tip="提示工具 - 基础", auto="默认主动技能", def="基础护甲", 
        Farea1="攻击 1 - 全伤害范围", Harea1="攻击 1 - 中伤害范围", 
        sides2="攻击 2 - 伤害骰子面数", fused="占用人口", dmgplus1="攻击 1 - 基础伤害", 
        Name="名字", green="颜色值(绿)", HP="生命最大值", defUp="防御升级奖励", 
        dice1="攻击 1 - 伤害骰子数量", goldcost="黄金消耗", spd="基础速度", 
        Upgrade="建筑升级", Qarea2="攻击 2 - 小伤害范围", RngBuff2="攻击 2 - 攻击范围缓冲", 
        cool1="攻击 1 - 攻击间隔", lumbercost="木材消耗", Qarea1="攻击 1 - 小伤害范围", 
        armor="装甲类型", collision="碰撞体积", sides1="攻击 1 - 伤害骰子面数", 
        fmade="提供人口", _parent="单位类别", Farea2="攻击 2 - 全伤害范围", moveHeight="高度", 
        file="模型文件", Hotkey="热键", Harea2="攻击 2 - 中伤害范围", 
        rangeN2="攻击 2 - 攻击范围", splashTargs1="攻击 1 - 范围影响目标", 
        targCount1="攻击 1 -最大目标数", lumberRep="修理木材消耗", 
        Missilespeed_1="攻击 1 - 射弹速率", MissileHoming_1="攻击 1 - 射弹自导允许", 
        red="颜色值(红)", type="单位类别", Art="图标 - 游戏界面", 
        atkType1="攻击 1 - 攻击类型", Requires="需求", Trains="训练单位", 
        weapTp2="攻击 2 - 武器类型", points="单位附加值", unitSound="单位声音设置", 
        Researches="可研究项目", targCount2="攻击 2 -最大目标数", 
        Missilearc_1="攻击 1 - 射弹弧度", blue="颜色值(蓝)", dmgplus2="攻击 2 - 基础伤害", 
        dice2="攻击 2 - 伤害骰子数量", Builds="可建造建筑", 
        Missileart_1="攻击 1 - 投射物图像", Missileart_2="攻击 2 - 投射物图像", 
        targs1="攻击 1 - 目标允许", cool2="攻击 2 - 攻击间隔", 
        Missilearc_2="攻击 2 - 射弹弧度", Missilespeed_2="攻击 2 - 射弹速率", 
        modelScale="模型缩放", weapTp1="攻击 1 - 武器类型", rangeN1="攻击 1 - 攻击范围", 
        weapType1="攻击 1 - 武器声音", 
    },
    items={
        o010={
            goldcost=75, preventPlace="unwalkable", Art="ReplaceableTextures\\CommandButtons\\BTNShadowHunter.blp", 
            cool1=0.4000, bldtm=1, Requires="", Trains="o00I", points=60, abilList="A008,Abds,Arbr,Aspi", 
            file="units\\orc\\HeroShadowHunter\\HeroShadowHunter.mdl", Tip="Build |cffffcc00C|rhuck", blue=50, 
            sides1=4, red=50, rangeN1=450, 
            Missileart_1="Abilities\\Weapons\\BrewmasterMissile\\BrewmasterMissile.mdl", lumbercost=0, 
            targs1="air,enemies,ground", _parent="owtw", Name="Chuck", green=50, 
            Ubertip="Chuck: Here's my phone number. [Dave reads it] Dave Buznik: You're gonna die, bitch? Chuck: Oh, sorry. That's a letter I'm writing to Geraldo Rivera ", 
            acquire=800.0000, Hotkey="C", dmgplus1=90, 
        },
        h007={
            dice1=1, def=7.0000, defType="large", sides1=1, _parent="hrif", Name="Halle Berry", collision=10.0000, 
            dmgplus1=999, file="units\\nightelf\\Vengeance\\Vengeance.mdl", HP=4500, defUp=23.0000, 
        },
        o00E={
            type="", def=6.0000, defType="small", dmgplus1=999, Name="Angelina Jolie", _parent="otau", collision=10.0000, 
            file="units\\creeps\\assassin\\assassin.mdl", HP=8500, sides1=1, 
        },
        o00M={
            goldcost=10, preventPlace="unwalkable", Art="ReplaceableTextures\\CommandButtons\\BTNPeon.blp", 
            atkType1="normal", Requires="", Trains="o00I", points=7, sides1=4, Tip="Build |cffffcc00J|rack Beard", 
            file="units\\orc\\Peon\\Peon.mdl", rangeN1=1200, lumbercost=0, targs1="air,enemies,ground", _parent="owtw", 
            Name="Jack Beard", dmgplus1=5, 
            Ubertip="\"Looks like a slight hill. What do you think?  \"And a slant to the left.\"   \"Nah, it looks that way cause you've only got one shoe on.", 
            acquire=1200.0000, Hotkey="J", bldtm=1, 
        },
        h005={
            dice1=1, def=6.0000, sides1=1, defType="small", dmgplus1=999, _parent="hrif", Name="Brad Pitt", collision=10.0000, 
            modelScale=1.4500, file="units\\human\\Footman\\Footman.mdl", HP=3250, defUp=21.0000, 
        },
        o00T={
            goldcost=10, preventPlace="unwalkable", 
            Art="ReplaceableTextures\\CommandButtons\\BTNHeroBloodElfPrince.blp", cool1=2.0000, unitSound="Peasant", 
            atkType1="normal", Qarea1=50, Requires="", Trains="o00I", points=7, abilList="A00C,Abds,Arbr,Aspi", 
            Tip="Build 10 Second |cffffcc00T|rom", 
            Missileart_1="Abilities\\Weapons\\WingedSerpentMissile\\WingedSerpentMissile.mdl", lumbercost=0, 
            Farea1=30, splashTargs1="air,enemies,ground", Harea1=40, rangeN1=750, targs1="air,enemies,ground", 
            _parent="owtw", Name="10 Second Tom", bldtm=1, dmgplus1=20, 
            file="units\\human\\HeroBloodElf\\HeroBloodElf.mdl", Hotkey="T", weapTp1="msplash", 
        },
        o00V={
            goldcost=175, preventPlace="unwalkable", Art="ReplaceableTextures\\CommandButtons\\BTNGrunt.blp", bldtm=1, 
            Requires="", Trains="o00I", points=131, abilList="A00C,A007,Abds,Arbr,Aspi", Tip="Build |cffffcc00D|roug", 
            rangeN1=900, Missileart_1="Abilities\\Weapons\\Banditmissile\\Banditmissile.mdl", sides1=1, 
            targs1="air,enemies,ground", _parent="owtw", Name="Doug", lumbercost=0, 
            Ubertip="\"Doug: Well, I may not able to kick your ath but my thithter thure can.\" Very weak but can give out steroids.", 
            file="units\\orc\\Grunt\\Grunt.mdl", Hotkey="D", dmgplus1=59, 
        },
        o00L={
            goldcost=120, lumberRep=0, preventPlace="unwalkable", 
            Art="ReplaceableTextures\\CommandButtons\\BTNSasquatchShaman.blp", cool1=0.5000, atkType1="magic", 
            Requires="", Trains="o00I", points=94, abilList="A003", Tip="Build |cffffcc00C|rhubbs", auto="A003", 
            file="units\\creeps\\SasquatchShaman\\SasquatchShaman.mdl", sides1=30, rangeN1=2000, 
            Missileart_1="Abilities\\Spells\\Items\\AIso\\AIsoTarget.mdl", lumbercost=0, 
            targs1="air,enemies,ground", _parent="owtw", Name="Chubbs", dmgplus1=79, 
            Ubertip="\"HELL no. Damn alligator bit my hand off!\"", acquire=2000.0000, Hotkey="C", bldtm=1, 
        },
        o00Q={
            dice1=20, goldcost=800, preventPlace="unwalkable", 
            Art="ReplaceableTextures\\CommandButtons\\BTNBanditLord.blp", cool1=0.4000, atkType1="chaos", Qarea1=150, 
            Requires="", Trains="o00I", points=600, sides1=100, Harea1=40, Tip="Build |cffffcc00B|rilly Madison", 
            dmgplus1=0, splashTargs1="air,enemies,ground", rangeN1=1500, lumbercost=0, 
            Missileart_1="Abilities\\Weapons\\LordofFlameMissile\\LordofFlameMissile.mdl", 
            file="units\\creeps\\BanditLord\\BanditLord.mdl", targs1="air,enemies,ground", _parent="owtw", 
            Name="Billy Madison", bldtm=1, Ubertip="\"T-T-T-TODAY JUNIOR!\" Has good splash damage.", 
            acquire=1500.0000, Hotkey="B", weapTp1="msplash", 
        },
        o001={
            dice1=3, goldcost=175, preventPlace="unwalkable", 
            Art="ReplaceableTextures\\CommandButtons\\BTNBloodElfPeasant.blp", bldtm=1, Requires="", Trains="o00I", 
            points=131, sides1=95, Tip="Build |cffffcc00C|rarl", 
            Missileart_1="Abilities\\Weapons\\FaerieDragonMissile\\FaerieDragonMissile.mdl", rangeN1=900, 
            targs1="air,enemies,ground", _parent="owtw", Name="Carl", lumbercost=0, 
            Ubertip="\"He did that little weasel laugh he does.  You know, Hee-Hee-Hee-Hee-Hee-Hee.\"", 
            file="units\\critters\\HighElfPeasant\\HighElfPeasant.mdl", Hotkey="C", dmgplus1=0, 
        },
        o016={
            goldcost=90, preventPlace="unwalkable", Art="ReplaceableTextures\\CommandButtons\\BTNShadowHunter.blp", 
            cool1=0.0500, unitSound="Bandit", atkType1="hero", Requires="", Trains="o00I", points=75, sides1=8, 
            Tip="Build |cffffcc00C|rrazy Eyes", lumbercost=0, 
            Missileart_1="Abilities\\Weapons\\AvengerMissile\\AvengerMissile.mdl", rangeN1=750, 
            targs1="air,enemies,ground", _parent="owtw", Name="Crazy Eyes", bldtm=1, 
            Ubertip="\"I watch the stock market channel all the time - I just watch because I suspect that anchor man of being an evil leprechaun... he can bullshit everybody else, but he ain't fooling me.\"", 
            file="units\\orc\\HeroShadowHunter\\HeroShadowHunter.mdl", Hotkey="C", dmgplus1=49, 
        },
        o014={
            goldcost=10, preventPlace="unwalkable", Art="ReplaceableTextures\\CommandButtons\\BTNVillagerMan1.blp", 
            cool1=0.0500, unitSound="HeadHunter", atkType1="hero", Requires="", Trains="o00I", points=7, red=50, 
            Tip="Build |cffffcc00E|rmilio", blue=50, bldtm=1, sides1=4, rangeN1=750, 
            Missileart_1="Abilities\\Weapons\\Banditmissile\\Banditmissile.mdl", lumbercost=0, 
            targs1="air,enemies,ground", _parent="owtw", Name="Emilio", green=25, 
            Ubertip="\"The hideousness of that foot will haunt my dreams forever.\" Emilio throws fire pokers.", 
            file="units\\critters\\VillagerMan1\\VillagerMan1.mdl", Hotkey="E", dmgplus1=4, 
        },
        u001={
            type="peon", Tip="|cffffcc00B|rrian Madison", spd=522, movetp="fly", moveHeight=200.0000, 
            Art="ReplaceableTextures\\CommandButtons\\BTNHeroPaladin.blp", goldcost=0, 
            Ubertip="Builds units from Billy Madison.  These towers have sporadic attacks.", atkType1="unknown", 
            _parent="uaco", Name="Brian Madison", bldtm=1, Builds="o000,o00O,o002,o001,o00P,o00Q", 
            file="units\\human\\HeroPaladin\\HeroPaladin.mdl", Hotkey="B", abilList="Avul", 
        },
        o007={
            def=6.0000, defType="fort", dmgplus1=999, Name="Tom Green", _parent="ogru", collision=10.0000, 
            file="units\\creeps\\Zombie\\Zombie.mdl", HP=150, sides1=1, 
        },
        o00Y={
            goldcost=5, preventPlace="unwalkable", 
            Art="ReplaceableTextures\\CommandButtons\\BTNIceTrollBeserker.blp", cool1=0.5000, unitSound="Bandit", 
            bldtm=1, Requires="", Trains="o00I", points=3, abilList="A00A,Abds,Arbr,Aspi", Tip="Build |cffffcc00N|rate", 
            rangeN1=450, splashTargs1="air,enemies,ground", 
            Missileart_1="Abilities\\Weapons\\VoidWalkerMissile\\VoidWalkerMissile.mdl", sides1=1, 
            targs1="air,enemies,ground", _parent="owtw", Name="Nate", lumbercost=0, 
            Ubertip="\"Nate: Oh, it's perfectely fine Mr. Rydell. I got it under control. See? Iverson just missed the shot, the Sixers lose. Who cares?... THE ANGER SHARKS ARE SWIMMING MY HEAD. YOU GOTTA DUNK THAT SHIT! YOU GOTTA DUNK THAT SHIT!\"", 
            file="units\\creeps\\IceTroll\\IceTroll.mdl", Hotkey="N", dmgplus1=3, 
        },
        o009={
            def=8.0000, defType="small", dmgplus1=999, Name="Drew Carey", _parent="ogru", collision=10.0000, 
            file="Units\\Creeps\\tuskar\\tuskar.mdl", HP=255, sides1=1, 
        },
        e003={
            def=5.0000, defType="normal", sides1=1, _parent="esen", Name="John Travolta", collision=10.0000, dmgplus1=999, 
            file="units\\human\\Knight\\Knight.mdl", HP=2500, abilList="Aesn,Amgl,Aien,Ault", 
        },
        o00A={
            sides1=1, _parent="ogru", Name="Ray Romano", def=9.0000, dmgplus1=999, collision=10.0000, HP=320, 
            defType="medium", 
        },
        o00R={
            goldcost=40, preventPlace="unwalkable", Art="ReplaceableTextures\\CommandButtons\\BTNShaman.blp", 
            cool1=0.4000, atkType1="normal", Qarea1=75, Requires="", Trains="o00I", dmgplus1=1, points=30, 
            splashTargs1="air,enemies,ground,notself,organic", red=50, sides1=39, Tip="Build |cffffcc00N|razo", blue=50, 
            lumbercost=0, Farea1=55, bldtm=1, 
            Missileart_1="Abilities\\Weapons\\MeatwagonMissile\\MeatwagonMissile.mdl", 
            file="units\\orc\\Shaman\\Shaman.mdl", targs1="air,enemies,ground", _parent="owtw", Name="Nazo", green=50, 
            Ubertip="\"Fish! Pony! Hip, Hip Hop, Hip Hop anonymous? Damn you! You gave him the easy ones.\"", 
            acquire=800.0000, Hotkey="N", Harea1=60, 
        },
        o00O={
            goldcost=40, preventPlace="unwalkable", Art="ReplaceableTextures\\CommandButtons\\BTNWendigo.blp", 
            cool1=0.4000, atkType1="normal", Requires="", Trains="o00I", points=30, red=50, Tip="Build |cffffcc00J|ruanita", 
            blue=50, file="units\\creeps\\Wendigo\\Wendigo.mdl", sides1=70, lumbercost=0, 
            Missileart_1="Abilities\\Weapons\\BrewmasterMissile\\BrewmasterMissile.mdl", dmgplus1=0, 
            targs1="air,enemies,ground", _parent="owtw", Name="Juanita", green=50, 
            Ubertip="\"If you're gonna stay home today, you can help me shave my armpits.\"", acquire=800.0000, 
            Hotkey="J", bldtm=1, 
        },
        o00Z={
            MissileHoming_1=1, goldcost=50, Qarea2=50, 
            Art="ReplaceableTextures\\CommandButtons\\BTNBansheeRanger.blp", cool1=0.5700, bldtm=1, Qarea1=50, 
            targs2="air,enemies", atkType2="siege", abilList="A009", _parent="owtw", Farea2=20, 
            Ubertip="\"Stacy: Uh, we're in the adult film industry, and, we're lovers. \"", Harea2=35, Hotkey="D", 
            dice2=1, preventPlace="unwalkable", targCount1=3, rangeN2=450, weapsOn=3, Requires="", Trains="o00I", 
            Missileart_1="Objects\\InventoryItems\\TreasureChest\\treasurechest.mdl", targs1="enemies,ground", 
            targCount2=3, splashTargs1="enemies,ground", sides2=3, Tip="Build |cffffcc00S|rtacy", acquire=1200.0000, 
            points=40, Farea1=20, lumbercost=0, Harea1=35, 
            Missileart_2="Objects\\InventoryItems\\TreasureChest\\treasurechest.mdl", Missilespeed_2=1800, 
            dmgplus1=52, Name="Stacy", atkType1="siege", file="Units\\Creeps\\BansheeRanger\\BansheeRanger.mdl", 
            dmgplus2=52, rangeN1=450, weapTp1="msplash", 
        },
        o00I={
            Tip="S|cffffcc00e|rll this tower.", Art="ReplaceableTextures\\CommandButtons\\BTNPillage.blp", 
            unitSound="", bldtm=1, _parent="ogru", Name="Sell", goldcost=0, 
            Ubertip="Simply put, you use this and it sells this tower for 75% of its original cost.", fused=0, 
            Hotkey="E", HP=1, 
        },
        o005={
            goldcost=10, preventPlace="unwalkable", Art="ReplaceableTextures\\CommandButtons\\BTNVillagerKid.blp", 
            unitSound="VillagerKid", atkType1="normal", Qarea1=50, Requires="", Trains="o00I", points=7, Harea1=40, 
            Tip="Build |cffffcc00J|rulien", dmgplus1=5, splashTargs1="air,enemies,ground", Farea1=30, rangeN1=750, 
            Missileart_1="Objects\\Spawnmodels\\Demon\\DemonBlood\\DemonBloodPitlord.mdl", lumbercost=0, 
            targs1="air,enemies,ground", _parent="owtw", Name="Julien", bldtm=1, 
            Ubertip="Julian is able to both pee and throw-up on the enemies.", 
            file="units\\critters\\VillagerKid\\VillagerKid.mdl", Hotkey="J", weapTp1="msplash", 
        },
        h004={
            collision=10.0000, _parent="hfoo", Name="Leonardo Dicaprio", def=4.0000, dmgplus1=999, 
            file="units\\critters\\HighElfPeasant\\HighElfPeasant.mdl", HP=125, sides1=1, 
        },
        o00D={
            type="", def=7.0000, defType="normal", dmgplus1=999, Name="Nicholas Cage", _parent="otau", collision=10.0000, 
            file="units\\creeps\\HumanMage\\HumanMage.mdl", HP=7000, sides1=1, 
        },
        o003={
            dice1=3, goldcost=350, preventPlace="unwalkable", 
            Art="ReplaceableTextures\\CommandButtons\\BTNHeroPaladin.blp", cool1=0.7000, atkType1="chaos", 
            Requires="", Trains="o00I", points=338, sides1=100, Tip="Build Happy |cffffcc00G|rilmore", 
            Missilearc_1=0.5000, rangeN1=4000, lumbercost=0, 
            Missileart_1="Abilities\\Weapons\\DemonHunterMissile\\DemonHunterMissile.mdl", 
            file="units\\human\\HeroPaladin\\HeroPaladin.mdl", targs1="air,enemies,ground", _parent="owtw", 
            Name="Happy Gilmore", dmgplus1=547, 
            Ubertip="\"Why don't you just go home? That's your home! Are you too good for your home?\"", 
            acquire=4000.0000, Hotkey="G", bldtm=1, 
        },
        o00G={
            type="", def=7.0000, dmgplus1=999, Name="Sean Connery", collision=10.0000, _parent="otau", 
            file="units\\nightelf\\DruidoftheClaw\\DruidoftheClaw.mdl", HP=12000, sides1=1, 
        },
        o018={
            goldcost=240, preventPlace="unwalkable", Art="ReplaceableTextures\\CommandButtons\\BTNVillagerMan.blp", 
            cool1=0.0500, unitSound="VillagerMan", atkType1="hero", Requires="", Trains="o00I", points=215, sides1=21, 
            Tip="Build |cffffcc00L|rongfellow Deeds", 
            Missileart_1="Abilities\\Spells\\Other\\FrostBolt\\FrostBoltMissile.mdl", rangeN1=750, 
            targs1="air,enemies,ground", _parent="owtw", Name="Longfellow Deeds", lumbercost=0, bldtm=1, 
            file="units\\critters\\VillagerMan\\VillagerMan.mdl", Hotkey="L", dmgplus1=119, 
        },
        u005={
            Tip="Mr. |cffffcc00D|reeds", spd=522, movetp="fly", type="peon", moveHeight=200.0000, bldtm=1, _parent="uaco", 
            Name="Mr. Deeds", goldcost=0, Builds="o014,o015,o016,o017,o018", atkType1="unknown", Hotkey="D", 
            abilList="Avul", 
        },
        h000={
            Upgrade="", preventPlace="unwalkable", fmade=2, _parent="htow", Name="Movie Selector", 
            Trains="u005,u004,u003,u000,u001,u002", upgrades="", abilList="Avul", Researches="", 
        },
        e002={
            def=6.0000, defType="fort", sides1=1, _parent="esen", Name="Johnny Depp", collision=10.0000, dmgplus1=999, 
            file="units\\creeps\\HighElfArcher\\HighElfArcher.mdl", HP=2000, abilList="Aesn,Amgl,Aien,Ault", 
        },
        o012={
            dice1=3, goldcost=300, preventPlace="unwalkable", 
            Art="ReplaceableTextures\\CommandButtons\\BTNBandit.blp", atkType1="chaos", Requires="", Trains="o00I", 
            points=250, sides1=5, Tip="Build |cffffcc00D|rave", lumbercost=0, 
            Missileart_1="Abilities\\Weapons\\GlaiveMissile\\GlaiveMissile.mdl", rangeN1=450, 
            targs1="air,enemies,ground", _parent="owtw", Name="Dave", bldtm=1, 
            Ubertip="\"Dave Buznik: Look everybody, Pana Banana's got a heinie! He's got a heinie! \"", 
            file="units\\creeps\\Bandit\\Bandit.mdl", Hotkey="D", dmgplus1=323, 
        },
        o00H={
            type="", def=10.0000, sides1=1, defType="hero", _parent="otau", dmgplus1=999, Name="Samuel L. Jackson", 
            collision=10.0000, modelScale=2.7500, file="units\\demon\\Kiljaeden\\Kiljaeden.mdl", HP=50000, red=100, 
        },
        o006={
            dice1=0, def=5.0000, Art="ReplaceableTextures\\CommandButtons\\BTNHarpy.blp", defType="none", 
            _parent="owyv", Name="Meryl Streep", dmgplus1=1000, file="units\\creeps\\Harpy\\Harpy.mdl", HP=105, 
            collision=50.0000, 
        },
        o004={
            dice1=2, goldcost=350, RngBuff2=250.0000, cool1=0.4000, bldtm=1, Qarea1=150, backSw2=0.3000, armor="Stone", 
            atkType2="pierce", abilList="A001", _parent="owtw", weapsOn=3, 
            Ubertip="Equiped with nothing more than a slingshot, Frankenstein is able to do massive damage.  He also has a special attack against air which is able to hit multiple targets.", 
            acquire=1000.0000, Hotkey="F", targs2="air", weapType1="RockHeavyBash", dice2=3, atkType1="siege", 
            Name="\"Frankenstein\"", preventPlace="unwalkable", unitSound="VillagerKid", weapType2="RockHeavyBash", 
            rangeN2=1000, targs1="enemies,ground", targCount2=5, Requires="", cool2=0.1500, 
            splashTargs1="enemies,ground,notself,organic", sides2=45, sides1=75, points=263, lumbercost=0, 
            Tip="Build |cffffcc00F|rrankenstein", file="units\\critters\\VillagerKid\\VillagerKid.mdl", 
            dmgpt2=0.3000, Farea1=100, Art="ReplaceableTextures\\CommandButtons\\BTNVillagerKid.blp", 
            Missileart_1="abilities\\weapons\\catapult\\catapultmissile.mdl", 
            Missileart_2="abilities\\weapons\\catapult\\catapultmissile.mdl", Missilespeed_2=2000, dmgplus1=173, 
            Missilearc_2=0.3500, dmgplus2=422, weapTp2="missile", Trains="o00I", Harea1=120, weapTp1="msplash", 
        },
        e000={
            def=7.0000, defType="medium", sides1=1, _parent="esen", Name="Robert De Niro", collision=10.0000, dmgplus1=999, 
            file="units\\creeps\\OrcWarlock\\OrcWarlock.mdl", HP=1400, abilList="Aesn,Amgl,Aien,Ault", 
        },
        o00B={
            def=10.0000, defType="hero", _parent="ogru", dmgplus1=999, Name="Barbra Streisand", collision=10.0000, 
            modelScale=2.1000, file="units\\undead\\Banshee\\Banshee.mdl", HP=6000, sides1=1, 
        },
        o00C={
            dice1=0, def=5.0000, defType="large", dmgplus1=1000, Name="Ozzy Osbourne", _parent="owyv", 
            file="units\\orc\\BatTroll\\BatTroll.mdl", HP=950, collision=50.0000, 
        },
        o00P={
            dice1=14, goldcost=400, preventPlace="unwalkable", 
            Art="ReplaceableTextures\\CommandButtons\\BTNHeroDreadLord.blp", cool1=0.4000, atkType1="normal", 
            Requires="", Trains="o00I", points=300, sides1=100, Tip="Build |cffffcc00E|rric", 
            file="units\\undead\\HeroDreadLord\\HeroDreadLord.mdl", rangeN1=1000, 
            Missileart_1="Abilities\\Weapons\\SkeletalMageMissile\\SkeletalMageMissile.mdl", lumbercost=0, 
            targs1="air,enemies,ground", _parent="owtw", Name="Eric", dmgplus1=0, 
            Ubertip="\"Oh, gross... did you see that guys balls?\"  \"Yeah... they were weird looking.\"", 
            acquire=1000.0000, Hotkey="E", bldtm=1, 
        },
        o00J={
            goldcost=200, lumberRep=0, preventPlace="unwalkable", 
            Art="ReplaceableTextures\\CommandButtons\\BTNPandarenBrewmaster.blp", cool1=0.5500, atkType1="siege", 
            Requires="", Trains="o00I", points=168, sides1=50, Tip="Build |cffffcc00S|rhooter McGavin", 
            file="Units\\Creeps\\PandarenBrewmaster\\PandarenBrewmaster.mdl", rangeN1=3000, 
            Missileart_1="abilities\\weapons\\DemolisherMissile\\DemolisherMissile.mdl", lumbercost=0, 
            targs1="air,enemies,ground", _parent="owtw", Name="Shooter McGavin", dmgplus1=299, 
            Ubertip="\"I eat pieces of shit like you for breakfast.\"", acquire=3000.0000, Hotkey="S", bldtm=1, 
        },
        n000={
            _parent="nglm", Name="Flaming Poop Bag", modelScale=0.4000, 
            Art="ReplaceableTextures\\CommandButtons\\BTNDustOfAppearance.blp", stockMax=32, 
            file="Objects\\InventoryItems\\Rune\\Rune.mdl", 
        },
        o000={
            goldcost=8, lumberRep=0, preventPlace="unwalkable", 
            Art="ReplaceableTextures\\CommandButtons\\BTNPenguin.blp", atkType1="magic", Requires="", Trains="o00I", 
            points=6, sides1=10, Tip="Build |cffffcc00G|riant Penguin", lumbercost=0, rangeN1=700, 
            Missileart_1="Abilities\\Spells\\Other\\FrostBolt\\FrostBoltMissile.mdl", modelScale=2.2500, 
            targs1="air,enemies,ground", _parent="owtw", Name="Giant Penguin", bldtm=1, 
            Ubertip="\"It's too damn hot for a penguin to be just walkin' around.\"", 
            file="units\\critters\\Penguin\\Penguin.mdl", Hotkey="G", dmgplus1=0, 
        },
        u000={
            goldcost=0, spd=522, movetp="fly", Art="ReplaceableTextures\\CommandButtons\\BTNSpellBreaker.blp", bldtm=1, 
            abilList="Avul", Tip="Build |cffffcc00S|rcuba Steve", upgrades="", type="peon", moveHeight=200.0000, 
            _parent="uaco", Name="Scuba Steve", Ubertip="Builds units from Big Daddy", 
            Builds="o005,o00R,o00S,o013,o004", file="units\\human\\BloodElfSpellThief\\BloodElfSpellThief.mdl", 
            Hotkey="S", atkType1="unknown", 
        },
        o017={
            goldcost=150, preventPlace="unwalkable", Art="ReplaceableTextures\\CommandButtons\\BTNAssassin.blp", 
            cool1=0.0500, unitSound="VillagerWoman", atkType1="hero", Requires="", Trains="o00I", points=125, sides1=8, 
            Tip="Build |cffffcc00P|ram Dawson", 
            Missileart_1="Abilities\\Spells\\Other\\FrostBolt\\FrostBoltMissile.mdl", rangeN1=750, 
            targs1="air,enemies,ground", _parent="owtw", Name="\"Pam Dawson\"", lumbercost=0, bldtm=1, 
            file="units\\creeps\\assassin\\assassin.mdl", Hotkey="P", dmgplus1=74, 
        },
        o00S={
            goldcost=80, preventPlace="unwalkable", Art="ReplaceableTextures\\CommandButtons\\BTNKobold.blp", 
            cool1=0.5000, atkType1="siege", Qarea1=90, Requires="", Trains="o00I", points=60, sides1=1, 
            Tip="Build |cffffcc00H|romeless Guy", bldtm=1, Farea1=75, lumbercost=0, Harea1=80, 
            splashTargs1="air,enemies,ground", targs1="air,enemies,ground", _parent="owtw", Name="Homeless Guy", 
            dmgplus1=59, Missileart_1="abilities\\weapons\\catapult\\catapultmissile.mdl", 
            file="Units\\Critters\\Shoveler\\Shoveler.mdl", Hotkey="F", weapTp1="msplash", 
        },
        u009={
            dice1=1, type="", def=5.0000, defType="small", sides1=1, _parent="ugho", Name="David Spade", collision=10.0000, 
            dmgplus1=999, file="units\\human\\Priest\\Priest_V1.mdl", HP=1100, defUp=14.0000, 
        },
        owtw={
            Tip="Build |cffffcc00G|riant Penguin", sides1=11, lumbercost=0, dmgplus1=1, Name="Giant Penguin", goldcost=7, 
            _parent="owtw", file="units\\critters\\Penguin\\Penguin.mdl", Requires="", abilList="", 
        },
        u008={
            dice1=1, type="", def=6.0000, defType="normal", sides1=1, _parent="ugho", Name="Jon Stewart", collision=10.0000, 
            dmgplus1=999, file="units\\other\\BloodElfLieutenant\\BloodElfLieutenant.mdl", HP=800, defUp=13.0000, 
        },
        h009={
            dice1=0, def=10.0000, defType="fort", _parent="hgry", Name="Harrison Ford", collision=50.0000, dmgplus1=1000, 
            file="units\\human\\Gyrocopter\\Gyrocopter_V1.mdl", HP=4000, defUp=25.0000, 
        },
        e001={
            def=5.0000, defType="large", sides1=1, _parent="esen", Name="Matt Damon", collision=10.0000, dmgplus1=999, 
            file="units\\other\\DalaranMutant\\DalaranMutant.mdl", HP=1700, abilList="Aesn,Amgl,Aien,Ault", 
        },
        o011={
            goldcost=190, preventPlace="unwalkable", Art="ReplaceableTextures\\CommandButtons\\BTNDranaiMage.blp", 
            cool1=2.0000, unitSound="GoblinSapper", atkType1="normal", Qarea1=50, Requires="", Trains="o00I", points=165, 
            abilList="A00B,Abds,Arbr,Aspi", 
            Missileart_1="Abilities\\Weapons\\WingedSerpentMissile\\WingedSerpentMissile.mdl", 
            Tip="Build Buddy R|cffffcc00y|rdell", lumbercost=0, splashTargs1="air,enemies,ground", Farea1=30, sides1=1, 
            Harea1=40, rangeN1=450, targs1="air,enemies,ground", _parent="owtw", Name="Buddy Rydell", bldtm=1, dmgplus1=179, 
            file="units\\other\\DranaiMage\\DranaiMage.mdl", Hotkey="Y", weapTp1="msplash", 
        },
        h008={
            dice1=1, def=5.0000, defType="fort", sides1=1, _parent="hrif", Name="Ben Stiller", collision=10.0000, 
            dmgplus1=999, file="units\\human\\Peasant\\Peasant.mdl", HP=5500, defUp=24.0000, 
        },
        u007={
            dice1=1, type="", def=7.0000, defType="fort", dmgplus1=999, Name="Sandra Bullock", collision=10.0000, 
            _parent="ugho", file="units\\critters\\VillagerWoman\\VillagerWoman.mdl", HP=600, sides1=1, 
        },
        u006={
            dice1=1, type="", blue=40, def=5.0000, sides1=1, collision=10.0000, dmgplus1=999, Name="Will Smith", green=40, 
            _parent="ugho", file="units\\critters\\VillagerMan1\\VillagerMan1.mdl", HP=475, red=40, 
        },
        h001={
            def=1.0000, defType="normal", dmgplus1=999, Name="Carrot Top", _parent="hfoo", collision=10.0000, 
            file="units\\human\\Sorceress\\Sorceress_V1.mdl", HP=20, sides1=1, 
        },
        o00N={
            MissileHoming_1=1, goldcost=60, preventPlace="unwalkable", 
            Art="ReplaceableTextures\\CommandButtons\\BTNZombie.blp", cool1=0.5700, Harea1=35, atkType1="siege", 
            Qarea1=50, Requires="", Trains="o00I", dmgplus1=19, points=45, targCount1=0, abilList="A004", 
            splashTargs1="air,enemies,ground", Tip="Build |cffffcc00D|ronald", sides1=16, rangeN1=1200, Farea1=20, 
            lumbercost=0, Missileart_1="units\\human\\WarWagon\\WarWagon_V1.mdl", 
            file="units\\creeps\\Zombie\\Zombie.mdl", targs1="air,enemies,ground", _parent="owtw", Name="Donald", 
            bldtm=1, Ubertip="\"You suck! Ya Jackass!\" This tower runs the enemy over with his car.", 
            acquire=1200.0000, Hotkey="D", weapTp1="msplash", 
        },
        u004={
            type="peon", Tip="|cffffcc00M|rarlin", spd=522, movetp="fly", moveHeight=200.0000, 
            Art="ReplaceableTextures\\CommandButtons\\BTNDruidOfTheClaw.blp", goldcost=0, 
            Ubertip="Builds units from 50 First Dates.  These towers excel in slowing units. (not fully balanced)", 
            atkType1="unknown", _parent="uaco", Name="Marlin", bldtm=1, Builds="o00T,o00U,o00W,o00V,o00X", 
            file="units\\nightelf\\DruidoftheClaw\\DruidoftheClaw.mdl", Hotkey="M", abilList="Avul", 
        },
        u003={
            type="peon", Tip="|cffffcc00L|rou", spd=522, movetp="fly", moveHeight=200.0000, 
            Art="ReplaceableTextures\\CommandButtons\\BTNHeroAlchemist.blp", goldcost=0, 
            Ubertip="Builds units from Anger Management.  These towers have high damage but lack in range. Most towers can get pissed off too.", 
            atkType1="unknown", _parent="uaco", Name="Lou", bldtm=1, Builds="o00Y,o00Z,o010,o011,o012", 
            file="Units\\Creeps\\HeroGoblinAlchemist\\HeroGoblinAlchemist.mdl", Hotkey="L", abilList="Avul", 
        },
        o00W={
            goldcost=120, lumberRep=0, preventPlace="unwalkable", 
            Art="ReplaceableTextures\\CommandButtons\\BTNNightElfRunner.blp", cool1=0.3000, atkType1="normal", 
            Requires="", Trains="o00I", points=94, abilList="A00C", Tip="Build |cffffcc00L|rucy", auto="A003", bldtm=1, 
            lumbercost=0, sides1=1, Missileart_1=".mdl", rangeN1=100, targs1="air,enemies,ground", _parent="owtw", 
            Name="Lucy", file="units\\nightelf\\Runner\\Runner.mdl", dmgplus1=64, acquire=500.0000, Hotkey="L", 
            weapTp1="normal", 
        },
        o00X={
            goldcost=400, preventPlace="unwalkable", Art="ReplaceableTextures\\CommandButtons\\BTNFurion.blp", 
            cool1=0.4000, bldtm=1, Requires="", Trains="o00I", points=300, sides1=1, Tip="Build H|cffffcc00e|rnry", 
            lumbercost=0, Missileart_1="units\\critters\\Penguin\\Penguin.mdl", rangeN1=1000, 
            targs1="air,enemies,ground", _parent="owtw", Name="Henry", 
            file="units\\nightelf\\MalFurion\\MalFurionNoStag.mdl", dmgplus1=479, acquire=1000.0000, Hotkey="E", 
            atkType1="siege", 
        },
        u002={
            type="peon", Tip="Build |cffffcc00V|rirginia", spd=522, movetp="fly", moveHeight=200.0000, 
            Art="ReplaceableTextures\\CommandButtons\\BTNVillagerWoman.blp", goldcost=0, 
            Ubertip="Builds units from Happy Gilmore.  These towers excel in range. (not balanced)", 
            atkType1="unknown", _parent="uaco", Name="Virginia", bldtm=1, Builds="o00M,o00N,o00L,o00J,o003,o00K", 
            file="units\\critters\\VillagerWoman\\VillagerWoman.mdl", Hotkey="V", abilList="Avul", 
        },
        h002={
            sides1=1, _parent="hfoo", Name="Keanu Reeves", collision=10.0000, dmgplus1=999, 
            file="units\\nightelf\\HeroDemonHunter\\HeroDemonHunter.mdl", HP=45, defType="small", 
        },
        o015={
            goldcost=30, preventPlace="unwalkable", Art="ReplaceableTextures\\CommandButtons\\BTNSpiritWalker.blp", 
            cool1=0.0500, unitSound="HeadHunter", atkType1="hero", Requires="", Trains="o00I", points=25, 
            abilList="A00C,Abds,Arbr,Aspi", Tip="Build |cffffcc00J|ran", lumbercost=0, sides1=5, 
            Missileart_1="Abilities\\Weapons\\WingedSerpentMissile\\WingedSerpentMissile.mdl", rangeN1=750, 
            targs1="air,enemies,ground", _parent="owtw", Name="Jan", dmgplus1=18, 
            Ubertip="\"I'm sorry all I heard was blah blah blah I'm a dirty tramp.\"", 
            file="units\\orc\\spiritwalker\\spiritwalker.mdl", Hotkey="J", bldtm=1, 
        },
        h006={
            dice1=1, def=5.0000, sides1=1, dmgplus1=999, Name="Patrick Stewart", collision=10.0000, _parent="hrif", 
            file="units\\undead\\Tichondrius\\Tichondrius.mdl", HP=3750, defUp=22.0000, 
        },
        uaco={
            Tip="|cffffcc00B|rig Daddy", _parent="uaco", Name="Big Daddy", weapsOn=0, Builds="", 
            Ubertip="Builds units from Big Daddy.  This race excels in ", Hotkey="B", abilList="", 
        },
        o013={
            goldcost=180, weapType1="RockHeavyBash", preventPlace="unwalkable", 
            Art="ReplaceableTextures\\CommandButtons\\BTNSorceress.blp", cool1=0.4000, unitSound="Sorceress", 
            atkType1="siege", Qarea1=150, Requires="", Trains="o00I", armor="Stone", points=120, Harea1=120, abilList="A001", 
            dmgplus1=124, Tip="Build |cffffcc00C|rorinne", splashTargs1="air,enemies,ground,notself,organic", 
            sides1=10, Farea1=100, lumbercost=0, Missileart_1="abilities\\weapons\\catapult\\catapultmissile.mdl", 
            file="units\\human\\Sorceress\\Sorceress_V1.mdl", targs1="enemies,ground", _parent="owtw", 
            Name="Corinne Maloney", bldtm=1, Ubertip="\"We wasted the good surprise on you!\"", acquire=1000.0000, 
            Hotkey="C", weapTp1="msplash", 
        },
        o00U={
            goldcost=50, preventPlace="unwalkable", Art="ReplaceableTextures\\CommandButtons\\BTNOrcWarlock.blp", 
            cool1=0.4000, unitSound="HeadHunter", atkType1="normal", Requires="", Trains="o00I", points=30, 
            abilList="A006,Abds,Arbr,Aspi", file="units\\creeps\\OrcWarlock\\OrcWarlock.mdl", 
            Tip="Build |cffffcc00U|rla", blue=50, sides1=1, red=50, lumbercost=0, 
            Missileart_1="Abilities\\Spells\\Undead\\PlagueCloud\\PlagueCloudCaster.mdl", dmgplus1=59, 
            targs1="air,enemies,ground", _parent="owtw", Name="Ula", green=50, 
            Ubertip="Ula: [dressed up as Lucy, with a coconut bra on] Aquariums make me super horny! ", 
            acquire=800.0000, Hotkey="U", bldtm=1, 
        },
        o00F={
            type="", def=5.0000, defType="medium", dmgplus1=999, Name="Mel Gibson", _parent="otau", collision=10.0000, 
            file="units\\orc\\Thrall\\Thrall.mdl", HP=10000, sides1=1, 
        },
        o00K={
            MissileHoming_1=1, goldcost=800, 
            Missileart_1="Abilities\\Weapons\\SpiritOfVengeanceMissile\\SpiritOfVengeanceMissile.mdl", 
            preventPlace="unwalkable", Art="ReplaceableTextures\\CommandButtons\\BTNHeroArchMage.blp", cool1=0.1700, 
            bldtm=1, atkType1="chaos", Qarea1=60, Requires="", Trains="o00I", splashTargs1="air,enemies,ground", points=900, 
            sides1=75, Missilespeed_1=3000, rangeN1=10000, Tip="Build |cffffcc00B|rob Barker", lumbercost=0, 
            file="units\\human\\HeroArchMage\\HeroArchMage.mdl", Farea1=20, dmgplus1=747, Harea1=40, dice1=3, 
            targs1="air,enemies,ground", _parent="owtw", Name="Bob Barker", Missilearc_1=0.6500, 
            Ubertip="\"Now, you've had enough... bitch.\" This tower has incredible range with a touch of splash.", 
            acquire=10000.0000, Hotkey="B", weapTp1="msplash", 
        },
        o008={
            def=7.0000, defType="normal", dmgplus1=999, Name="Jerry Seinfeld", _parent="ogru", collision=10.0000, 
            file="units\\other\\Dranai\\Dranai.mdl", HP=200, sides1=1, 
        },
        o002={
            dice1=2, goldcost=80, preventPlace="unwalkable", 
            Art="ReplaceableTextures\\CommandButtons\\BTNMortarTeam.blp", cool1=0.5000, atkType1="siege", Qarea1=60, 
            Requires="", Trains="o00I", points=60, abilList="A005,Abds,Arbr,Aspi", Harea1=45, 
            Tip="Build |cffffcc00F|rrank and Jack", bldtm=1, splashTargs1="air,enemies,ground", Farea1=30, sides1=60, 
            Missileart_1="Abilities\\Weapons\\FragDriller\\FragDriller.mdl", lumbercost=0, 
            targs1="air,enemies,ground", _parent="owtw", Name="Frank and Jack", dmgplus1=0, 
            Ubertip="\"When I graduated from first grade, all my dad did was tell me to get a job.\" Frank and Jack are able to set flaming bags of \"poop\" for the enemy to step on and have a little splash.", 
            file="units\\human\\MortarTeam\\MortarTeam.mdl", Hotkey="F", weapTp1="msplash", 
        },
        h003={
            def=3.0000, defType="medium", dmgplus1=999, Name="William Shatner", _parent="hfoo", collision=10.0000, 
            file="units\\creeps\\OgreOneHeaded\\OgreOneHeaded.mdl", HP=95, sides1=1, 
        },
        e004={
            def=5.0000, sides1=1, defType="hero", dmgplus1=999, _parent="esen", Name="Tom Cruise", collision=10.0000, 
            modelScale=2.5000, file="units\\other\\Proudmoore\\Proudmoore.mdl", HP=35000, 
            abilList="Aesn,Amgl,Aien,Ault", 
        },
    },
    category="unit", 
}