local slk = require 'slk' 
local obj 
obj = slk.unit.e000:new('e000') 
obj.Name = [[Robert De Niro]]
obj.Tip = [[训练女猎手(|cffffcc00H|r)]]
obj.Ubertip = [[灵活的远程攻击单位，能学习到哨兵和月刃技能。|n|n|cffffcc00能攻击地面单位。|r]]
obj = slk.unit.e001:new('e001') 
obj.Name = [[Matt Damon]]
obj.Tip = [[训练女猎手(|cffffcc00H|r)]]
obj.Ubertip = [[灵活的远程攻击单位，能学习到哨兵和月刃技能。|n|n|cffffcc00能攻击地面单位。|r]]
obj = slk.unit.e002:new('e002') 
obj.Name = [[Johnny Depp]]
obj.Tip = [[训练女猎手(|cffffcc00H|r)]]
obj.Ubertip = [[灵活的远程攻击单位，能学习到哨兵和月刃技能。|n|n|cffffcc00能攻击地面单位。|r]]
obj = slk.unit.e003:new('e003') 
obj.Name = [[John Travolta]]
obj.Tip = [[训练女猎手(|cffffcc00H|r)]]
obj.Ubertip = [[灵活的远程攻击单位，能学习到哨兵和月刃技能。|n|n|cffffcc00能攻击地面单位。|r]]
obj = slk.unit.e004:new('e004') 
obj.Name = [[Tom Cruise]]
obj.Tip = [[训练女猎手(|cffffcc00H|r)]]
obj.Ubertip = [[灵活的远程攻击单位，能学习到哨兵和月刃技能。|n|n|cffffcc00能攻击地面单位。|r]]
obj = slk.unit.h000:new('h000') 
obj.Name = [[Movie Selector]]
obj.Tip = [[建造城镇大厅(|cffffcc00H|r)]]
obj.Ubertip = [[基本建筑物，用来训练农民和存贮搜集到的资源，在升级到了主城和城堡之后能让玩家建造许多新的建筑物和单位。]]
obj = slk.unit.h001:new('h001') 
obj.Name = [[Carrot Top]]
obj.Tip = [[生产步兵(|cffffcc00F|r)]]
obj.Ubertip = [[步兵能学习到防御模式技能。|n|n|cffffcc00能攻击地面单位。|r]]
obj = slk.unit.h002:new('h002') 
obj.Name = [[Keanu Reeves]]
obj.Tip = [[生产步兵(|cffffcc00F|r)]]
obj.Ubertip = [[步兵能学习到防御模式技能。|n|n|cffffcc00能攻击地面单位。|r]]
obj = slk.unit.h003:new('h003') 
obj.Name = [[William Shatner]]
obj.Tip = [[生产步兵(|cffffcc00F|r)]]
obj.Ubertip = [[步兵能学习到防御模式技能。|n|n|cffffcc00能攻击地面单位。|r]]
obj = slk.unit.h004:new('h004') 
obj.Name = [[Leonardo Dicaprio]]
obj.Tip = [[生产步兵(|cffffcc00F|r)]]
obj.Ubertip = [[步兵能学习到防御模式技能。|n|n|cffffcc00能攻击地面单位。|r]]
obj = slk.unit.h005:new('h005') 
obj.Name = [[Brad Pitt]]
obj.Tip = [[生产矮人火枪手(|cffffcc00R|r)]]
obj.Ubertip = [[非常适合于对付敌人的空中单位，还能获得长管火枪的升级。|n|n|cffffcc00能攻击地面和空中单位。|r]]
obj = slk.unit.h006:new('h006') 
obj.Name = [[Patrick Stewart]]
obj.Tip = [[生产矮人火枪手(|cffffcc00R|r)]]
obj.Ubertip = [[非常适合于对付敌人的空中单位，还能获得长管火枪的升级。|n|n|cffffcc00能攻击地面和空中单位。|r]]
obj = slk.unit.h007:new('h007') 
obj.Name = [[Halle Berry]]
obj.Tip = [[生产矮人火枪手(|cffffcc00R|r)]]
obj.Ubertip = [[非常适合于对付敌人的空中单位，还能获得长管火枪的升级。|n|n|cffffcc00能攻击地面和空中单位。|r]]
obj = slk.unit.h008:new('h008') 
obj.Name = [[Ben Stiller]]
obj.Tip = [[生产矮人火枪手(|cffffcc00R|r)]]
obj.Ubertip = [[非常适合于对付敌人的空中单位，还能获得长管火枪的升级。|n|n|cffffcc00能攻击地面和空中单位。|r]]
obj = slk.unit.h009:new('h009') 
obj.Name = [[Harrison Ford]]
obj.Tip = [[训练狮鹫骑士(|cffffcc00G|r)]]
obj.Ubertip = [[威力巨大的飞行单位，狮鹫上面骑乘着一个矮人族的锤手。能学到风暴战锤技能。|n|n|cffffcc00能攻击地面和空中单位。|r]]
obj = slk.unit.n000:new('n000') 
obj.Name = [[Flaming Poop Bag]]
obj.Tip = [[null]]
obj = slk.unit.o000:new('o000') 
obj.Name = [[Giant Penguin]]
obj.Tip = [[Build |cffffcc00G|riant Penguin]]
obj.Ubertip = [["It's too damn hot for a penguin to be just walkin' around."]]
obj = slk.unit.o001:new('o001') 
obj.Name = [[Carl]]
obj.Tip = [[Build |cffffcc00C|rarl]]
obj.Ubertip = [["He did that little weasel laugh he does.  You know. Hee-Hee-Hee-Hee-Hee-Hee."]]
obj = slk.unit.o002:new('o002') 
obj.Name = [[Frank and Jack]]
obj.Tip = [[Build |cffffcc00F|rrank and Jack]]
obj.Ubertip = [["When I graduated from first grade. all my dad did was tell me to get a job." Frank and Jack are able to set flaming bags of "poop" for the enemy to step on and have a little splash.]]
obj = slk.unit.o003:new('o003') 
obj.Name = [[Happy Gilmore]]
obj.Tip = [[Build Happy |cffffcc00G|rilmore]]
obj.Ubertip = [["Why don't you just go home? That's your home! Are you too good for your home?"]]
obj = slk.unit.o004:new('o004') 
obj.Name = [["Frankenstein"]]
obj.Tip = [[Build |cffffcc00F|rrankenstein]]
obj.Ubertip = [[Equiped with nothing more than a slingshot. Frankenstein is able to do massive damage.  He also has a special attack against air which is able to hit multiple targets.]]
obj = slk.unit.o005:new('o005') 
obj.Name = [[Julien]]
obj.Tip = [[Build |cffffcc00J|rulien]]
obj.Ubertip = [[Julian is able to both pee and throw-up on the enemies.]]
obj = slk.unit.o006:new('o006') 
obj.Name = [[Meryl Streep]]
obj.Tip = [[训练风骑士(|cffffcc00W|r)]]
obj.Ubertip = [[一种高度机动的飞行单位。特别擅长于侦察。能获得浸毒武器的升级。|n|n|cffffcc00能攻击地面和空中单位。|r]]
obj = slk.unit.o007:new('o007') 
obj.Name = [[Tom Green]]
obj.Tip = [[训练兽族步兵(|cffffcc00G|r)]]
obj.Ubertip = [[基本的兽族地面单位。能得到狂暴力量的升级。|n|n|cffffcc00能攻击地面单位。|r]]
obj = slk.unit.o008:new('o008') 
obj.Name = [[Jerry Seinfeld]]
obj.Tip = [[训练兽族步兵(|cffffcc00G|r)]]
obj.Ubertip = [[基本的兽族地面单位。能得到狂暴力量的升级。|n|n|cffffcc00能攻击地面单位。|r]]
obj = slk.unit.o009:new('o009') 
obj.Name = [[Drew Carey]]
obj.Tip = [[训练兽族步兵(|cffffcc00G|r)]]
obj.Ubertip = [[基本的兽族地面单位。能得到狂暴力量的升级。|n|n|cffffcc00能攻击地面单位。|r]]
obj = slk.unit.o00A:new('o00A') 
obj.Name = [[Ray Romano]]
obj.Tip = [[训练兽族步兵(|cffffcc00G|r)]]
obj.Ubertip = [[基本的兽族地面单位。能得到狂暴力量的升级。|n|n|cffffcc00能攻击地面单位。|r]]
obj = slk.unit.o00B:new('o00B') 
obj.Name = [[Barbra Streisand]]
obj.Tip = [[训练兽族步兵(|cffffcc00G|r)]]
obj.Ubertip = [[基本的兽族地面单位。能得到狂暴力量的升级。|n|n|cffffcc00能攻击地面单位。|r]]
obj = slk.unit.o00C:new('o00C') 
obj.Name = [[Ozzy Osbourne]]
obj.Tip = [[训练风骑士(|cffffcc00W|r)]]
obj.Ubertip = [[一种高度机动的飞行单位。特别擅长于侦察。能获得浸毒武器的升级。|n|n|cffffcc00能攻击地面和空中单位。|r]]
obj = slk.unit.o00D:new('o00D') 
obj.Name = [[Nicholas Cage]]
obj.Tip = [[训练牛头人(|cffffcc00T|r)]]
obj.Ubertip = [[大型的单位，能学习到粉碎技能。|n|n|cffffcc00能攻击地面单位。|r]]
obj = slk.unit.o00E:new('o00E') 
obj.Name = [[Angelina Jolie]]
obj.Tip = [[训练牛头人(|cffffcc00T|r)]]
obj.Ubertip = [[大型的单位，能学习到粉碎技能。|n|n|cffffcc00能攻击地面单位。|r]]
obj = slk.unit.o00F:new('o00F') 
obj.Name = [[Mel Gibson]]
obj.Tip = [[训练牛头人(|cffffcc00T|r)]]
obj.Ubertip = [[大型的单位，能学习到粉碎技能。|n|n|cffffcc00能攻击地面单位。|r]]
obj = slk.unit.o00G:new('o00G') 
obj.Name = [[Sean Connery]]
obj.Tip = [[训练牛头人(|cffffcc00T|r)]]
obj.Ubertip = [[大型的单位，能学习到粉碎技能。|n|n|cffffcc00能攻击地面单位。|r]]
obj = slk.unit.o00H:new('o00H') 
obj.Name = [[Samuel L. Jackson]]
obj.Tip = [[训练牛头人(|cffffcc00T|r)]]
obj.Ubertip = [[大型的单位，能学习到粉碎技能。|n|n|cffffcc00能攻击地面单位。|r]]
obj = slk.unit.o00I:new('o00I') 
obj.Name = [[Sell]]
obj.Tip = [[S|cffffcc00e|rll this tower.]]
obj.Ubertip = [[Simply put. you use this and it sells this tower for 75% of its original cost.]]
obj = slk.unit.o00J:new('o00J') 
obj.Name = [[Shooter McGavin]]
obj.Tip = [[Build |cffffcc00S|rhooter McGavin]]
obj.Ubertip = [["I eat pieces of shit like you for breakfast."]]
obj = slk.unit.o00K:new('o00K') 
obj.Name = [[Bob Barker]]
obj.Tip = [[Build |cffffcc00B|rob Barker]]
obj.Ubertip = [["Now. you've had enough... bitch." This tower has incredible range with a touch of splash.]]
obj = slk.unit.o00L:new('o00L') 
obj.Name = [[Chubbs]]
obj.Tip = [[Build |cffffcc00C|rhubbs]]
obj.Ubertip = [["HELL no. Damn alligator bit my hand off!"]]
obj = slk.unit.o00M:new('o00M') 
obj.Name = [[Jack Beard]]
obj.Tip = [[Build |cffffcc00J|rack Beard]]
obj.Ubertip = [["Looks like a slight hill. What do you think?  "And a slant to the left."   "Nah. it looks that way cause you've only got one shoe on.]]
obj = slk.unit.o00N:new('o00N') 
obj.Name = [[Donald]]
obj.Tip = [[Build |cffffcc00D|ronald]]
obj.Ubertip = [["You suck! Ya Jackass!" This tower runs the enemy over with his car.]]
obj = slk.unit.o00O:new('o00O') 
obj.Name = [[Juanita]]
obj.Tip = [[Build |cffffcc00J|ruanita]]
obj.Ubertip = [["If you're gonna stay home today. you can help me shave my armpits."]]
obj = slk.unit.o00P:new('o00P') 
obj.Name = [[Eric]]
obj.Tip = [[Build |cffffcc00E|rric]]
obj.Ubertip = [["Oh. gross... did you see that guys balls?"  "Yeah... they were weird looking."]]
obj = slk.unit.o00Q:new('o00Q') 
obj.Name = [[Billy Madison]]
obj.Tip = [[Build |cffffcc00B|rilly Madison]]
obj.Ubertip = [["T-T-T-TODAY JUNIOR!" Has good splash damage.]]
obj = slk.unit.o00R:new('o00R') 
obj.Name = [[Nazo]]
obj.Tip = [[Build |cffffcc00N|razo]]
obj.Ubertip = [["Fish! Pony! Hip. Hip Hop. Hip Hop anonymous? Damn you! You gave him the easy ones."]]
obj = slk.unit.o00S:new('o00S') 
obj.Name = [[Homeless Guy]]
obj.Tip = [[Build |cffffcc00H|romeless Guy]]
obj.Ubertip = [["Nazo: Not my problem your father was sick.   Homeless Guy: That - well - -Stop yelling at me! AAAhhhhhhhh! ." The homeless guy throws trash at people.]]
obj = slk.unit.o00T:new('o00T') 
obj.Name = [[10 Second Tom]]
obj.Tip = [[Build 10 Second |cffffcc00T|rom]]
obj.Ubertip = [[Dr. Keats: Tom was in an accident and now he only has a ten-second memory.   Ten Second Tom: I was in an accident? That's terrible.   Dr. Keats: Don't worry. you're totally gonna get over it in about three seconds. Tom has a great attack but is incredibly slow.]]
obj = slk.unit.o00U:new('o00U') 
obj.Name = [[Ula]]
obj.Tip = [[Build |cffffcc00U|rla]]
obj.Ubertip = [[Ula: [dressed up as Lucy. with a coconut bra on] Aquariums make me super horny! ]]
obj = slk.unit.o00V:new('o00V') 
obj.Name = [[Doug]]
obj.Tip = [[Build |cffffcc00D|roug]]
obj.Ubertip = [["Doug: Well. I may not able to kick your ath but my thithter thure can." Very weak but can give out steroids.]]
obj = slk.unit.o00W:new('o00W') 
obj.Name = [[Lucy]]
obj.Tip = [[Build |cffffcc00L|rucy]]
obj.Ubertip = [["Henry: Hah! I can't believe you fell for that!   Lucy: Well... my grandfather died while trying to jump-start a car... " - Lucy hits people with her bat]]
obj = slk.unit.o00X:new('o00X') 
obj.Name = [[Henry]]
obj.Tip = [[Build H|cffffcc00e|rnry]]
obj.Ubertip = [["Henry: I don't think that's an option. Lisa.   Linda: Linda.   Henry: I know. I changed your name for your protection. "]]
obj = slk.unit.o00Y:new('o00Y') 
obj.Name = [[Nate]]
obj.Tip = [[Build |cffffcc00N|rate]]
obj.Ubertip = [["Nate: Oh. it's perfectely fine Mr. Rydell. I got it under control. See? Iverson just missed the shot. the Sixers lose. Who cares?... THE ANGER SHARKS ARE SWIMMING MY HEAD. YOU GOTTA DUNK THAT SHIT! YOU GOTTA DUNK THAT SHIT!"]]
obj = slk.unit.o00Z:new('o00Z') 
obj.Name = [[Stacy]]
obj.Tip = [[Build |cffffcc00S|rtacy]]
obj.Ubertip = [["Stacy: Uh. we're in the adult film industry. and. we're lovers. "]]
obj = slk.unit.o010:new('o010') 
obj.Name = [[Chuck]]
obj.Tip = [[Build |cffffcc00C|rhuck]]
obj.Ubertip = [["Chuck: Here's my phone number.   [Dave reads it]   Dave Buznik: "You're gonna die. bitch"?   Chuck: Oh. sorry. That's a letter I'm writing to Geraldo Rivera."]]
obj = slk.unit.o011:new('o011') 
obj.Name = [[Buddy Rydell]]
obj.Tip = [[Build Buddy R|cffffcc00y|rdell]]
obj.Ubertip = [["[after loudly passing gas in bed]   Dr. Buddy Rydell: You hear that frog?"  ]]
obj = slk.unit.o012:new('o012') 
obj.Name = [[Dave]]
obj.Tip = [[Build |cffffcc00D|rave]]
obj.Ubertip = [["Dave Buznik: Look everybody. Pana Banana's got a heinie! He's got a heinie! "]]
obj = slk.unit.o013:new('o013') 
obj.Name = [[Corinne Maloney]]
obj.Tip = [[Build |cffffcc00C|rorinne]]
obj.Ubertip = [["We wasted the good surprise on you!"]]
obj = slk.unit.o014:new('o014') 
obj.Name = [[Emilio]]
obj.Tip = [[Build |cffffcc00E|rmilio]]
obj.Ubertip = [["The hideousness of that foot will haunt my dreams forever." Emilio throws fire pokers.]]
obj = slk.unit.o015:new('o015') 
obj.Name = [[Jan]]
obj.Tip = [[Build |cffffcc00J|ran]]
obj.Ubertip = [["I'm sorry all I heard was blah blah blah I'm a dirty tramp."]]
obj = slk.unit.o016:new('o016') 
obj.Name = [[Crazy Eyes]]
obj.Tip = [[Build |cffffcc00C|rrazy Eyes]]
obj.Ubertip = [["I watch the stock market channel all the time - I just watch because I suspect that anchor man of being an evil leprechaun... he can bullshit everybody else. but he ain't fooling me."]]
obj = slk.unit.o017:new('o017') 
obj.Name = [["Pam Dawson"]]
obj.Tip = [[Build |cffffcc00P|ram Dawson]]
obj.Ubertip = [["And this is my brother Denny's room.   [opens a closet door]   they didn't like my brother very much."]]
obj = slk.unit.o018:new('o018') 
obj.Name = [[Longfellow Deeds]]
obj.Tip = [[Build |cffffcc00L|rongfellow Deeds]]
obj.Ubertip = [["Longfellow Deeds: How many cats do you have?   Cat Lady: Seven.   Longfellow Deeds: Holy shit. Lets get cracking."]]
obj = slk.unit.u000:new('u000') 
obj.Name = [[Scuba Steve]]
obj.Tip = [[Build |cffffcc00S|rcuba Steve]]
obj.Ubertip = [[Builds units from Big Daddy]]
obj = slk.unit.u001:new('u001') 
obj.Name = [[Brian Madison]]
obj.Tip = [[|cffffcc00B|rrian Madison]]
obj.Ubertip = [[Builds units from Billy Madison.  These towers have sporadic attacks.]]
obj = slk.unit.u002:new('u002') 
obj.Name = [[Virginia]]
obj.Tip = [[Build |cffffcc00V|rirginia]]
obj.Ubertip = [[Builds units from Happy Gilmore.  These towers excel in range. (not balanced)]]
obj = slk.unit.u003:new('u003') 
obj.Name = [[Lou]]
obj.Tip = [[|cffffcc00L|rou]]
obj.Ubertip = [[Builds units from Anger Management.  These towers have high damage but lack in range. Most towers can get pissed off too.]]
obj = slk.unit.u004:new('u004') 
obj.Name = [[Marlin]]
obj.Tip = [[|cffffcc00M|rarlin]]
obj.Ubertip = [[Builds units from 50 First Dates.  These towers excel in slowing units. (not fully balanced)]]
obj = slk.unit.u005:new('u005') 
obj.Name = [[Mr. Deeds]]
obj.Tip = [[Mr. |cffffcc00D|reeds]]
obj.Ubertip = [[不死族的基本工人单位。能召唤建筑物，采集黄金和进行修复工作。在牺牲深渊里牺牲以后侍僧还可以变为阴影。|n|n|cffffcc00能攻击地面单位。|r]]
obj = slk.unit.u006:new('u006') 
obj.Name = [[Will Smith]]
obj.Tip = [[训练食尸鬼(|cffffcc00G|r)]]
obj.Ubertip = [[基本的地面单位，也能采集木材。能学习到吞食尸体和食尸鬼狂热技能。|n|n|cffffcc00能攻击地面单位和树木。|r]]
obj = slk.unit.u007:new('u007') 
obj.Name = [[Sandra Bullock]]
obj.Tip = [[训练食尸鬼(|cffffcc00G|r)]]
obj.Ubertip = [[基本的地面单位，也能采集木材。能学习到吞食尸体和食尸鬼狂热技能。|n|n|cffffcc00能攻击地面单位和树木。|r]]
obj = slk.unit.u008:new('u008') 
obj.Name = [[Jon Stewart]]
obj.Tip = [[训练食尸鬼(|cffffcc00G|r)]]
obj.Ubertip = [[基本的地面单位，也能采集木材。能学习到吞食尸体和食尸鬼狂热技能。|n|n|cffffcc00能攻击地面单位和树木。|r]]
obj = slk.unit.u009:new('u009') 
obj.Name = [[David Spade]]
obj.Tip = [[训练食尸鬼(|cffffcc00G|r)]]
obj.Ubertip = [[基本的地面单位，也能采集木材。能学习到吞食尸体和食尸鬼狂热技能。|n|n|cffffcc00能攻击地面单位和树木。|r]]
obj = slk.ability.A000:new('A000') 
obj.Name = [[Car Attack]]
obj.Tip = [[|cffffcc00C|rar Attack]]
obj.Ubertip = [[Donald runs over enemies in his car.]]
obj = slk.ability.A001:new('A001') 
obj.Name = [[Multi-Attack]]
obj.Tip = [[Multi-Attack]]
obj.Ubertip = [[Fires fast rocks at nearby enemy air units. dealing <hrtt.mindmg2> - <hrtt.maxdmg2> damage per hit.]]
obj = slk.ability.A002:new('A002') 
obj.Name = [[Car Attack]]
obj.Tip = [[诅咒(|cffffcc00C|r)]]
obj.Ubertip = [[诅咒敌人的某个单位使其有 <Acrs.DataA1.%>%的概率不能击中自己的目标。|n持续<Acrs.Dur1>秒。]]
obj = slk.ability.A003:new('A003') 
obj.Name = [[It's all in the hips.]]
obj.Tip = [[It's all in the hips.]]
obj.Ubertip = [[Boosts the confidence of nearby friendly units making them have a 30% damage increase.]]
obj = slk.ability.A004:new('A004') 
obj.Name = [[Car Attack]]
obj.Tip = [[Car Attack]]
obj.Ubertip = [[Donald drives his car into many surrounding enemies.]]
obj = slk.ability.A005:new('A005') 
obj.Name = [[Flaming Poop Bag]]
obj.Tip = [[|cffffcc00F|rlaming Poop Bag]]
obj.Ubertip = [[Frank and Jack set down a Flaming Poop Bag for an enemy to step on.]]
obj = slk.ability.A006:new('A006') 
obj.Name = [[Pot Smoke (Abomination)]]
obj.Tip = [[Smoke]]
obj.Ubertip = [[Infects nearby enemy living units with Pot Smoke. The smoke deals <Aap1.DataB1> damage per second. |nLasts <Aap1.DataA1> seconds.]]
obj = slk.ability.A007:new('A007') 
obj.Name = [[Steroids]]
obj.Tip = [[|cffffcc00S|rteroids]]
obj.Ubertip = [[增加一个友军单位<Ablo.DataA1.%>%的攻击速度和<Ablo.DataB1.%>%的移动速度。|n持续<Ablo.Dur1>秒。]]
obj = slk.ability.A008:new('A008') 
obj.Name = [[Get Pissed]]
obj.Tip = [[Get Pi|cffffcc00s|rsed]]
obj.Ubertip = [[增加一个友军单位<Ablo.DataA1.%>%的攻击速度和<Ablo.DataB1.%>%的移动速度。|n持续<Ablo.Dur1>秒。]]
obj = slk.ability.A009:new('A009') 
obj.Name = [[Get Pissed]]
obj.Tip = [[Get Pi|cffffcc00s|rsed]]
obj.Ubertip = [[增加一个友军单位<Ablo.DataA1.%>%的攻击速度和<Ablo.DataB1.%>%的移动速度。|n持续<Ablo.Dur1>秒。]]
obj = slk.ability.A00A:new('A00A') 
obj.Name = [[Get Pissed]]
obj.Tip = [[Get Pi|cffffcc00s|rsed]]
obj.Ubertip = [[增加一个友军单位<Ablo.DataA1.%>%的攻击速度和<Ablo.DataB1.%>%的移动速度。|n持续<Ablo.Dur1>秒。]]
obj = slk.ability.A00B:new('A00B') 
obj.Name = [[Goos Frabah]]
obj.Tip = [[Goos Frabah]]
obj.Ubertip = [[提高周围友军单位<ACat.DataA1.%>%的远程攻击力。]]
obj = slk.ability.A00C:new('A00C') 
obj.Name = [[Slow]]
obj.Tip = [[Slow]]
obj.Ubertip = [[This tower attacks so devistatingly hard that it gives enemies brain damage.]]
